"""Shared helpers for generated tool functions.

Provides state access utilities used by all substep tool files.
Generated by Agent Factory — edit factory/templates/tool_helpers.py.j2, not this file.
"""


def _los(state: dict, key: str, default=None):
    """Get a LOS field value from state.

    Usage:
        address = _los(state, "property_address")
    """
    entry = state.get("los_fields", {}).get(key, {})
    return entry.get("value", default) if isinstance(entry, dict) else default


def _doc(state: dict, key: str, default=None):
    """Get a doc field value from state.

    Usage:
        cd_amount = _doc(state, "cd_loan_amount")
    """
    entry = state.get("doc_fields", {}).get(key, {})
    return entry.get("value", default) if isinstance(entry, dict) else default


def _efolder_present(state: dict, doc_type: str) -> bool:
    """Return True if a document of doc_type exists in the eFolder (regardless of extraction).

    Checks efolder_documents directly — use this for presence checks instead of
    _doc() which returns an extracted field value (can be None even if doc exists).

    Usage:
        if not _efolder_present(state, "1003 URLA"):
            # flag as missing
    """
    entry = state.get("efolder_documents", {}).get(doc_type)
    if not entry:
        return False
    if isinstance(entry, dict):
        # Ground-truth presence: # of attachments in the actual eFolder bucket from the
        # GET /documents listing (not the extraction cache). Decisive when present;
        # older states without it fall back to the copy_count heuristic.
        listing_count = entry.get("efolder_listing_count")
        if listing_count is not None:
            return listing_count > 0
        return bool(entry.get("copy_count", 0) or entry.get("attachment_id") or entry.get("extracted_fields"))
    return bool(entry)


def _efolder_bucket(state: dict, doc_type: str) -> str:
    """Return the actual Encompass eFolder bucket title for a canonical doc type.

    The bucket name is stored on the document entry in efolder_documents as
    'encompass_bucket'. Falls back to the canonical doc_type name if not set
    (i.e., the canonical name is the same as the Encompass bucket title).

    Usage:
        bucket = _efolder_bucket(state, "VOE - non service provider")
    """
    entry = state.get("efolder_documents", {}).get(doc_type, {})
    if isinstance(entry, dict):
        return entry.get("encompass_bucket") or doc_type
    return doc_type


def _doc_coords(state: dict, doc_type: str, matched_copy_index=None):
    """Return DocRepo/S3 coordinates for a doc_type, or None if it is absent.

    Coordinates (not signed URLs) are returned so the frontend can mint a fresh
    presigned URL on demand from the DocRepo GET endpoint (clientId=client_id,
    docId=doc_id). Includes per-attachment ``copies`` so multi-copy buckets
    (VOE, Bank Statement, ...) can be displayed in full.

    Returns None when the document is not present in the eFolder, so callers
    only attach a reference when there is actually a file to link.
    """
    if not _efolder_present(state, doc_type):
        return None
    entry = state.get("efolder_documents", {}).get(doc_type)
    if not isinstance(entry, dict):
        return None
    copies = []
    for c in entry.get("copies", []) or []:
        if not isinstance(c, dict):
            continue
        copies.append({
            "copy_index": c.get("copy_index"),
            "doc_id": c.get("docrepo_location"),
            "bucket": c.get("docrepo_bucket"),
            "client_id": c.get("docrepo_client_id"),
            "attachment_id": c.get("attachment_id"),
            "status": c.get("status"),
        })
    ref = {
        "doc_type": doc_type,
        "client_id": entry.get("docrepo_client_id"),
        "doc_id": entry.get("docrepo_location"),
        "bucket": entry.get("docrepo_bucket"),
        "attachment_id": entry.get("attachment_id"),
        "encompass_bucket": entry.get("encompass_bucket") or doc_type,
        "copies": copies,
    }
    if matched_copy_index is not None:
        ref["matched_copy_index"] = matched_copy_index
    return ref


def _relevant_docs(state: dict, *field_keys: str, doc_types=None, matched=None) -> list:
    """Build a flag's ``relevant_documents`` as DocRepo coordinate refs.

    - ``field_keys``: doc_field keys whose ``source_document`` (extraction
      provenance) identifies the document that supplied the value.
    - ``doc_types``: explicit canonical doc-type names to include directly.
    - ``matched``: optional {doc_type: copy_index} marking the copy that
      triggered the flag.

    Only documents actually present in the eFolder are returned (absent docs
    have no coordinates). Order-stable and de-duplicated.
    """
    matched = matched or {}
    names: list = []
    seen: set = set()

    def _add(name):
        name = (name or "").strip()
        if name and name not in seen:
            seen.add(name)
            names.append(name)

    df = state.get("doc_fields", {})
    for key in field_keys:
        entry = df.get(key)
        if isinstance(entry, dict):
            _add(entry.get("source_document"))
    for dt in (doc_types or []):
        _add(dt)

    refs = []
    for name in names:
        ref = _doc_coords(state, name, matched_copy_index=matched.get(name))
        if ref:
            refs.append(ref)
    return refs


def _enrich_flag_docs(state: dict, flags: list) -> None:
    """Resolve string-name ``relevant_documents`` on flags into coordinate refs.

    A flag may set ``relevant_documents`` to a list of doc-type names (str) or
    {"name": ..., "matched_copy_index": ...} dicts. This converts them in place
    to DocRepo coordinate refs (via ``_doc_coords``), dropping any doc not
    present in the eFolder. Refs already enriched (dicts carrying ``doc_id``)
    are left untouched.
    """
    for f in flags:
        rd = f.get("relevant_documents")
        if not rd:
            continue
        if all(isinstance(x, dict) and "doc_id" in x for x in rd):
            continue  # already enriched
        refs = []
        for item in rd:
            if isinstance(item, dict):
                name = item.get("name") or item.get("doc_type")
                mci = item.get("matched_copy_index")
            else:
                name, mci = item, None
            ref = _doc_coords(state, name, matched_copy_index=mci)
            if ref:
                refs.append(ref)
        if refs:
            f["relevant_documents"] = refs
        else:
            f.pop("relevant_documents", None)


def _doc_all(state: dict, key: str) -> list:
    """Get all values for a doc field across multiple document copies.

    For multi-copy doc types (e.g., COC forms, purchase agreement addenda),
    returns the list of copy dicts from the ``copies`` key. Falls back to
    a single-element list wrapping the primary value if no copies exist.

    Usage:
        all_coc_changes = _doc_all(state, "coc_changes")
        for copy in all_coc_changes:
            print(copy["value"], copy["source_document"])
    """
    entry = state.get("doc_fields", {}).get(key, {})
    if not isinstance(entry, dict):
        return []
    if "copies" in entry and entry["copies"]:
        return entry["copies"]
    val = entry.get("value")
    if val is not None:
        return [{"value": val, "source_document": entry.get("source_document"), "confidence": entry.get("confidence"), "copy_index": 0}]
    return []


def _profile(state: dict, key: str, default=None):
    """Get a loan profile value from state.

    The loan profile is detected in Step 0 and contains:
        loan_type (str): Conventional, FHA, VA, USDA
        purpose (str): Purchase, Refinance, CashOutRefi
        state (str): 2-letter property state code
        trust (bool): Trust involvement
        note_llc (bool): Originated by Note Mortgage LLC

    Usage:
        if _profile(state, "loan_type") == "FHA":
            ...
        if _profile(state, "state") == "WA":
            ...
    """
    return state.get("loan_profile", {}).get(key, default)


def _write_fields(
    loan_id: str,
    updates: dict,
    substep: str,
    flags: list,
    state: dict,
    labels: dict | None = None,
) -> None:
    """Write fields to Encompass with an audit trail appended to flags.

    - Skips None values — safe to pass a conditional dict without pre-filtering.
    - Appends one ``info-overwrite`` flag per field successfully written.
    - If Encompass rejects one or more fields (unknown id, undefined custom
      field, read-only field, or bad value/format), the resilient writer strips
      the offender(s) and writes the rest. A single readable ``warning`` flag
      then lists each rejected field — with its label and the specific reason —
      so the failure and the remaining successful writes are both surfaced.
    - Appends one ``warning`` flag (with a humanized error message) for any
      non-field error such as a locked loan (409).
    """
    from shared.encompass_io import write_fields_resilient, humanize_write_error

    filtered = {fid: val for fid, val in updates.items() if val is not None}
    if not filtered:
        return

    from datetime import datetime, timezone

    def _label(field_id):
        return (labels or {}).get(field_id, f"Field {field_id}")

    try:
        written, bad_fields = write_fields_resilient(loan_id, filtered, state=state)

        for field_id, value in written.items():
            flags.append({
                "substep": substep,
                "title": f"Auto-corrected: {_label(field_id)}",
                "severity": "info-overwrite",
                "details": f"Field {field_id} set to {value!r}",
                "suggestion": "",
                "resolved": True,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

        if bad_fields:
            detail_lines = [
                f"- {_label(fid)} (id {fid}): {reason}"
                for fid, reason in sorted(bad_fields.items())
            ]
            flags.append({
                "substep": substep,
                "title": f"Field Write Partially Failed — {len(bad_fields)} field(s) skipped",
                "severity": "warning",
                "details": (
                    f"{len(written)} field(s) written successfully. "
                    f"{len(bad_fields)} field(s) were rejected by Encompass and skipped so the "
                    f"rest could save:\n" + "\n".join(detail_lines)
                ),
                "suggestion": (
                    "Correct the rejected field(s) above — fix the field ID/value in the tool's "
                    "FIELD_MAP/YAML, or set the value manually in Encompass if the field is read-only."
                ),
                "resolved": False,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    except Exception as exc:
        flags.append({
            "substep": substep,
            "title": "Field Write Error",
            "severity": "warning",
            "details": (
                f"Could not write field(s) {sorted(filtered.keys())}: "
                f"{humanize_write_error(str(exc))}"
            ),
            "suggestion": "Check if the loan is locked (409) or the credentials/field IDs are valid, then re-run.",
            "resolved": False,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })


def _manual_field(
    manual_fields: list,
    substep: str,
    field_id: str,
    label: str,
    current_value=None,
    reason: str = "",
    suggested_value=None,
) -> None:
    """Register a field the agent deliberately did NOT write.

    Appends a row to the tool's local manual_fields list; the tool must return
    it via ``Command(update={"manual_fields": rows})``. The dashboard's Field
    Writes tab shows these as empty editable rows (with dropdown options from
    field_writes_config.json) so the processor can fill them in.

    Usage:
        manual_rows: list = []
        _manual_field(manual_rows, "14.2", "CX.TAXES", "Taxes",
                      current_value=_los(state, "taxes_dropdown"),
                      reason="Left blank per processor guidance — judgment call")
    """
    from datetime import datetime, timezone

    manual_fields.append({
        "substep": substep,
        "field_id": field_id,
        "label": label,
        "current_value": current_value,
        "reason": reason,
        "suggested_value": suggested_value,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })


# ── Property verification helpers (PUD + new construction via Zillow/HasData) ──
# Used by review_property_listing (1.3) and consumed (via state['property_verification'])
# by update_transmittal_summary (11.1), update_fha_management (12.1), and
# update_hud_transmittal (12.2). Keep the HasData network call in ONE place —
# 1.3 runs it once per loan and stores the result for everyone else.

_CONDO_PUD_TYPES = {"condo", "condominium", "pud", "planned unit development"}


def _parse_money_loose(val) -> float | None:
    if val is None:
        return None
    try:
        cleaned = str(val).replace("$", "").replace(",", "").strip()
        return float(cleaned) if cleaned else None
    except (ValueError, TypeError):
        return None


def _is_attached_dwelling(val) -> bool:
    """True if a property/attachment type string indicates an Attached dwelling."""
    if not val:
        return False
    low = str(val).lower()
    # Guard against "Detached" matching the "attached" substring.
    return "attach" in low and "detach" not in low


def _is_condo_or_pud(property_type) -> bool:
    if not property_type:
        return False
    return any(t in str(property_type).lower() for t in _CONDO_PUD_TYPES)


def _zillow_search_url(street=None, city=None, state=None, zip_=None) -> str | None:
    """Build a Zillow address-search deep link for the processor to visually verify."""
    from urllib.parse import quote
    parts = [p.strip() for p in (street, city, state, zip_) if p and str(p).strip()]
    if not parts:
        return None
    return "https://www.zillow.com/homes/" + quote(" ".join(parts)) + "_rb/"


def _lookup_zillow_facts(state: dict):
    """Best-effort Zillow/HasData lookup. Returns ZillowPropertyFacts; never raises."""
    try:
        from shared.zillow_client import lookup_property_sync
        return lookup_property_sync(
            _los(state, "property_address"),
            _los(state, "property_city"),
            _los(state, "property_state"),
            _los(state, "property_zip"),
        )
    except Exception:  # noqa: BLE001 — a lookup must never break the agent
        from shared.zillow_client import ZillowPropertyFacts
        return ZillowPropertyFacts(found=False, error="lookup raised")


def _detect_pud_signals(state: dict, zillow_facts=None) -> dict:
    """Gather PUD signals from appraisal + Encompass heuristic + Zillow.

    Returns a dict suitable for state['property_verification']['pud']:
      is_condo, pud_signals, strong, zillow_url, zillow_subdivision,
      zillow_attached, zillow_signals, appraisal_says_pud, hoa_present,
      attached, home_type, structure_type, hoa_fee, found, error
    """
    from shared.zillow_client import is_pud_indicative

    property_type = _los(state, "property_type")
    hoa_dues = _los(state, "hoa_dues_monthly")
    attachment_type = _los(state, "attachment_type")

    # (a) document-backed: appraisal "Project Type" checkbox == PUD
    def _truthy(v) -> bool:
        return str(v).strip().lower() in ("true", "yes", "1", "y")

    _appraisal_pud_flag = _doc(state, "appraisal_pud")
    _appraisal_property_type = _doc(state, "property_type")  # DOC (appraisal), not LOS
    appraisal_project_type = _doc(state, "appraisal_project_type")
    appraisal_says_pud = (
        _truthy(_appraisal_pud_flag)
        or any(t in str(_appraisal_property_type or "").lower() for t in ("pud", "planned unit"))
        or any(t in (appraisal_project_type or "").lower() for t in ("pud", "planned unit"))
    )

    # (b) heuristic: HOA dues present + Attached dwelling
    hoa_amt = _parse_money_loose(hoa_dues)
    hoa_present = hoa_amt is not None and hoa_amt > 0
    attached = _is_attached_dwelling(attachment_type) or _is_attached_dwelling(property_type)

    # (c) external — Zillow (reuse precomputed facts when the caller already looked up)
    zf = zillow_facts if zillow_facts is not None else _lookup_zillow_facts(state)
    zillow_url = zf.url if zf.found else None
    zillow_subdivision = zf.subdivision if zf.found else None
    zillow_attached = bool(zf.has_attached_property) if zf.found else False
    zillow_signals: list = []
    if zf.found:
        _, zillow_signals = is_pud_indicative(zf)
        if zillow_attached:
            attached = True

    pud_signals: list = []
    is_condo = _is_condo_or_pud(property_type)
    if not is_condo:
        if appraisal_says_pud:
            if _truthy(_appraisal_pud_flag):
                src = f"appraisal_pud={_appraisal_pud_flag!r}"
            elif any(t in str(_appraisal_property_type or "").lower() for t in ("pud", "planned unit")):
                src = f"property_type={_appraisal_property_type!r}"
            else:
                src = f"appraisal_project_type={appraisal_project_type!r}"
            pud_signals.append(f"Appraisal indicates PUD ({src})")
        if hoa_present:
            pud_signals.append(f"HOA dues present (field 233 = {hoa_dues})")
        if attached:
            pud_signals.append("Property is Attached (Encompass)")
        if zillow_signals:
            pud_signals.extend(zillow_signals)

    strong = (
        (not is_condo)
        and (
            appraisal_says_pud
            or (hoa_present and attached)
            or len(zillow_signals) >= 2
        )
    )

    deep_link = zillow_url or _zillow_search_url(
        _los(state, "property_address"),
        _los(state, "property_city"),
        _los(state, "property_state"),
        _los(state, "property_zip"),
    )

    return {
        "is_condo": is_condo,
        "pud_signals": pud_signals,
        "strong": strong,
        "zillow_url": zillow_url,
        "zillow_deep_link": deep_link,
        "zillow_subdivision": zillow_subdivision,
        "zillow_attached": zillow_attached,
        "zillow_signals": list(zillow_signals),
        "appraisal_says_pud": appraisal_says_pud,
        "hoa_present": hoa_present,
        "attached": attached,
        "home_type": zf.home_type if zf.found else None,
        "structure_type": zf.structure_type if zf.found else None,
        "hoa_fee": zf.hoa_fee if zf.found else None,
        "found": bool(zf.found),
        "error": zf.error if not zf.found else None,
    }


def _detect_new_construction(state: dict, zillow_facts=None) -> dict:
    """Detect new construction (< ~1 year) from Zillow year_built / isNewConstruction.

    Returns a dict suitable for state['property_verification']['new_construction']:
      is_new_construction, year_built, zillow_flag, zillow_url, confidence, found, error
    """
    from shared.zillow_client import is_new_construction as _is_new

    zf = zillow_facts if zillow_facts is not None else _lookup_zillow_facts(state)
    if not zf.found:
        return {
            "is_new_construction": False,
            "year_built": None,
            "zillow_flag": None,
            "zillow_url": None,
            "confidence": "none",
            "found": False,
            "error": zf.error,
        }

    is_new = _is_new(zf)
    # Confidence: year_built in range is primary; bare isNewConstruction flag is weaker.
    if is_new and zf.year_built is not None:
        confidence = "high"
    elif is_new and zf.is_new_construction_flag is True:
        confidence = "medium"
    else:
        confidence = "none"

    return {
        "is_new_construction": is_new,
        "year_built": zf.year_built,
        "zillow_flag": zf.is_new_construction_flag,
        "zillow_url": zf.url,
        "confidence": confidence,
        "found": True,
        "error": None,
    }


def _get_or_detect_property_verification(state: dict) -> dict:
    """Return state['property_verification'] or compute it (defensive fallback).

    Prefer the precomputed result from review_property_listing (1.3). Fall back
    to a live HasData lookup only when the key is missing (e.g. 1.3 was skipped
    in dev mode) so downstream tools still work.
    """
    existing = state.get("property_verification")
    if isinstance(existing, dict) and ("pud" in existing or "new_construction" in existing):
        return existing
    zf = _lookup_zillow_facts(state)
    return {
        "pud": _detect_pud_signals(state, zillow_facts=zf),
        "new_construction": _detect_new_construction(state, zillow_facts=zf),
    }
