"""ProcessorAgent Agent v1.0.0 — Generated entry point.

Generated by Agent Factory. Do not edit unless you know what you're doing.
The enforcement logic, reducers, and resolvers are battle-tested.
"""

import json
import logging
import os
import sys
from datetime import datetime, timezone
from typing import Annotated, Any, NotRequired

from dotenv import load_dotenv
from langchain_core.messages import ToolMessage

load_dotenv()

# Add project root to path for shared/ imports
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
PARENT_ROOT = os.path.dirname(PROJECT_ROOT)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
if PARENT_ROOT not in sys.path:
    sys.path.insert(0, PARENT_ROOT)

from copilotagent import create_deep_agent
from langchain.agents.middleware.types import AgentMiddleware, AgentState, OmitFromInput
from langgraph.graph.message import add_messages

from registry import (
    STEP_ORDER,
    get_step_config,
    get_step_number,
    is_step_skipped,
    is_substep_skipped,
    get_next_step,
    get_tools_for_step,
    get_step_tools_excluding_skipped,
    generate_workflow_overview,
    GENERAL_TOOLS,
    SKIP_STEP_TOOLS,
)
from step_loader import load_plan_content

logger = logging.getLogger(__name__)

MAX_TOOL_RESULT_SIZE = 15000


# ═══════════════════════════════════════════════════════════════════════
# Reducers
# ═══════════════════════════════════════════════════════════════════════

def merge_dicts(existing: dict | None, new: dict | None) -> dict:
    """Deep merge two dictionaries, preserving nested structures."""
    if existing is None:
        return new or {}
    if new is None:
        return existing
    result = {**existing}
    for key, value in new.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = merge_dicts(result[key], value)
        else:
            result[key] = value
    return result


def last_value_reducer(existing: Any | None, new: Any | None) -> Any | None:
    """Take the new value, falling back to existing if new is None."""
    return new if new is not None else existing


def dedupe_flags(existing: list | None, new: list | None) -> list:
    """Merge flags lists with deduplication by (substep, title).

    If the same (substep, title) appears again and the new entry is resolved
    while the stored entry is not, the new entry replaces the old one so
    follow-up tools can clear warnings raised in earlier steps.
    """
    all_flags = (existing or []) + (new or [])
    order: list[tuple[str, str]] = []
    by_key: dict[tuple[str, str], dict] = {}
    for flag in all_flags:
        if not isinstance(flag, dict):
            continue
        key = (flag.get("substep", ""), flag.get("title", ""))
        if "resolved" not in flag:
            flag["resolved"] = False
        if "timestamp" not in flag:
            flag["timestamp"] = datetime.now(timezone.utc).isoformat()
        flag.pop("hard_stop", None)

        if key not in by_key:
            by_key[key] = flag
            order.append(key)
        else:
            prev = by_key[key]
            if not prev.get("resolved") and flag.get("resolved"):
                by_key[key] = flag
    return [by_key[k] for k in order]


def truncate_messages(existing: list | None, new: list | None) -> list:
    """Merge messages with truncation of large tool results."""
    merged = add_messages(existing, new)
    truncated = []
    for msg in merged:
        if isinstance(msg, ToolMessage):
            content = msg.content
            if isinstance(content, str) and len(content) > MAX_TOOL_RESULT_SIZE:
                truncated_content = content[:MAX_TOOL_RESULT_SIZE] + "\n... [TRUNCATED]"
                truncated.append(ToolMessage(
                    content=truncated_content,
                    tool_call_id=msg.tool_call_id,
                    name=msg.name if hasattr(msg, "name") else None,
                ))
            else:
                truncated.append(msg)
        else:
            truncated.append(msg)
    return truncated


# ═══════════════════════════════════════════════════════════════════════
# State Schema
# ═══════════════════════════════════════════════════════════════════════

class ProcessorAgentState(AgentState):
    """State schema for ProcessorAgent agent."""

    # ── Input fields (shown in UI) ──
    loan_number: str
    env: str
    borrower_name: NotRequired[str]
    additional_info: NotRequired[dict]

    # ── Core data (set in Step 0) ──
    loan_id: Annotated[NotRequired[str], OmitFromInput, last_value_reducer]
    los_fields: Annotated[NotRequired[dict], OmitFromInput, merge_dicts]
    doc_fields: Annotated[NotRequired[dict], OmitFromInput, merge_dicts]
    loan_summary: Annotated[NotRequired[dict], OmitFromInput, last_value_reducer]

    # ── Issues and tracking ──
    flags: Annotated[NotRequired[list[dict]], OmitFromInput, dedupe_flags]
    pending_field_updates: Annotated[NotRequired[list[dict]], OmitFromInput]
    review_list: Annotated[NotRequired[list[dict]], OmitFromInput]

    # ── Workflow progress ──
    current_step: Annotated[NotRequired[str | None], OmitFromInput, last_value_reducer]
    current_substep: Annotated[NotRequired[str | None], OmitFromInput, last_value_reducer]
    workflow_plan: Annotated[NotRequired[dict | None], OmitFromInput, last_value_reducer]
    dynamic_skipping: Annotated[NotRequired[list[str]], OmitFromInput, last_value_reducer]
    step_reports: Annotated[NotRequired[dict[str, dict]], OmitFromInput, merge_dicts]
    step_fullReports: Annotated[NotRequired[dict[str, dict]], OmitFromInput, merge_dicts]

    # ── Files and UI ──
    loan_files: Annotated[NotRequired[dict[str, dict]], OmitFromInput, merge_dicts]

    # ── Audit ──
    step_start_message_index: Annotated[NotRequired[int], OmitFromInput, last_value_reducer]
    conversation_summary: Annotated[NotRequired[str], OmitFromInput, last_value_reducer]
    _summarized_up_to_index: Annotated[NotRequired[int], OmitFromInput, last_value_reducer]
    notes: Annotated[NotRequired[list[dict]], OmitFromInput]

    # ── Messages ──
    messages: Annotated[list, truncate_messages]


# ═══════════════════════════════════════════════════════════════════════
# Step Detection
# ═══════════════════════════════════════════════════════════════════════

def get_current_step_from_state(state: dict) -> str:
    """Get the current step ID from state.

    Priority: current_step > step_reports in_progress > last completed + 1 > first step
    """
    first_step = STEP_ORDER[0] if STEP_ORDER else "STEP_00"
    current_step = state.get("current_step")

    if current_step == "COMPLETED":
        return "COMPLETED"

    if current_step:
        step_reports = state.get("step_reports", {})
        step_status = step_reports.get(f"{current_step}_status", {}).get("status")

        if step_status in ("completed", "skipped"):
            candidate = get_next_step(current_step)
            while candidate:
                cand_status = step_reports.get(f"{candidate}_status", {}).get("status")
                if cand_status not in ("completed", "skipped"):
                    return candidate
                candidate = get_next_step(candidate)
            return "COMPLETED"
        return current_step

    step_reports = state.get("step_reports", {})

    # Look for step-level in_progress
    for key, value in step_reports.items():
        if key.endswith("_status") and isinstance(value, dict):
            parts = key.replace("_status", "").split("_")
            if len(parts) == 2 and parts[0] == "STEP":
                if value.get("status") == "in_progress":
                    return value.get("step_id", first_step)

    # Check substep in_progress
    for key, value in step_reports.items():
        if key.endswith("_status") and isinstance(value, dict):
            if value.get("status") == "in_progress":
                step_id = value.get("step_id")
                if step_id:
                    return step_id

    # Last completed + 1
    completed_nums = set()
    for key, value in step_reports.items():
        if key.endswith("_status") and isinstance(value, dict):
            parts = key.replace("_status", "").split("_")
            if len(parts) == 2 and parts[0] == "STEP" and value.get("status") == "completed":
                step_id = value.get("step_id")
                if step_id:
                    try:
                        completed_nums.add(int(step_id.replace("STEP_", "")))
                    except ValueError:
                        pass

    if completed_nums:
        last_num = max(completed_nums)
        next_num = last_num + 1
        max_step = max(int(s.replace("STEP_", "")) for s in STEP_ORDER)
        if next_num <= max_step:
            return f"STEP_{next_num:02d}"
        return "COMPLETED"

    return first_step


# ═══════════════════════════════════════════════════════════════════════
# Resolvers
# ═══════════════════════════════════════════════════════════════════════

_ALL_TOOLS_REF = None


def resolve_tools_for_step(state: dict) -> list:
    """Return only the tools relevant to the current step.

    This resolver:
    1. Excludes tools from config-skipped substeps (dev mode)
    2. Excludes tools from dynamically-skipped substeps (runtime state)
    3. Returns only SKIP_STEP_TOOLS when the entire step is skipped
    4. Returns empty list when workflow is COMPLETED
    """
    global _ALL_TOOLS_REF

    if _ALL_TOOLS_REF is None:
        return []

    current_step = get_current_step_from_state(state)

    if current_step == "COMPLETED":
        return []

    # If the whole step is skipped, only allow write_todo and status tools
    if is_step_skipped(current_step):
        return [t for t in _ALL_TOOLS_REF
                if getattr(t, "name", getattr(t, "__name__", "")) in SKIP_STEP_TOOLS]

    # Build set of dynamically-skipped substep IDs from state
    dynamic_skipping = set(state.get("dynamic_skipping", []) or [])

    # Get allowed tool names, excluding both config-skipped and dynamically-skipped substeps
    allowed_names = get_step_tools_excluding_skipped(
        current_step, extra_skip_substeps=dynamic_skipping
    )

    return [t for t in _ALL_TOOLS_REF
            if getattr(t, "name", getattr(t, "__name__", "")) in allowed_names]


def resolve_plan_for_step(state: dict) -> str | None:
    """Return the plan for the current step."""
    current_step = get_current_step_from_state(state)

    if current_step == "COMPLETED":
        return None
    if is_step_skipped(current_step):
        return None

    try:
        return load_plan_content(current_step)
    except Exception as e:
        logger.warning(f"[PLAN_RESOLVER] Could not load plan for {current_step}: {e}")
        return None


# ═══════════════════════════════════════════════════════════════════════
# Middleware
# ═══════════════════════════════════════════════════════════════════════

class ProcessorAgentMiddleware(AgentMiddleware):
    """Middleware that provides the ProcessorAgent state schema."""
    state_schema = ProcessorAgentState


# ═══════════════════════════════════════════════════════════════════════
# Agent Creation
# ═══════════════════════════════════════════════════════════════════════

def create_agent():
    """Create and return the ProcessorAgent agent."""
    global _ALL_TOOLS_REF

    # Import all tools
    from tools import get_all_tools
    all_tools = get_all_tools()
    _ALL_TOOLS_REF = all_tools

    # Build system prompt
    plans_dir = os.path.join(PROJECT_ROOT, "plans")
    with open(os.path.join(plans_dir, "system_prompt.template.md"), "r") as f:
        system_prompt = f.read()

    # Replace workflow overview placeholder
    overview = generate_workflow_overview()
    system_prompt = system_prompt.replace("{{WORKFLOW_OVERVIEW}}", overview)

    agent = create_deep_agent(
        model="claude-sonnet-4-20250514",
        tools=all_tools,
        system_prompt=system_prompt,
        middleware=(ProcessorAgentMiddleware(),),
        tool_resolver=resolve_tools_for_step,
        plan_resolver=resolve_plan_for_step,
        name="processoragent_agent",
    )

    return agent


# Entry point for LangGraph
graph = create_agent()
