"""Workflow Registry — Generated from workflow_config.json.

Single source of truth for step/substep configuration.
Generated by Agent Factory.
"""

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Optional

logger = logging.getLogger(__name__)

CONFIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config")


@dataclass
class SubstepConfig:
    name: str
    tools: list[str] = field(default_factory=list)


@dataclass
class StepConfig:
    name: str
    phase: str
    plan_file: str = ""
    tools: list[str] = field(default_factory=list)
    substeps: dict[str, SubstepConfig] = field(default_factory=dict)


# ── General tools available to all steps ──
GENERAL_TOOLS = {"write_todo", "get_workflow_status", "save_step_report"}
SKIP_STEP_TOOLS = {"write_todo", "get_workflow_status"}

# ── Load configuration ──

def _load_workflow_config() -> dict:
    path = os.path.join(CONFIG_DIR, "workflow_config.json")
    with open(path, "r") as f:
        return json.load(f)


_config = _load_workflow_config()

# Step order
STEP_ORDER = _config.get("step_order", [])

# Runtime settings (loaded from workflow_config.json dev_mode section)
class _DevMode:
    def __init__(self):
        dev = _config.get("dev_mode", {})
        self.skip_steps = set(dev.get("skip_steps", []))
        self.skip_substeps = set(dev.get("skip_substeps", []))
        self.dry_run = dev.get("dry_run", False)
        self.fixture = dev.get("fixture", {})
        self.source = "config"

    @property
    def enabled(self) -> bool:
        """Skipping is active whenever there are steps or substeps to skip."""
        return bool(self.skip_steps or self.skip_substeps)

DEV_MODE = _DevMode()


def get_fixture_config() -> dict:
    """Return fixture API settings from dev_mode config."""
    return DEV_MODE.fixture


def apply_dev_mode_config(input_config: dict | None = None) -> None:
    """Apply dev mode configuration from input."""
    if input_config:
        DEV_MODE.skip_steps = set(input_config.get("skip_steps", DEV_MODE.skip_steps))
        DEV_MODE.skip_substeps = set(input_config.get("skip_substeps", DEV_MODE.skip_substeps))
        DEV_MODE.dry_run = input_config.get("dry_run", DEV_MODE.dry_run)
        DEV_MODE.source = "input"


# Build step configs
_STEPS: dict[str, StepConfig] = {}

for step_id, step_data in _config.get("steps", {}).items():
    substeps = {}
    for ss_key, ss_data in step_data.get("substeps", {}).items():
        substeps[ss_key] = SubstepConfig(
            name=ss_data.get("name", ""),
            tools=ss_data.get("tools", []),
        )

    _STEPS[step_id] = StepConfig(
        name=step_data.get("name", ""),
        phase=step_data.get("phase", ""),
        plan_file=step_data.get("plan_file", ""),
        tools=step_data.get("tools", []),
        substeps=substeps,
    )


# ── Public API ──

def get_step_config(step_id: str) -> Optional[StepConfig]:
    return _STEPS.get(step_id)


def get_step_number(step_id: str) -> int:
    try:
        return int(step_id.replace("STEP_", ""))
    except ValueError:
        return -1


def get_next_step(step_id: str) -> Optional[str]:
    try:
        idx = STEP_ORDER.index(step_id)
        if idx + 1 < len(STEP_ORDER):
            return STEP_ORDER[idx + 1]
    except ValueError:
        pass
    return None


def is_step_skipped(step_id: str) -> bool:
    if not DEV_MODE.enabled:
        return False
    return step_id in DEV_MODE.skip_steps


def is_substep_skipped(step_id: str, substep_id: str) -> bool:
    if not DEV_MODE.enabled:
        return False
    return substep_id in DEV_MODE.skip_substeps


def get_step_tools(step_id: str) -> list[str]:
    """Get ALL tool names for a step (ignores substep skipping)."""
    cfg = get_step_config(step_id)
    if not cfg:
        return []
    if is_step_skipped(step_id):
        return list(SKIP_STEP_TOOLS)
    return list(GENERAL_TOOLS | set(cfg.tools))


def get_step_tools_excluding_skipped(
    step_id: str,
    extra_skip_substeps: set[str] | None = None,
) -> set[str]:
    """Get tool names for a step, EXCLUDING tools from skipped substeps.

    This is the primary function used by the tool resolver to determine
    which tools the model should see. It respects both config-level skipping
    (dev mode) and dynamic skipping (runtime state).

    Args:
        step_id: Step ID (e.g., "STEP_02")
        extra_skip_substeps: Additional substep IDs to treat as skipped,
            typically from state["dynamic_skipping"].

    Returns:
        Set of allowed tool names (always includes GENERAL_TOOLS).
    """
    cfg = get_step_config(step_id)
    if not cfg:
        return set()
    if is_step_skipped(step_id):
        return set(SKIP_STEP_TOOLS)

    step_num = get_step_number(step_id)
    allowed = set(GENERAL_TOOLS)

    for ss_key, ss_cfg in cfg.substeps.items():
        full_id = f"{step_num}.{ss_key}"

        # Skip config-skipped substeps (dev mode)
        if is_substep_skipped(step_id, full_id):
            continue

        # Skip dynamically-skipped substeps (runtime)
        if extra_skip_substeps and full_id in extra_skip_substeps:
            continue

        # Add this substep's tools
        for tool_name in ss_cfg.tools:
            if tool_name:
                allowed.add(tool_name)

    return allowed


def get_tools_for_step(all_tools: list, step_id: str) -> list:
    """Filter tool objects to only those available for the given step.

    NOTE: This returns ALL step tools (ignores substep skipping).
    For substep-aware filtering, use get_step_tools_excluding_skipped().
    """
    allowed = set(get_step_tools(step_id))
    return [t for t in all_tools
            if getattr(t, "name", getattr(t, "__name__", "")) in allowed]


def generate_workflow_overview() -> str:
    """Generate a compact workflow overview listing only steps (no substeps)."""
    lines = []
    current_phase = None

    for step_id in STEP_ORDER:
        cfg = get_step_config(step_id)
        if not cfg:
            continue

        if cfg.phase != current_phase:
            current_phase = cfg.phase
            lines.append(f"\n### Phase: {current_phase}")

        step_num = get_step_number(step_id)
        ss_count = len(cfg.substeps)
        skipped = " [SKIPPED]" if is_step_skipped(step_id) else ""
        lines.append(f"- **Step {step_num}** — {cfg.name} ({ss_count} substeps){skipped}")

    return "\n".join(lines)
