"""Tools package — Auto-generated imports.

Generated by Agent Factory.
Each substep tool lives in its own file (named after the tool function).
"""

# General tools (always available)
from .general import write_todo, get_workflow_status, save_step_report

# Step 0: Data Gathering (auto-generated)
from .data_gathering import find_loan, fetch_los_fields, fetch_doc_fields, build_loan_summary

# STEP_01 / 1.1: Document Presence Check
from .run_pre_checks import run_pre_checks
# STEP_02 / 2.1: Review Borrower Summary - Origination
from .review_borrower_summary import review_borrower_summary
# STEP_03 / 3.1: Review 1003 URLA Page 1
from .review_urla_page1 import review_urla_page1
# STEP_04 / 4.1: Employment Verification (1b VOE)
from .review_urla_employment import review_urla_employment
# STEP_04 / 4.2: Other Income (1e)
from .review_urla_other_income import review_urla_other_income
# STEP_05 / 5.1: Assets and VOD (2a)
from .review_urla_assets import review_urla_assets
# STEP_05 / 5.2: EMD Check (2b)
from .review_urla_emd import review_urla_emd
# STEP_05 / 5.3: Liabilities and VOL (2c)
from .review_urla_liabilities import review_urla_liabilities
# STEP_05 / 5.4: Other Assets and REO (2d, Section 3)
from .review_urla_reo import review_urla_reo
# STEP_06 / 6.1: Downpayment Sources (4b, 4c, 4d)
from .review_urla_downpayment import review_urla_downpayment
# STEP_06 / 6.2: Declarations (Section 5)
from .review_urla_declarations import review_urla_declarations
# STEP_06 / 6.3: Ethnicity and ID Cross-Check
from .review_urla_ethnicity import review_urla_ethnicity
# STEP_07 / 7.1: Draft Cover Letter / Submission Notes
from .draft_cover_letter import draft_cover_letter
# STEP_08 / 8.1: Update Borrower Vesting
from .update_borrower_vesting import update_borrower_vesting
# STEP_09 / 9.1: Update Transmittal Summary
from .update_transmittal_summary import update_transmittal_summary
# STEP_10 / 10.1: Order Appraisal
from .order_appraisal import order_appraisal
# STEP_10 / 10.2: Order Condo Questionnaire
from .order_condo_questionnaire import order_condo_questionnaire
# STEP_10 / 10.3: File Contacts and Title Order Email
from .send_title_order_email import send_title_order_email
# STEP_11 / 11.1: Prep eFolder - Delete Junk Buckets
from .prep_efolder import prep_efolder
# STEP_12 / 12.1: Run Ocrolus and Income Calc
from .run_additional_services import run_additional_services
# STEP_13 / 13.1: Print Forms to eFolder
from .print_forms import print_forms
# STEP_14 / 14.1: Run Fannie Mae DU
from .run_fannie_aus import run_fannie_aus
# STEP_14 / 14.2: Run Freddie Mac LP
from .run_freddie_aus import run_freddie_aus
# STEP_15 / 15.1: Processor Workflow Update
from .update_processor_workflow import update_processor_workflow
# STEP_15 / 15.2: Processor Closing Update
from .update_processor_closing import update_processor_closing
# STEP_16 / 16.1: Review All Flags (HITL)
from .review_flags import review_flags
# STEP_17 / 17.1: Mark Docs Ready-for-UW
from .mark_docs_ready_for_uw import mark_docs_ready_for_uw
# STEP_17 / 17.2: Required Fields - Click Finished
from .complete_required_fields import complete_required_fields
# STEP_17 / 17.3: Milestone Change and Processor Name
from .update_milestone import update_milestone
# STEP_17 / 17.4: Final eFolder Cleanup
from .final_efolder_cleanup import final_efolder_cleanup
# STEP_18 / 18.1: Lock Desk Email (if locked + address change)
from .send_lock_desk_email import send_lock_desk_email
# STEP_18 / 18.2: Request Locked LE (if locked + no Locked LE)
from .request_locked_le import request_locked_le
# STEP_18 / 18.3: EMD Email to Realtor (if EMD missing or mismatch)
from .send_emd_email import send_emd_email

def get_all_tools() -> list:
    """Return all tool functions."""
    tools = [
        # General
        write_todo,
        get_workflow_status,
        save_step_report,
        # Step 0
        find_loan,
        fetch_los_fields,
        fetch_doc_fields,
        build_loan_summary,
    ]
    tools.append(run_pre_checks)
    tools.append(review_borrower_summary)
    tools.append(review_urla_page1)
    tools.append(review_urla_employment)
    tools.append(review_urla_other_income)
    tools.append(review_urla_assets)
    tools.append(review_urla_emd)
    tools.append(review_urla_liabilities)
    tools.append(review_urla_reo)
    tools.append(review_urla_downpayment)
    tools.append(review_urla_declarations)
    tools.append(review_urla_ethnicity)
    tools.append(draft_cover_letter)
    tools.append(update_borrower_vesting)
    tools.append(update_transmittal_summary)
    tools.append(order_appraisal)
    tools.append(order_condo_questionnaire)
    tools.append(send_title_order_email)
    tools.append(prep_efolder)
    tools.append(run_additional_services)
    tools.append(print_forms)
    tools.append(run_fannie_aus)
    tools.append(run_freddie_aus)
    tools.append(update_processor_workflow)
    tools.append(update_processor_closing)
    tools.append(review_flags)
    tools.append(mark_docs_ready_for_uw)
    tools.append(complete_required_fields)
    tools.append(update_milestone)
    tools.append(final_efolder_cleanup)
    tools.append(send_lock_desk_email)
    tools.append(request_locked_le)
    tools.append(send_emd_email)
    return tools


__all__ = [
    "get_all_tools",
    "write_todo",
    "get_workflow_status",
    "save_step_report",
    "find_loan",
    "fetch_los_fields",
    "fetch_doc_fields",
    "build_loan_summary",
    "run_pre_checks",
    "review_borrower_summary",
    "review_urla_page1",
    "review_urla_employment",
    "review_urla_other_income",
    "review_urla_assets",
    "review_urla_emd",
    "review_urla_liabilities",
    "review_urla_reo",
    "review_urla_downpayment",
    "review_urla_declarations",
    "review_urla_ethnicity",
    "draft_cover_letter",
    "update_borrower_vesting",
    "update_transmittal_summary",
    "order_appraisal",
    "order_condo_questionnaire",
    "send_title_order_email",
    "prep_efolder",
    "run_additional_services",
    "print_forms",
    "run_fannie_aus",
    "run_freddie_aus",
    "update_processor_workflow",
    "update_processor_closing",
    "review_flags",
    "mark_docs_ready_for_uw",
    "complete_required_fields",
    "update_milestone",
    "final_efolder_cleanup",
    "send_lock_desk_email",
    "request_locked_le",
    "send_emd_email",
]
