"""Tools package — Auto-generated imports.

Generated by Agent Factory.
Each substep tool lives in its own file (named after the tool function).
"""

# General tools (always available)
from .general import write_todo, get_workflow_status, save_step_report

# Step 0: Data Gathering (auto-generated)
from .data_gathering import find_loan, fetch_los_fields, fetch_doc_fields, build_loan_summary, validate_property_address, extract_almas_images

# STEP_01 / 1.1: Document Presence Check
from .run_pre_checks import run_pre_checks
# STEP_01 / 1.2: File Contacts Check
from .review_file_contacts import review_file_contacts
# STEP_02 / 2.1: Review Borrower Summary - Origination
from .review_borrower_summary import review_borrower_summary
# STEP_03 / 3.1: Update 1003 URLA Lender
from .update_urla_lender import update_urla_lender
# STEP_04 / 4.1: Review 1003 URLA Page 1
from .review_urla_page1 import review_urla_page1
# STEP_05 / 5.1: Employment Verification (2b VOE)
from .review_urla_employment import review_urla_employment
# STEP_05 / 5.2: Other Income (2e)
from .review_urla_other_income import review_urla_other_income
# STEP_06 / 6.1: Assets and VOD (3a)
from .review_urla_assets import review_urla_assets
# STEP_06 / 6.2: EMD Check (3b)
from .review_urla_emd import review_urla_emd
# STEP_06 / 6.3: Liabilities and VOL (3c)
from .review_urla_liabilities import review_urla_liabilities
# STEP_06 / 6.4: Other Assets and REO (3d)
from .review_urla_reo import review_urla_reo
# STEP_07 / 7.1: Downpayment Sources (4b, 4c, 4d)
from .review_urla_downpayment import review_urla_downpayment
# STEP_07 / 7.2: Declarations (Section 5)
from .review_urla_declarations import review_urla_declarations
# STEP_07 / 7.3: Ethnicity and ID Cross-Check
from .review_urla_ethnicity import review_urla_ethnicity
# STEP_08 / 8.1: Draft Cover Letter / Submission Notes
from .draft_cover_letter import draft_cover_letter
# STEP_09 / 9.1: Update Borrower Vesting
from .update_borrower_vesting import update_borrower_vesting
# STEP_10 / 10.1: Update Transmittal Summary
from .update_transmittal_summary import update_transmittal_summary
# STEP_11 / 11.1: FHA Management
from .update_fha_management import update_fha_management
# STEP_11 / 11.2: HUD Transmittal
from .update_hud_transmittal import update_hud_transmittal
# STEP_12 / 12.1: Processor Workflow Update
from .update_processor_workflow import update_processor_workflow
# STEP_12 / 12.2: Processor Closing Update
from .update_processor_closing import update_processor_closing

def get_all_tools() -> list:
    """Return all tool functions."""
    tools = [
        # General
        write_todo,
        get_workflow_status,
        save_step_report,
        # Step 0
        find_loan,
        fetch_los_fields,
        fetch_doc_fields,
        build_loan_summary,
        validate_property_address,
        extract_almas_images,
    ]
    tools.append(run_pre_checks)
    tools.append(review_file_contacts)
    tools.append(review_borrower_summary)
    tools.append(update_urla_lender)
    tools.append(review_urla_page1)
    tools.append(review_urla_employment)
    tools.append(review_urla_other_income)
    tools.append(review_urla_assets)
    tools.append(review_urla_emd)
    tools.append(review_urla_liabilities)
    tools.append(review_urla_reo)
    tools.append(review_urla_downpayment)
    tools.append(review_urla_declarations)
    tools.append(review_urla_ethnicity)
    tools.append(draft_cover_letter)
    tools.append(update_borrower_vesting)
    tools.append(update_transmittal_summary)
    tools.append(update_fha_management)
    tools.append(update_hud_transmittal)
    tools.append(update_processor_workflow)
    tools.append(update_processor_closing)
    return tools


__all__ = [
    "get_all_tools",
    "write_todo",
    "get_workflow_status",
    "save_step_report",
    "find_loan",
    "fetch_los_fields",
    "fetch_doc_fields",
    "build_loan_summary",
    "validate_property_address",
    "extract_almas_images",
    "run_pre_checks",
    "review_file_contacts",
    "review_borrower_summary",
    "update_urla_lender",
    "review_urla_page1",
    "review_urla_employment",
    "review_urla_other_income",
    "review_urla_assets",
    "review_urla_emd",
    "review_urla_liabilities",
    "review_urla_reo",
    "review_urla_downpayment",
    "review_urla_declarations",
    "review_urla_ethnicity",
    "draft_cover_letter",
    "update_borrower_vesting",
    "update_transmittal_summary",
    "update_fha_management",
    "update_hud_transmittal",
    "update_processor_workflow",
    "update_processor_closing",
]
