"""Shared helpers for generated tool functions.

Provides state access utilities used by all substep tool files.
Generated by Agent Factory — edit factory/templates/tool_helpers.py.j2, not this file.
"""


def _los(state: dict, key: str, default=None):
    """Get a LOS field value from state.

    Usage:
        address = _los(state, "property_address")
    """
    entry = state.get("los_fields", {}).get(key, {})
    return entry.get("value", default) if isinstance(entry, dict) else default


def _doc(state: dict, key: str, default=None):
    """Get a doc field value from state.

    Usage:
        cd_amount = _doc(state, "cd_loan_amount")
    """
    entry = state.get("doc_fields", {}).get(key, {})
    return entry.get("value", default) if isinstance(entry, dict) else default


def _efolder_present(state: dict, doc_type: str) -> bool:
    """Return True if a document of doc_type exists in the eFolder (regardless of extraction).

    Checks efolder_documents directly — use this for presence checks instead of
    _doc() which returns an extracted field value (can be None even if doc exists).

    Usage:
        if not _efolder_present(state, "1003 URLA"):
            # flag as missing
    """
    entry = state.get("efolder_documents", {}).get(doc_type)
    if not entry:
        return False
    # Guard against empty/stub entries
    if isinstance(entry, dict):
        return bool(entry.get("copy_count", 0) or entry.get("attachment_id") or entry.get("extracted_fields"))
    return bool(entry)


def _efolder_bucket(state: dict, doc_type: str) -> str:
    """Return the actual Encompass eFolder bucket name used for this document type.

    Returns the canonical doc_type name as fallback if bucket info is not stored.

    Usage:
        bucket = _efolder_bucket(state, "1003 URLA")  # -> "1003"
        f"eFolder bucket: '{bucket}'"
    """
    entry = state.get("efolder_documents", {}).get(doc_type)
    if isinstance(entry, dict):
        return entry.get("encompass_bucket") or doc_type
    return doc_type


def _doc_all(state: dict, key: str) -> list:
    """Get all values for a doc field across multiple document copies.

    For multi-copy doc types (e.g., COC forms, purchase agreement addenda),
    returns the list of copy dicts from the ``copies`` key. Falls back to
    a single-element list wrapping the primary value if no copies exist.

    Usage:
        all_coc_changes = _doc_all(state, "coc_changes")
        for copy in all_coc_changes:
            print(copy["value"], copy["source_document"])
    """
    entry = state.get("doc_fields", {}).get(key, {})
    if not isinstance(entry, dict):
        return []
    if "copies" in entry and entry["copies"]:
        return entry["copies"]
    val = entry.get("value")
    if val is not None:
        return [{"value": val, "source_document": entry.get("source_document"), "confidence": entry.get("confidence"), "copy_index": 0}]
    return []


def _profile(state: dict, key: str, default=None):
    """Get a loan profile value from state.

    The loan profile is detected in Step 0 and contains:
        loan_type (str): Conventional, FHA, VA, USDA
        purpose (str): Purchase, Refinance, CashOutRefi
        state (str): 2-letter property state code
        trust (bool): Trust involvement
        note_llc (bool): Originated by Note Mortgage LLC

    Usage:
        if _profile(state, "loan_type") == "FHA":
            ...
        if _profile(state, "state") == "WA":
            ...
    """
    return state.get("loan_profile", {}).get(key, default)


def _write_fields(
    loan_id: str,
    updates: dict,
    substep: str,
    flags: list,
    state: dict,
    labels: dict | None = None,
) -> None:
    """Write fields to Encompass with an audit trail appended to flags.

    - Skips None values — safe to pass a conditional dict without pre-filtering.
    - Appends one ``info-overwrite`` flag per field successfully written.
    - On 400 invalid field IDs: retries without the bad IDs, then appends one
      compiled ``warning`` flag listing all skipped bad IDs (not per-field, since
      that is a config issue not a per-field business issue).
    - Appends one ``warning`` flag for any other write error.
    """
    from shared.encompass_io import write_fields_resilient

    filtered = {fid: val for fid, val in updates.items() if val is not None}
    if not filtered:
        return

    from datetime import datetime, timezone

    try:
        written, bad_ids = write_fields_resilient(loan_id, filtered, state=state)

        for field_id, value in written.items():
            label = (labels or {}).get(field_id, f"Field {field_id}")
            flags.append({
                "substep": substep,
                "title": f"Auto-corrected: {label}",
                "severity": "info-overwrite",
                "details": f"Field {field_id} set to {value!r}",
                "suggestion": "",
                "resolved": True,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

        if bad_ids:
            bad_labels = [f"{fid} ({(labels or {}).get(fid, 'unknown')})" for fid in sorted(bad_ids)]
            flags.append({
                "substep": substep,
                "title": "Field Write Skipped — Invalid Field IDs",
                "severity": "warning",
                "details": (
                    f"{len(bad_ids)} field ID(s) were rejected by Encompass as invalid and skipped: "
                    f"{', '.join(bad_labels)}. The remaining {len(written)} field(s) were written successfully."
                ),
                "suggestion": "Remove or correct the invalid field IDs from the tool's FIELD_MAP or YAML definition.",
                "resolved": False,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    except Exception as exc:
        flags.append({
            "substep": substep,
            "title": "Field Write Error",
            "severity": "warning",
            "details": f"Could not write field(s) {list(filtered.keys())}: {exc}",
            "suggestion": "Check if the loan is locked or the field ID is correct.",
            "resolved": False,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })
