"""Shared helpers for generated tool functions.

Provides state access utilities used by all substep tool files.
Generated by Agent Factory.
"""

import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


def _los(state: dict, key: str, default=None):
    """Get a LOS field value from state.

    Usage:
        address = _los(state, "property_address")
    """
    entry = state.get("los_fields", {}).get(key, {})
    return entry.get("value", default) if isinstance(entry, dict) else default


def _doc(state: dict, key: str, default=None):
    """Get a doc field value from state.

    Usage:
        cd_amount = _doc(state, "cd_loan_amount")
    """
    entry = state.get("doc_fields", {}).get(key, {})
    return entry.get("value", default) if isinstance(entry, dict) else default


def _doc_all(state: dict, key: str) -> list:
    """Get all values for a doc field across multiple document copies.

    For multi-copy doc types (e.g., COC forms, purchase agreement addenda),
    returns the list of copy dicts from the ``copies`` key. Falls back to
    a single-element list wrapping the primary value if no copies exist.

    Usage:
        all_coc_changes = _doc_all(state, "coc_changes")
        for copy in all_coc_changes:
            print(copy["value"], copy["source_document"])
    """
    entry = state.get("doc_fields", {}).get(key, {})
    if not isinstance(entry, dict):
        return []
    if "copies" in entry and entry["copies"]:
        return entry["copies"]
    val = entry.get("value")
    if val is not None:
        return [{"value": val, "source_document": entry.get("source_document"), "confidence": entry.get("confidence"), "copy_index": 0}]
    return []


def _write_fields(
    loan_id: str,
    updates: dict[str, Any],
    substep: str,
    flags: list,
    state: dict | None = None,
    labels: dict[str, str] | None = None,
) -> None:
    """Write Encompass fields and append audit flags to the caller's flag list.

    For each field written successfully an ``info``-severity flag is appended
    so the processor sees every auto-correction at the Step 16 Flag Review gate.
    On write failure a single ``warning``-severity flag is appended instead.

    Args:
        loan_id:  Encompass loan GUID.
        updates:  ``{field_id: new_value}`` dict — only non-None values are sent.
        substep:  Substep ID string (e.g. ``"2.1"``) stamped onto every flag.
        flags:    The tool's local flag list; flags are appended in-place.
        state:    Optional state dict forwarded to ``write_fields`` for env resolution.
        labels:   Optional ``{field_id: human_label}`` for readable flag titles.
                  Falls back to ``"Field <field_id>"`` when omitted.

    Usage::

        _write_fields(
            loan_id, {"1480": home_phone}, substep="2.1", flags=flags, state=state,
            labels={"1480": "Borrower Cell Phone"},
        )
    """
    clean = {fid: val for fid, val in updates.items() if val is not None}
    if not clean:
        return

    labels = labels or {}
    ts = datetime.now(timezone.utc).isoformat()

    try:
        from shared.encompass_io import write_fields as _encompass_write
        _encompass_write(loan_id, clean, state=state)
        logger.info(f"[WRITE_FIELDS] substep={substep} wrote {len(clean)} field(s): {list(clean)}")
        for fid, val in clean.items():
            label = labels.get(fid, f"Field {fid}")
            flags.append({
                "substep": substep,
                "title": f"Auto-Corrected: {label}",
                "severity": "info",
                "details": f"Field {fid} was empty or incorrect — set to: {val!r}",
                "suggestion": "Confirm this is correct or update manually.",
                "resolved": False,
                "timestamp": ts,
            })
    except Exception as exc:
        logger.error(f"[WRITE_FIELDS] substep={substep} write error: {exc}")
        flags.append({
            "substep": substep,
            "title": "Field Write Error",
            "severity": "warning",
            "details": f"Failed to write fields {list(clean)}: {exc}",
            "suggestion": "Retry or update the fields manually in Encompass.",
            "resolved": False,
            "timestamp": ts,
        })


def _profile(state: dict, key: str, default=None):
    """Get a loan profile value from state.

    The loan profile is detected in Step 0 and contains:
        loan_type (str): Conventional, FHA, VA, USDA
        purpose (str): Purchase, Refinance, CashOutRefi
        state (str): 2-letter property state code
        trust (bool): Trust involvement
        note_llc (bool): Originated by Note Mortgage LLC

    Usage:
        if _profile(state, "loan_type") == "FHA":
            ...
        if _profile(state, "state") == "WA":
            ...
    """
    return state.get("loan_profile", {}).get(key, default)
