"""complete_required_fields — Tool for substep 17.2: Required Fields - Click Finished

Step 17 (STEP_17): Submission
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def complete_required_fields(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Navigate to Encompass Required Fields screen. Confirm all required fields are complete. Click Finished. This auto-places the Cover Letter in the correct eFolder bucket as a side effect (notes.txt:219-220).


    Call this tool during STEP_17 (Submission) as substep 17.2.    Reads LOS: required_fields_status    Flags: Required Fields Incomplete (critical)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[COMPLETE_REQUIRED_FIELDS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    required_fields_status = _los(state, "required_fields_status")  # Field CX.REQUIRED.FIELDS.STATUS: Required Fields Status    # ── Rule: Required Fields Complete ──
    # All Encompass-required fields must be complete. Click Finished to submit. Cover Letter auto-places in eFolder bucket as side effect.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Required Fields Incomplete ──
    # Condition: Encompass required fields screen shows incomplete fields
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "17.2",
    #         "title": "Required Fields Incomplete",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Return to Flag Review — incomplete required fields must be resolved",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "17.2",
        "tool": "complete_required_fields",
        "flags_count": len(flags),
        "message": "Required Fields - Click Finished completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[COMPLETE_REQUIRED_FIELDS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
