"""draft_cover_letter — Tool for substep 7.1: Draft Cover Letter / Submission Notes

Step 7 (STEP_07): Cover Letter
Phase: FORM_UPDATES

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def draft_cover_letter(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Populate CX.KM.SUBMISSION.NOTES using Almas' notes from state["almas_notes"] and loan profile data (AMI eligibility, missing docs, etc.). Clear pre-populated Title Company, Appraisal, and Additional Notes sub-fields. Raise a flag with the draft text so the processor can review and edit at Step 16 Flag Review. Do NOT interrupt here.


    Call this tool during STEP_07 (Cover Letter) as substep 7.1.    Reads LOS: submission_notes, cover_letter_title_company, cover_letter_appraisal, cover_letter_additional_notes, ami_percentage, loan_type    Flags: Cover Letter Draft for Processor Review (info), Almas Notes Missing (warning)    Writes: field corrections for CX.KM.SUBMISSION.NOTES, CX.KM.CL.TITLE.COMPANY, CX.KM.CL.APPRAISAL, CX.KM.CL.ADDITIONAL.NOTES    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[DRAFT_COVER_LETTER] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    submission_notes = _los(state, "submission_notes")  # Field CX.KM.SUBMISSION.NOTES: Submission Notes (Cover Letter)    cover_letter_title_company = _los(state, "cover_letter_title_company")  # Field CX.KM.CL.TITLE.COMPANY: Cover Letter - Title Company (pre-populated)    cover_letter_appraisal = _los(state, "cover_letter_appraisal")  # Field CX.KM.CL.APPRAISAL: Cover Letter - Appraisal (pre-populated)    cover_letter_additional_notes = _los(state, "cover_letter_additional_notes")  # Field CX.KM.CL.ADDITIONAL.NOTES: Cover Letter - Additional Notes (pre-populated)    ami_percentage = _los(state, "ami_percentage")  # Field CX.AMI.PERCENTAGE: AMI Percentage    loan_type = _los(state, "loan_type")  # Field 1172: Mortgage Type    # ── Rule: Draft from Almas Notes ──
    # Read state["almas_notes"]. Use as primary source for the submission notes. Augment with loan-derived facts: AMI grant eligibility, missing docs (if any known from Steps 1-6 flags), loan type, and borrower profile highlights.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Clear Pre-populated Fields ──
    # Clear Title Company, Appraisal, and Additional Notes sub-fields of CX.KM.SUBMISSION.NOTES as per Almas' standard process (notes.txt:126).
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Cover Letter Draft for Processor Review ──
    # Condition: Always raised — processor must review and approve the draft
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "7.1",
    #         "title": "Cover Letter Draft for Processor Review",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Review the cover letter draft at Step 16 Flag Review and edit as needed",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Almas Notes Missing ──
    # Condition: state["almas_notes"] is empty or None
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "7.1",
    #         "title": "Almas Notes Missing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Provide Almas' notes/email as agent input before running",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Field Updates ──
    field_updates = {}    # Field CX.KM.SUBMISSION.NOTES: {llm_drafted_notes} (condition: always)
    # TODO: Set value
    # field_updates["CX.KM.SUBMISSION.NOTES"] = <computed_value>    # Field CX.KM.CL.TITLE.COMPANY:  (condition: always)
    # TODO: Set value
    # field_updates["CX.KM.CL.TITLE.COMPANY"] = <computed_value>    # Field CX.KM.CL.APPRAISAL:  (condition: always)
    # TODO: Set value
    # field_updates["CX.KM.CL.APPRAISAL"] = <computed_value>    # Field CX.KM.CL.ADDITIONAL.NOTES:  (condition: always)
    # TODO: Set value
    # field_updates["CX.KM.CL.ADDITIONAL.NOTES"] = <computed_value>
    if field_updates:
        try:
            from shared.encompass_io import write_fields
            write_fields(loan_id, field_updates, state=state)
            logger.info(f"[DRAFT_COVER_LETTER] Wrote {len(field_updates)} field updates")
        except Exception as e:
            logger.error(f"[DRAFT_COVER_LETTER] Field write error: {e}")
            flags.append({
                "substep": "7.1",
                "title": "Field Write Error",
                "severity": "warning",
                "details": str(e),
                "suggestion": "Retry or escalate",
                "resolved": False,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "7.1",
        "tool": "draft_cover_letter",
        "flags_count": len(flags),
        "message": "Draft Cover Letter / Submission Notes completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[DRAFT_COVER_LETTER] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
