"""final_efolder_cleanup — Tool for substep 17.4: Final eFolder Cleanup

Step 17 (STEP_17): Submission
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def final_efolder_cleanup(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Move all Unassigned eFolder documents to the Recycle bucket. Clean up any residual junk files after submission.


    Call this tool during STEP_17 (Submission) as substep 17.4.    Reads Docs: Unassigned (all copies)    Flags: Unassigned Documents Remain (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[FINAL_EFOLDER_CLEANUP] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read Doc Fields ──    # From: Unassigned (ALL COPIES)    unassigned_doc_ids_doc = _doc(state, "unassigned_doc_ids")    # ── Rule: Move Unassigned to Recycle ──
    # Find all documents in the Unassigned bucket and move them to Recycle.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Unassigned Documents Remain ──
    # Condition: Unassigned documents could not be moved to Recycle
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "17.4",
    #         "title": "Unassigned Documents Remain",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Manually move Unassigned documents to Recycle in eFolder",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "17.4",
        "tool": "final_efolder_cleanup",
        "flags_count": len(flags),
        "message": "Final eFolder Cleanup completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[FINAL_EFOLDER_CLEANUP] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
