"""mark_docs_ready_for_uw — Tool for substep 17.1: Mark Docs Ready-for-UW

Step 17 (STEP_17): Submission
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def mark_docs_ready_for_uw(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """In eFolder, select and mark the following documents as Ready-for-UW per notes.txt:215. These are handed to UW with the next milestone change. Documents: 1003, 1008, Assets, Bank Statements, Condo Project, Credit Report, Estimated Settlement Statement, Flood Certificate, Fraud, General Letter of Explanation, ID Customer, Income Calc, Internal Submission, LDP, Loan Estimate, Lock Confirmation, Paystubs, Purchase Agreement, Tax Summary, UW (x2), VOE.


    Call this tool during STEP_17 (Submission) as substep 17.1.    Reads Docs: 1003 URLA, Transmittal Summary, Assets (all copies), Bank Statement (all copies), Underwriting (DU / LP) (all copies), Income Calc    Flags: Doc Not Found for Ready-for-UW (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[MARK_DOCS_READY_FOR_UW] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read Doc Fields ──    # From: 1003 URLA    urla_doc_id_doc = _doc(state, "urla_doc_id")    # From: Transmittal Summary    transmittal_doc_id_doc = _doc(state, "transmittal_doc_id")    # From: Assets (ALL COPIES)    assets_doc_ids_doc = _doc(state, "assets_doc_ids")    # From: Bank Statement (ALL COPIES)    bank_statement_doc_ids_doc = _doc(state, "bank_statement_doc_ids")    # From: Underwriting (DU / LP) (ALL COPIES)    uw_doc_ids_doc = _doc(state, "uw_doc_ids")    # From: Income Calc    income_calc_doc_id_doc = _doc(state, "income_calc_doc_id")    # ── Rule: All Specified Docs Marked Ready-for-UW ──
    # Select each document in the ready-for-UW list and change its status to Ready-for-UW in Encompass eFolder.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Doc Not Found for Ready-for-UW ──
    # Condition: A required Ready-for-UW document is missing from eFolder
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "17.1",
    #         "title": "Doc Not Found for Ready-for-UW",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Verify document is in eFolder before marking Ready-for-UW",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "17.1",
        "tool": "mark_docs_ready_for_uw",
        "flags_count": len(flags),
        "message": "Mark Docs Ready-for-UW completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[MARK_DOCS_READY_FOR_UW] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
