"""order_appraisal — Tool for substep 10.1: Order Appraisal

Step 10 (STEP_10): Orders
Phase: ORDERS

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def order_appraisal(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Order the appraisal via Encompass unless AUS collateral relief or appraisal waiver is active. If VA loan, appraisal cannot be waived. Reference existing AUS findings (read at Step 1) for waiver status.


    Call this tool during STEP_10 (Orders) as substep 10.1.    Reads LOS: loan_type, appraisal_waiver, aus_collateral_relief    Flags: Appraisal Not Ordered (warning), VA Appraisal Cannot Be Waived (critical)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[ORDER_APPRAISAL] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_type = _los(state, "loan_type")  # Field 1172: Mortgage Type    appraisal_waiver = _los(state, "appraisal_waiver")  # Field CX.APPRAISAL.WAIVER: Appraisal Waiver Flag    aus_collateral_relief = _los(state, "aus_collateral_relief")  # Field CX.AUS.COLLATERAL.RELIEF: AUS Collateral Relief    # ── Rule: Skip If Waived ──
    # If appraisal_waiver == True OR aus_collateral_relief == True AND loan_type != VA: skip appraisal order. Otherwise, order via Encompass.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Appraisal Not Ordered ──
    # Condition: Appraisal required but not yet ordered
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "10.1",
    #         "title": "Appraisal Not Ordered",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Order appraisal via Encompass appraisal ordering workflow",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: VA Appraisal Cannot Be Waived ──
    # Condition: VA loan with appraisal waiver flag active
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "10.1",
    #         "title": "VA Appraisal Cannot Be Waived",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Remove waiver flag — VA loans require a full appraisal",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Rule Modifiers (loan profile conditions) ──
    _lp = state.get("loan_profile", {})
    if _lp.get("loan_type") == "VA":  # VA loans always require a full appraisal — waiver is not allowed.
        # ADD: VA loans always require a full appraisal — waiver is not allowed. [notes.txt]
        # Flag: VA Loan - Appraisal Required (No Waiver) (critical)
        # Condition: Appraisal waiver active on a VA loan
        # TODO: Add modifier flag condition
        # if <condition>:
        #     flags.append({
        #         "substep": "10.1",
        #         "title": "VA Loan - Appraisal Required (No Waiver)",
        #         "severity": "critical",
        #         "details": "",
        #         "suggestion": "Remove appraisal waiver and order full VA appraisal",
        #         "resolved": False,
        #         "timestamp": datetime.now(timezone.utc).isoformat(),
        #         "modifier_source": "notes.txt",
        #     })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "10.1",
        "tool": "order_appraisal",
        "flags_count": len(flags),
        "message": "Order Appraisal completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[ORDER_APPRAISAL] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
