"""order_condo_questionnaire — Tool for substep 10.2: Order Condo Questionnaire

Step 10 (STEP_10): Orders
Phase: ORDERS

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def order_condo_questionnaire(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Order the condo questionnaire only if the property type is Condo. Uses the project type from Step 9 (Transmittal Summary). Skip for non-condo properties.


    Call this tool during STEP_10 (Orders) as substep 10.2.    Reads LOS: property_type, condo_project_type    Flags: Condo Questionnaire Not Ordered (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[ORDER_CONDO_QUESTIONNAIRE] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    property_type = _los(state, "property_type")  # Field 1041: Property Type    condo_project_type = _los(state, "condo_project_type")  # Field CX.CONDO.PROJECT.TYPE: Condo Project Type    # ── Rule: Skip If Non-Condo ──
    # If property_type != Condo, mark this substep as dynamically skipped. Otherwise, order the Condo Questionnaire via the ordering service.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Condo Questionnaire Not Ordered ──
    # Condition: Condo property but questionnaire not ordered
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "10.2",
    #         "title": "Condo Questionnaire Not Ordered",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Order condo questionnaire for this property",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "10.2",
        "tool": "order_condo_questionnaire",
        "flags_count": len(flags),
        "message": "Order Condo Questionnaire completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[ORDER_CONDO_QUESTIONNAIRE] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
