"""prep_efolder — Tool for substep 11.1: Prep eFolder - Delete Junk Buckets

Step 11 (STEP_11): Prep eFolder
Phase: PREP

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def prep_efolder(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Delete the following eFolder buckets to clear stale data before new runs: UW (prior AUS findings), MI Quote, Ocrolus Processing, Paystubs (old), W2 (old). This ensures fresh Ocrolus and AUS uploads land in clean buckets.


    Call this tool during STEP_11 (Prep eFolder) as substep 11.1.    Reads Docs: Underwriting (DU / LP) (all copies), MI Quote (all copies), Ocrolus Processing (all copies), Paystubs (all copies), W2 (all copies)    Flags: eFolder Cleanup Incomplete (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[PREP_EFOLDER] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read Doc Fields ──    # From: Underwriting (DU / LP) (ALL COPIES)    aus_doc_ids_doc = _doc(state, "aus_doc_ids")    # From: MI Quote (ALL COPIES)    mi_quote_doc_ids_doc = _doc(state, "mi_quote_doc_ids")    # From: Ocrolus Processing (ALL COPIES)    ocrolus_doc_ids_doc = _doc(state, "ocrolus_doc_ids")    # From: Paystubs (ALL COPIES)    paystub_doc_ids_doc = _doc(state, "paystub_doc_ids")    # From: W2 (ALL COPIES)    w2_doc_ids_doc = _doc(state, "w2_doc_ids")    # ── Rule: Delete Specified Buckets ──
    # Delete all docs in: UW, MI Quote, Ocrolus Processing, Paystubs, W2 buckets. These will be repopulated by Steps 12 (Ocrolus) and 14 (fresh AUS).
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: eFolder Cleanup Incomplete ──
    # Condition: One or more junk buckets could not be deleted
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "11.1",
    #         "title": "eFolder Cleanup Incomplete",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Manually delete the bucket contents before running Step 12 or 14",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "11.1",
        "tool": "prep_efolder",
        "flags_count": len(flags),
        "message": "Prep eFolder - Delete Junk Buckets completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[PREP_EFOLDER] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
