"""print_forms — Tool for substep 13.1: Print Forms to eFolder

Step 13 (STEP_13): Print 1003 and Transmittal
Phase: PREP

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def print_forms(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Print the following to eFolder: - 1008 Transmittal Summary → Transmittal Summary bucket - 2020 URLA → 1003 URLA bucket Do NOT upload Cover Letter here — it is auto-placed at Step 17 via Required Fields → Finished (notes.txt:219-220).


    Call this tool during STEP_13 (Print 1003 and Transmittal) as substep 13.1.    Reads LOS: loan_number    Flags: Transmittal Summary Not Printed (warning), 2020 URLA Not Printed (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[PRINT_FORMS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_number = _los(state, "loan_number")  # Field 364: Loan Number    # ── Rule: Print Transmittal Summary ──
    # Generate PDF of 1008 Transmittal Summary and upload to Transmittal Summary eFolder bucket.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Print 2020 URLA ──
    # Generate PDF of 2020 URLA and upload to 1003 URLA eFolder bucket.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Transmittal Summary Not Printed ──
    # Condition: 1008 Transmittal Summary PDF not found in eFolder bucket
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "13.1",
    #         "title": "Transmittal Summary Not Printed",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Print and upload the Transmittal Summary",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: 2020 URLA Not Printed ──
    # Condition: 2020 URLA PDF not found in eFolder bucket
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "13.1",
    #         "title": "2020 URLA Not Printed",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Print and upload the 2020 URLA",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "13.1",
        "tool": "print_forms",
        "flags_count": len(flags),
        "message": "Print Forms to eFolder completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[PRINT_FORMS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
