"""request_locked_le — Tool for substep 18.2: Request Locked LE (if locked + no Locked LE)

Step 18 (STEP_18): Notifications
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def request_locked_le(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Send email requesting a Locked Loan Estimate if the loan is locked but no Locked LE is present in eFolder. Uses recipients.json contacts.


    Call this tool during STEP_18 (Notifications) as substep 18.2.    Reads LOS: loan_locked, locked_le_present    Reads Docs: Lock Confirmation    Flags: Locked LE Request Not Sent (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REQUEST_LOCKED_LE] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_locked = _los(state, "loan_locked")  # Field CX.LOAN.LOCKED: Loan Locked Status    locked_le_present = _los(state, "locked_le_present")  # Field CX.LOCKED.LE.PRESENT: Locked LE Present    # ── Read Doc Fields ──    # From: Lock Confirmation    lock_confirmation_present_doc = _doc(state, "lock_confirmation_present")    # ── Rule: Send Only If Locked and No Locked LE ──
    # If loan_locked == True AND locked_le_present == False: send Locked LE request email. Otherwise, dynamically skip.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Locked LE Request Not Sent ──
    # Condition: Locked loan without Locked LE and email not sent
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "18.2",
    #         "title": "Locked LE Request Not Sent",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Manually request Locked LE from LO/LP",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "18.2",
        "tool": "request_locked_le",
        "flags_count": len(flags),
        "message": "Request Locked LE (if locked + no Locked LE) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REQUEST_LOCKED_LE] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
