"""review_urla_declarations — Tool for substep 6.2: Declarations (Section 5)

Step 6 (STEP_06): 1003 URLA Part 4
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_declarations(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Section 5 — Declarations. Flag any answers that appear incorrect based on known loan file facts. (Example: Borrower rented for 10 months but owned a property 3 years ago — second checkbox should be Yes, not No.)


    Call this tool during STEP_06 (1003 URLA Part 4) as substep 6.2.    Reads LOS: declaration_primary_residence, declaration_ownership_3yr    Flags: Declaration Appears Incorrect (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_DECLARATIONS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    declaration_primary_residence = _los(state, "declaration_primary_residence")  # Field 1490: Declaration - Primary Residence Intent    declaration_ownership_3yr = _los(state, "declaration_ownership_3yr")  # Field 1491: Declaration - Owned Property in Last 3 Years    # ── Rule: Declarations Consistent with File ──
    # Cross-check each declaration against known loan file facts (borrower notes, credit report, prior address history). Flag any that appear incorrect.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Declaration Appears Incorrect ──
    # Condition: A declaration answer is inconsistent with known borrower history
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "6.2",
    #         "title": "Declaration Appears Incorrect",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Review with processor and correct if needed",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "6.2",
        "tool": "review_urla_declarations",
        "flags_count": len(flags),
        "message": "Declarations (Section 5) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_DECLARATIONS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
