"""review_urla_other_income — Tool for substep 4.2: Other Income (1e)

Step 4 (STEP_04): 1003 URLA Page 2
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_other_income(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Section 1e — Other Sources of Income (alimony, dividend stocks, Social Security, etc.). Verify amounts are populated and documented.


    Call this tool during STEP_04 (1003 URLA Page 2) as substep 4.2.    Reads LOS: other_income_type, other_income_amount    Flags: Other Income Not Documented (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_OTHER_INCOME] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    other_income_type = _los(state, "other_income_type")  # Field 172: Other Income Type    other_income_amount = _los(state, "other_income_amount")  # Field 173: Other Income Amount (Monthly)    # ── Rule: Other Income Documented ──
    # If other income is present in Encompass, verify it is documented in the file. Alimony requires court order; dividends require brokerage statements.
    # 
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Flag: Other Income Not Documented ──
    # Condition: Other income amount is populated but supporting documents are missing
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "4.2",
    #         "title": "Other Income Not Documented",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Obtain supporting documentation for other income type",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "4.2",
        "tool": "review_urla_other_income",
        "flags_count": len(flags),
        "message": "Other Income (1e) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_OTHER_INCOME] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
