"""review_urla_employment — Tool for substep 4.1: Employment Verification (1b VOE)

Step 4 (STEP_04): 1003 URLA Page 2
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_employment(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Cross-check employment fields against VOE: employer name, original hire date, base pay (Gross Monthly Income → Base / Month). Cross-reference employer address via Google. Flag discrepancies. Check employment history — if current employment < 2 years, review prior history for gaps and explanations.


    Call this tool during STEP_04 (1003 URLA Page 2) as substep 4.1.    Reads LOS: employer_name, employer_address, employment_start_date, base_monthly_income, job_title, years_in_profession    Reads Docs: VOE    Flags: Employer Name Mismatch (VOE vs 1003) (warning), Hire Date Mismatch (VOE vs 1003) (warning), Base Pay Mismatch (VOE vs 1003) (warning), Employment Gap Requires Explanation (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_EMPLOYMENT] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    employer_name = _los(state, "employer_name")  # Field 1169: Employer Name    employer_address = _los(state, "employer_address")  # Field 1182: Employer Address    employment_start_date = _los(state, "employment_start_date")  # Field 1068: Employment Start Date (Hire Date)    base_monthly_income = _los(state, "base_monthly_income")  # Field 1072: Base Monthly Income    job_title = _los(state, "job_title")  # Field 1286: Job Title    years_in_profession = _los(state, "years_in_profession")  # Field 1073: Years in Profession    # ── Read Doc Fields ──    # From: VOE    voe_employer_name_doc = _doc(state, "voe_employer_name")    voe_hire_date_doc = _doc(state, "voe_hire_date")    voe_base_pay_doc = _doc(state, "voe_base_pay")    voe_employer_address_doc = _doc(state, "voe_employer_address")    # ── Rule: Employer Name Matches VOE ──
    # Employer name in Encompass must match the VOE employer name.
    # Type: field_comparison    # TODO: Implement this rule
    pass

    # ── Rule: Hire Date Matches VOE ──
    # Employment start date must match VOE original hire date.
    # Type: field_comparison    # TODO: Implement this rule
    pass

    # ── Rule: Base Pay Matches VOE ──
    # Gross Monthly Base / Month must match VOE compensation base pay.
    # Type: field_comparison    # TODO: Implement this rule
    pass

    # ── Rule: Employment History Gap Check ──
    # If current employment start date shows < 2 years: review prior employment entries. If FHA and gap < 6 months, require written explanation. If gap > 6 months, document 2-year history before the gap and income continuity.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Employer Name Mismatch (VOE vs 1003) ──
    # Condition: Employer name in Encompass doesn't match VOE
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "4.1",
    #         "title": "Employer Name Mismatch (VOE vs 1003)",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Correct employer name to match VOE",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Hire Date Mismatch (VOE vs 1003) ──
    # Condition: Hire date in Encompass doesn't match VOE original hire date
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "4.1",
    #         "title": "Hire Date Mismatch (VOE vs 1003)",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Correct hire date to match VOE",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Base Pay Mismatch (VOE vs 1003) ──
    # Condition: Base monthly income doesn't match VOE base pay rate
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "4.1",
    #         "title": "Base Pay Mismatch (VOE vs 1003)",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Reconcile income figure with VOE",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Employment Gap Requires Explanation ──
    # Condition: Employment gap < 6 months with FHA loan, or gap > 6 months with any loan type

    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "4.1",
    #         "title": "Employment Gap Requires Explanation",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Obtain written explanation letter from borrower for employment gap",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Rule Modifiers (loan profile conditions) ──
    _lp = state.get("loan_profile", {})
    if _lp.get("loan_type") == "FHA":  # FHA: if employment gap < 6 months, require written...
        # ADD: FHA: if employment gap < 6 months, require written explanation from borrower. If gap > 6 months, require 2-year history before the gap. [notes.txt:44-48]
        # Rule: FHA Employment Gap Rules — For FHA loans: gap < 6 months requires explanation letter; gap > 6 months requires documented 2-year history before gap.

        # TODO: Implement rule modifier logic
        pass
        # Flag: FHA Employment Gap - Explanation Required (warning)
        # Condition: FHA loan with employment gap < 6 months
        # TODO: Add modifier flag condition
        # if <condition>:
        #     flags.append({
        #         "substep": "4.1",
        #         "title": "FHA Employment Gap - Explanation Required",
        #         "severity": "warning",
        #         "details": "",
        #         "suggestion": "Obtain borrower explanation letter for employment gap",
        #         "resolved": False,
        #         "timestamp": datetime.now(timezone.utc).isoformat(),
        #         "modifier_source": "notes.txt:44-48",
        #     })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "4.1",
        "tool": "review_urla_employment",
        "flags_count": len(flags),
        "message": "Employment Verification (1b VOE) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_EMPLOYMENT] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
