"""review_borrower_summary — Tool for substep 2.1: Review Borrower Summary - Origination

Step 2 (STEP_02): Borrower Summary - Origination
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_borrower_summary(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Walk through the Borrower Summary – Origination screen. Check every field for completeness (cell phone = home phone if empty). Verify ID is not expired. Cross-check subject property address against listing (Google). Confirm credit score, loan amount, and AMI / Affordable Loan Eligibility fields.


    Call this tool during STEP_02 (Borrower Summary - Origination) as substep 2.1.    Reads LOS: borrower_first_name, borrower_last_name, borrower_cell_phone, borrower_home_phone, borrower_dob, property_address, property_city, property_state, property_zip, credit_score, loan_amount, appraised_value, loan_purpose, ami_eligibility    Reads Docs: Driver's License, Purchase Agreement    Flags: Required Field Empty (warning), Borrower ID Expired (warning), Property Address Mismatch (warning), Loan Amount Missing (critical)    Writes: field corrections for 1480    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_BORROWER_SUMMARY] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    borrower_first_name = _los(state, "borrower_first_name")  # Field 4000: Borrower First Name    borrower_last_name = _los(state, "borrower_last_name")  # Field 4002: Borrower Last Name    borrower_cell_phone = _los(state, "borrower_cell_phone")  # Field 1480: Borrower Cell Phone    borrower_home_phone = _los(state, "borrower_home_phone")  # Field 66: Borrower Home Phone    borrower_dob = _los(state, "borrower_dob")  # Field 1402: Borrower Date of Birth    property_address = _los(state, "property_address")  # Field 11: Property Street Address    property_city = _los(state, "property_city")  # Field 12: Property City    property_state = _los(state, "property_state")  # Field 14: Property State    property_zip = _los(state, "property_zip")  # Field 15: Property ZIP    credit_score = _los(state, "credit_score")  # Field 1168: Credit Score (Middle)    loan_amount = _los(state, "loan_amount")  # Field 1109: Loan Amount    appraised_value = _los(state, "appraised_value")  # Field 356: Appraised / Estimated Value    loan_purpose = _los(state, "loan_purpose")  # Field 19: Loan Purpose    ami_eligibility = _los(state, "ami_eligibility")  # Field CX.AMI.ELIGIBILITY: AMI / Affordable Loan Eligibility    # ── Read Doc Fields ──    # From: Driver's License    dl_expiry_doc = _doc(state, "dl_expiry")    dl_name_doc = _doc(state, "dl_name")    # From: Purchase Agreement    purchase_price_doc = _doc(state, "purchase_price")    purchase_property_address_doc = _doc(state, "purchase_property_address")    # ── Rule: All Required Fields Populated ──
    # Every mandatory field on the Borrower Summary screen must be populated. If cell phone is empty, copy value from home phone.
    # 
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Rule: ID Not Expired ──
    # Government ID expiration must be >= today.
    # Type: value_check    # Check: dl_expiry >= today    # TODO: Implement this rule
    pass

    # ── Rule: Property Address Consistent ──
    # Property address in Encompass should match the listing and Purchase Contract. Flag any mismatch.
    # 
    # Type: field_comparison    # TODO: Implement this rule
    pass

    # ── Rule: Loan Amount Positive ──
    # Loan amount must be greater than zero.
    # Type: value_check    # Check: loan_amount > 0    # TODO: Implement this rule
    pass

    # ── Flag: Required Field Empty ──
    # Condition: A mandatory Borrower Summary field is blank
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "2.1",
    #         "title": "Required Field Empty",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Populate the missing field before proceeding",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Borrower ID Expired ──
    # Condition: Government ID expiration date is before today
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "2.1",
    #         "title": "Borrower ID Expired",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request a valid government-issued ID from the borrower",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Property Address Mismatch ──
    # Condition: Encompass address doesn't match listing or Purchase Contract
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "2.1",
    #         "title": "Property Address Mismatch",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Correct the property address and flag for Lock Desk if needed",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Loan Amount Missing ──
    # Condition: Loan amount is zero or blank
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "2.1",
    #         "title": "Loan Amount Missing",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Enter the correct loan amount before proceeding",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Field Updates ──
    field_updates = {}    # Field 1480: {borrower_home_phone} (condition: borrower_cell_phone is empty)
    # TODO: Set value
    # field_updates["1480"] = <computed_value>
    if field_updates:
        try:
            from shared.encompass_io import write_fields
            write_fields(loan_id, field_updates, state=state)
            logger.info(f"[REVIEW_BORROWER_SUMMARY] Wrote {len(field_updates)} field updates")
        except Exception as e:
            logger.error(f"[REVIEW_BORROWER_SUMMARY] Field write error: {e}")
            flags.append({
                "substep": "2.1",
                "title": "Field Write Error",
                "severity": "warning",
                "details": str(e),
                "suggestion": "Retry or escalate",
                "resolved": False,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "2.1",
        "tool": "review_borrower_summary",
        "flags_count": len(flags),
        "message": "Review Borrower Summary - Origination completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_BORROWER_SUMMARY] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
