"""review_urla_page1 — Tool for substep 3.1: Review 1003 URLA Page 1

Step 3 (STEP_03): 1003 URLA Page 1
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_page1(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Check all fields on 1003 URLA Page 1 for completeness and consistency with the Borrower Summary - Origination screen. Confirm borrower name, address, SSN, loan purpose, property type, and occupancy. Flag any mismatches.


    Call this tool during STEP_03 (1003 URLA Page 1) as substep 3.1.    Reads LOS: borrower_first_name, borrower_middle_name, borrower_last_name, borrower_ssn, borrower_dob, borrower_current_address, property_address, loan_purpose, property_type, occupancy    Flags: URLA Page 1 Field Mismatch with Origination (warning), Borrower SSN Missing (critical)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_PAGE1] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    borrower_first_name = _los(state, "borrower_first_name")  # Field 4000: Borrower First Name    borrower_middle_name = _los(state, "borrower_middle_name")  # Field 4001: Borrower Middle Name    borrower_last_name = _los(state, "borrower_last_name")  # Field 4002: Borrower Last Name    borrower_ssn = _los(state, "borrower_ssn")  # Field 65: Borrower SSN    borrower_dob = _los(state, "borrower_dob")  # Field 1402: Borrower DOB    borrower_current_address = _los(state, "borrower_current_address")  # Field 35: Borrower Current Street Address    property_address = _los(state, "property_address")  # Field 11: Subject Property Address    loan_purpose = _los(state, "loan_purpose")  # Field 19: Loan Purpose    property_type = _los(state, "property_type")  # Field 1041: Property Type    occupancy = _los(state, "occupancy")  # Field 1811: Occupancy    # ── Rule: Borrower Info Consistent with Origination ──
    # First name, last name, property address, loan purpose, property type, and occupancy must match the Borrower Summary screen values from Step 2.
    # 
    # Type: field_comparison    # TODO: Implement this rule
    pass

    # ── Rule: SSN Populated ──
    # Borrower SSN must not be blank.
    # Type: existence_check    # Check: borrower_ssn IS NOT NULL    # TODO: Implement this rule
    pass

    # ── Flag: URLA Page 1 Field Mismatch with Origination ──
    # Condition: Field value on URLA Page 1 differs from Borrower Summary screen
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "3.1",
    #         "title": "URLA Page 1 Field Mismatch with Origination",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Reconcile the field — update the incorrect screen",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Borrower SSN Missing ──
    # Condition: Borrower SSN is blank on Page 1
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "3.1",
    #         "title": "Borrower SSN Missing",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Populate SSN before proceeding",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "3.1",
        "tool": "review_urla_page1",
        "flags_count": len(flags),
        "message": "Review 1003 URLA Page 1 completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_PAGE1] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
