"""review_urla_assets — Tool for substep 5.1: Assets and VOD (2a)

Step 5 (STEP_05): 1003 URLA Part 3
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_assets(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Section 2a (Assets/VOD). Check bank accounts, checking/savings. Cross-reference against bank statements. Verify account numbers, dates, and balances. Flag if total assets insufficient for closing. Rename asset documents per naming convention (e.g. "Edward Jones x1234 - 04/14/2026").


    Call this tool during STEP_05 (1003 URLA Part 3) as substep 5.1.    Reads LOS: total_assets, checking_balance, savings_balance    Reads Docs: Bank Statement (all copies), Assets, VOD    Flags: ZEL/Zelle Deposit Requires Explanation (warning), Large Deposit Requires Sourcing (warning), Bank Statement Stale (warning), Asset Document Needs Renaming (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_ASSETS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    total_assets = _los(state, "total_assets")  # Field 732: Total Assets    checking_balance = _los(state, "checking_balance")  # Field 733: Checking Account Balance    savings_balance = _los(state, "savings_balance")  # Field 734: Savings Account Balance    # ── Read Doc Fields ──    # From: Bank Statement (ALL COPIES)    bank_account_number_doc = _doc(state, "bank_account_number")    bank_balance_doc = _doc(state, "bank_balance")    bank_statement_date_doc = _doc(state, "bank_statement_date")    bank_zel_deposits_doc = _doc(state, "bank_zel_deposits")    bank_large_deposits_doc = _doc(state, "bank_large_deposits")    # From: Assets    asset_account_number_doc = _doc(state, "asset_account_number")    asset_balance_doc = _doc(state, "asset_balance")    asset_account_date_doc = _doc(state, "asset_account_date")    # From: VOD    vod_account_balances_doc = _doc(state, "vod_account_balances")    vod_account_numbers_doc = _doc(state, "vod_account_numbers")    # ── Rule: Bank Statement Recency ──
    # Bank statements must be within required recency window (Conv=60 days, FHA=30 days).
    # Type: value_check    # TODO: Implement this rule
    pass

    # ── Rule: ZEL/Zelle Deposits Flagged ──
    # Any ZEL or Zelle deposits should be flagged for UW explanation letter. Klarna or Firm deposits should also be flagged.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Large Deposits Flagged ──
    # Green deposits (cash deposits, large non-payroll deposits) must be explained and sourced. Flag for borrower Letter of Explanation.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: ZEL/Zelle Deposit Requires Explanation ──
    # Condition: Zelle or ZEL deposit found in bank statement
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.1",
    #         "title": "ZEL/Zelle Deposit Requires Explanation",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request borrower LOE explaining the ZEL/Zelle transactions",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Large Deposit Requires Sourcing ──
    # Condition: Large non-payroll deposit (green deposit) found in bank statement
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.1",
    #         "title": "Large Deposit Requires Sourcing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request documentation sourcing the large deposit",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Bank Statement Stale ──
    # Condition: Bank statement older than required recency window for loan type
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.1",
    #         "title": "Bank Statement Stale",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request updated bank statements from borrower",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Asset Document Needs Renaming ──
    # Condition: Asset document not named per convention (e.g. "Edward Jones x1234 - 04/14/2026")
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.1",
    #         "title": "Asset Document Needs Renaming",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Rename document in eFolder per naming convention",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Rule Modifiers (loan profile conditions) ──
    _lp = state.get("loan_profile", {})
    if _lp.get("loan_type") == "FHA":  # FHA requires only 1 month of bank statements (vs 2 for...
        # ADD: FHA requires only 1 month of bank statements (vs 2 for Conventional). [notes.txt:64]
        # Rule: FHA Bank Statement 1 Month — FHA loan — only 1 month of bank statements required.
        # TODO: Implement rule modifier logic
        pass

    # ── Build result ──
    result = {
        "success": True,
        "substep": "5.1",
        "tool": "review_urla_assets",
        "flags_count": len(flags),
        "message": "Assets and VOD (2a) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_ASSETS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
