"""review_urla_ethnicity — Tool for substep 6.3: Ethnicity and ID Cross-Check

Step 6 (STEP_06): 1003 URLA Part 4
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_ethnicity(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Validate borrower ethnicity selection against Driver's License. Verify attachment type (attached/detached) and property type match the Google listing. Confirm estate held = Fee Simple and manner of title = Sole Ownership (or appropriate for married/co-borrower).


    Call this tool during STEP_06 (1003 URLA Part 4) as substep 6.3.    Reads LOS: borrower_ethnicity, attachment_type, property_type, estate_held, manner_of_title    Reads Docs: Driver's License    Flags: Ethnicity Mismatch with ID (warning), Attachment Type Mismatch with Listing (warning), Estate Held Not Fee Simple (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_ETHNICITY] Starting for loan {str(loan_id)[:8]}...")

    flags = []

    def _flag(title, severity, details, suggestion):
        return {
            "substep": "6.3",
            "title": title,
            "severity": severity,
            "details": details,
            "suggestion": suggestion,
            "resolved": severity in ("info", "info-overwrite"),
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    # ── Read LOS Fields ───────────────────────────────────────────────────────
    borrower_ethnicity  = _los(state, "borrower_ethnicity")   # field 1544
    attachment_type     = _los(state, "attachment_type")      # CX.ATTACHMENT.TYPE
    property_type       = _los(state, "property_type")        # field 1041
    estate_held         = _los(state, "estate_held")          # field 1066

    # ── Read Doc Fields (Driver's License) ───────────────────────────────────
    dl_ethnicity_doc    = _doc(state, "dl_ethnicity_indicator")
    dl_borrower_name    = _doc(state, "dl_borrower_name")

    # ── Rule: Ethnicity cross-check vs Driver's License ───────────────────────
    # dl_ethnicity_indicator is in the live DL extraction schema but most US
    # driver's licenses do not print ethnicity — check only when extracted.
    #
    # Normalize both values to a common "hispanic" / "not_hispanic" / "unknown"
    # bucket before comparing, since Encompass and DL use different strings.
    def _ethnicity_bucket(raw: str) -> str:
        v = (raw or "").strip().lower()
        if not v or "not wish" in v or "decline" in v or "prefer not" in v:
            return "unknown"
        if "hispanic" in v and ("not" in v or "non" in v):
            return "not_hispanic"
        if "hispanic" in v or "latino" in v:
            return "hispanic"
        return "unknown"

    if dl_ethnicity_doc:
        dl_bucket   = _ethnicity_bucket(dl_ethnicity_doc)
        los_bucket  = _ethnicity_bucket(borrower_ethnicity)
        if dl_bucket != "unknown" and los_bucket != "unknown":
            if dl_bucket != los_bucket:
                flags.append(_flag(
                    "Ethnicity Mismatch — 1003 vs Driver's License",
                    "warning",
                    f"1003 (field 1544): '{borrower_ethnicity}' | "
                    f"Driver's License: '{dl_ethnicity_doc}'. "
                    "Self-identified ethnicity on the URLA differs from what the DL indicates.",
                    "Confirm with borrower — self-identification takes precedence; "
                    "update field 1544 if the borrower wishes to correct it.",
                ))
            else:
                flags.append(_flag(
                    "Ethnicity Consistent — 1003 vs Driver's License",
                    "info",
                    f"1003: '{borrower_ethnicity}' consistent with DL: '{dl_ethnicity_doc}'.",
                    "No action needed.",
                ))
        elif dl_bucket != "unknown" and los_bucket == "unknown":
            flags.append(_flag(
                "Borrower Ethnicity Not Selected on 1003",
                "info",
                f"Driver's License indicates '{dl_ethnicity_doc}' but field 1544 is blank "
                "or set to 'I do not wish to provide'.",
                "Confirm with borrower whether they wish to self-identify ethnicity on the URLA.",
            ))
    # If dl_ethnicity_doc is null/empty: most DLs don't print ethnicity — no flag needed.

    # ── Rule: Attachment Type Consistent with Listing ─────────────────────────
    # Cross-reference Attached/Detached in Encompass against Google property listing.
    # Cannot be automated without a live Google search — flagged for manual review
    # when attachment_type is blank.
    if not (attachment_type or "").strip():
        flags.append(_flag(
            "Attachment Type Not Set",
            "info",
            "CX.ATTACHMENT.TYPE (attachment type) is blank. "
            "Should be 'Attached' or 'Detached' based on the property listing.",
            "Check the Google property listing and set the attachment type in Encompass.",
        ))

    # ── Rule: Estate Held = Fee Simple ────────────────────────────────────────
    # (field 1066 — 1003 URLA Lender dropdown: FeeSimple / Leasehold)
    _estate = (estate_held or "").strip().lower().replace(" ", "")
    if not _estate:
        flags.append(_flag(
            "Estate Held Not Set",
            "info",
            "Field 1066 (Estate Will Be Held In) is blank.",
            "Confirm 'Fee Simple' in the 1003 URLA Lender section.",
        ))
    elif _estate not in ("feesimple",):
        flags.append(_flag(
            "Estate Not Held in Fee Simple",
            "warning",
            f"Estate will be held in '{estate_held}'. Standard residential loans expect Fee Simple.",
            "Verify with processor — Leasehold and other tenures require additional review.",
        ))


    # ── Build result ──
    result = {
        "success": True,
        "substep": "6.3",
        "tool": "review_urla_ethnicity",
        "flags_count": len(flags),
        "message": "Ethnicity and ID Cross-Check completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_ETHNICITY] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
