"""review_urla_ethnicity — Tool for substep 6.3: Ethnicity and ID Cross-Check

Step 6 (STEP_06): 1003 URLA Part 4
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_ethnicity(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Validate borrower ethnicity selection against Driver's License. Verify attachment type (attached/detached) and property type match the Google listing. Confirm estate held = Fee Simple and manner of title = Sole Ownership (or appropriate for married/co-borrower).


    Call this tool during STEP_06 (1003 URLA Part 4) as substep 6.3.    Reads LOS: borrower_ethnicity, attachment_type, property_type, estate_held, manner_of_title    Reads Docs: Driver's License    Flags: Ethnicity Mismatch with ID (warning), Attachment Type Mismatch with Listing (warning), Estate Held Not Fee Simple (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_ETHNICITY] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    borrower_ethnicity = _los(state, "borrower_ethnicity")  # Field 1544: Borrower Ethnicity    attachment_type = _los(state, "attachment_type")  # Field CX.ATTACHMENT.TYPE: Attachment Type (Attached/Detached)    property_type = _los(state, "property_type")  # Field 1041: Property Type    estate_held = _los(state, "estate_held")  # Field 33: Estate Will Be Held In    manner_of_title = _los(state, "manner_of_title")  # Field 34: Manner in Which Title Will Be Held    # ── Read Doc Fields ──    # From: Driver's License    dl_ethnicity_indicator_doc = _doc(state, "dl_ethnicity_indicator")    dl_borrower_name_doc = _doc(state, "dl_borrower_name")    # ── Rule: Attachment Type Consistent with Listing ──
    # Cross-reference attachment type (Attached vs Detached) against listing on Google. Flag mismatch.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Manner of Title Appropriate ──
    # If no co-borrower and not married: Sole Ownership. If co-borrower: Joint Tenants / Tenants in Common as appropriate.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Ethnicity Mismatch with ID ──
    # Condition: Ethnicity on 1003 doesn't match ID documentation
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "6.3",
    #         "title": "Ethnicity Mismatch with ID",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Verify borrower's self-identified ethnicity and update if needed",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Attachment Type Mismatch with Listing ──
    # Condition: Attachment type in Encompass doesn't match property listing
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "6.3",
    #         "title": "Attachment Type Mismatch with Listing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Correct attachment type based on property listing",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Estate Held Not Fee Simple ──
    # Condition: Estate held is not Fee Simple for standard purchase
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "6.3",
    #         "title": "Estate Held Not Fee Simple",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Verify estate type is correct for this loan",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "6.3",
        "tool": "review_urla_ethnicity",
        "flags_count": len(flags),
        "message": "Ethnicity and ID Cross-Check completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_ETHNICITY] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
