"""review_urla_emd — Tool for substep 5.2: EMD Check (2b)

Step 5 (STEP_05): 1003 URLA Part 3
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_emd(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Section 2b — Earnest Money Deposit. Verify EMD amount matches Purchase Contract. Flag if EMD check copy is missing (trigger email to Realtor via Step 18).


    Call this tool during STEP_05 (1003 URLA Part 3) as substep 5.2.    Reads LOS: emd_amount    Reads Docs: Purchase Agreement    Flags: EMD Amount Mismatch (warning), EMD Check Copy Missing (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_EMD] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    emd_amount = _los(state, "emd_amount")  # Field 186: EMD Amount    # ── Read Doc Fields ──    # From: Purchase Agreement    emd_amount_pa_doc = _doc(state, "emd_amount_pa")    payment_terms_doc = _doc(state, "payment_terms")    emd_payable_to_doc = _doc(state, "emd_payable_to")    # ── Rule: EMD Amount Matches Purchase Contract ──
    # EMD amount in Section 2b must match Purchase Contract EMD row. Flag mismatch and missing check copy for Realtor email at Step 18.
    # 
    # Type: field_comparison    # TODO: Implement this rule
    pass

    # ── Flag: EMD Amount Mismatch ──
    # Condition: EMD in Encompass doesn't match Purchase Contract
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.2",
    #         "title": "EMD Amount Mismatch",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Correct EMD amount to match Purchase Contract",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: EMD Check Copy Missing ──
    # Condition: Copy of EMD check not in eFolder
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.2",
    #         "title": "EMD Check Copy Missing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Email Realtor to request copy of EMD check (auto-sends at Step 18)",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "5.2",
        "tool": "review_urla_emd",
        "flags_count": len(flags),
        "message": "EMD Check (2b) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_EMD] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
