"""review_urla_reo — Tool for substep 5.4: Other Assets and REO (2d, Section 3)

Step 5 (STEP_05): 1003 URLA Part 3
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_reo(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review 2d (Other Assets — usually marked No) and Section 3 (REO). If borrower owns other real property, verify mortgage statement, insurance deck page, HOA statement, and tax bill are present.


    Call this tool during STEP_05 (1003 URLA Part 3) as substep 5.4.    Reads LOS: owned_properties_count    Reads Docs: Mortgage Statement    Flags: REO Documents Missing (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_REO] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    owned_properties_count = _los(state, "owned_properties_count")  # Field 558: Number of Owned Properties (REO)    # ── Read Doc Fields ──    # From: Mortgage Statement    mortgage_statement_present_doc = _doc(state, "mortgage_statement_present")    # ── Rule: REO Documentation ──
    # If borrower owns other property (REO count > 0), verify: mortgage statement, insurance deck page, HOA statement, tax bill. If count = 0, skip.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: REO Documents Missing ──
    # Condition: Borrower has REO properties but supporting docs are absent
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.4",
    #         "title": "REO Documents Missing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Obtain mortgage statement, insurance, HOA, and tax bill for each REO",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "5.4",
        "tool": "review_urla_reo",
        "flags_count": len(flags),
        "message": "Other Assets and REO (2d, Section 3) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_REO] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
