"""review_urla_liabilities — Tool for substep 5.3: Liabilities and VOL (2c)

Step 5 (STEP_05): 1003 URLA Part 3
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_liabilities(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Section 2c — Liabilities (VOL). Check Excluded Monthly Payment and To Be Paid Off columns. Flag excluded debts for explanation. Flag any debts to be paid off that require most recent statement.


    Call this tool during STEP_05 (1003 URLA Part 3) as substep 5.3.    Reads LOS: total_monthly_payments    Reads Docs: VOL    Flags: Excluded Debt Needs Explanation (warning), Payoff Statement Required (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_LIABILITIES] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    total_monthly_payments = _los(state, "total_monthly_payments")  # Field 350: Total Monthly Liabilities    # ── Read Doc Fields ──    # From: VOL    excluded_debts_doc = _doc(state, "excluded_debts")    debts_to_be_paid_off_doc = _doc(state, "debts_to_be_paid_off")    # ── Rule: Excluded Debt Explained ──
    # Column 1 (Excluded Monthly Payment = Y): verify why excluded. Was it already paid off?
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Paid-Off Debt Statement Required ──
    # Column 2 (To Be Paid Off = Y): request most recent credit card/loan statement (e.g. JPMCB card). Usually for cash-out refis.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Excluded Debt Needs Explanation ──
    # Condition: Debt excluded from monthly payment without documented reason
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.3",
    #         "title": "Excluded Debt Needs Explanation",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Document why debt is excluded (paid off, not obligated, etc.)",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Payoff Statement Required ──
    # Condition: Debt marked To Be Paid Off but payoff statement missing
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "5.3",
    #         "title": "Payoff Statement Required",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request most recent statement for debt to be paid off",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "5.3",
        "tool": "review_urla_liabilities",
        "flags_count": len(flags),
        "message": "Liabilities and VOL (2c) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_LIABILITIES] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
