"""review_urla_downpayment — Tool for substep 6.1: Downpayment Sources (4b, 4c, 4d)

Step 6 (STEP_06): 1003 URLA Part 4
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_urla_downpayment(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Sections 4b (downpayment assistance / HELOC — usually N/A for purchase), 4c (rental income — check if applicable), and 4d (grant programs). Check Fannie Mae Additional Data and AMI eligibility for grant programs (e.g. Freddie Mac $2500 grant for borrowers <= 50% AMI).


    Call this tool during STEP_06 (1003 URLA Part 4) as substep 6.1.    Reads LOS: gift_amount, ami_percentage, fnma_additional_data, rental_income    Flags: Gift Letter Missing (warning), AMI Eligibility Not Set (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_DOWNPAYMENT] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    gift_amount = _los(state, "gift_amount")  # Field 231: Gift Amount    ami_percentage = _los(state, "ami_percentage")  # Field CX.AMI.PERCENTAGE: AMI Percentage    fnma_additional_data = _los(state, "fnma_additional_data")  # Field CX.FNMA.ADDITIONAL.DATA: Fannie Mae Additional Data - AMI    rental_income = _los(state, "rental_income")  # Field 218: Rental Income    # ── Rule: Grant Program Eligibility ──
    # If AMI <= 50%, borrower qualifies for $2500 Freddie Mac grant automatically. Verify Affordable Loan Eligibility = AM 100% flag.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Gift Letter Required ──
    # If gift amount is populated, verify gift letter and donor details are in file. Send gift letter to borrower if missing.
    # 
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Flag: Gift Letter Missing ──
    # Condition: Gift amount is populated but gift letter is absent
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "6.1",
    #         "title": "Gift Letter Missing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Send gift letter to borrower for signature and return",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: AMI Eligibility Not Set ──
    # Condition: AMI percentage is <= 50% but Affordable Loan Eligibility not confirmed
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "6.1",
    #         "title": "AMI Eligibility Not Set",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Confirm AMI = AM 100% in Fannie Mae Additional Data screen",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "6.1",
        "tool": "review_urla_downpayment",
        "flags_count": len(flags),
        "message": "Downpayment Sources (4b, 4c, 4d) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_URLA_DOWNPAYMENT] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
