"""review_urla_downpayment — Tool for substep 6.1: Downpayment Sources (4b, 4c, 4d)

Step 6 (STEP_06): 1003 URLA Part 4
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _efolder_present, _relevant_docs

logger = logging.getLogger(__name__)

# Asset types that require a gift letter in the eFolder
_GIFT_TYPES = {"GiftOfCash", "GiftOfEquity", "GiftFunds"}
# Asset types that represent grants (no letter required, but verify deposited)
_GRANT_TYPES = {"Grant", "CommunitySecondsAndDownPaymentAssistancePrograms"}


@tool
def review_urla_downpayment(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Review Sections 4b (downpayment assistance / HELOC — usually N/A for purchase), 4c (rental income — check if applicable), and 4d (grant programs). Check Fannie Mae Additional Data and AMI eligibility for grant programs (e.g. Freddie Mac $2500 grant for borrowers <= 50% AMI).


    Call this tool during STEP_06 (1003 URLA Part 4) as substep 6.1.    Reads LOS: gift_amount, ami_percentage, fnma_additional_data, rental_income    Flags: Gift Letter Missing (warning), AMI Eligibility Not Set (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_URLA_DOWNPAYMENT] Starting for loan {str(loan_id)[:8]}...")

    flags = []

    # ── Read LOS Fields ──
    ami_percentage      = _los(state, "ami_percentage")       # CX.AMI.PERCENTAGE
    ami_eligibility     = _los(state, "ami_eligibility")      # CX.AMI.ELIGIBILITY
    # fnma_additional_data (CX.FNMA.ADDITIONAL.DATA) reserved for future AMI program logic
    rental_income       = _los(state, "rental_income")        # Field 218

    # ── Fetch Gifts / Grants via API ──
    try:
        from shared.encompass_io import read_gifts_grants
        gifts_grants = read_gifts_grants(loan_id, state=state)
    except Exception as e:
        logger.warning(f"[REVIEW_URLA_DOWNPAYMENT] Could not fetch giftsGrants: {e}")
        gifts_grants = []

    gifts  = [r for r in gifts_grants if r.get("asset_type") in _GIFT_TYPES]
    grants = [r for r in gifts_grants if r.get("asset_type") in _GRANT_TYPES]

    now = datetime.now(timezone.utc).isoformat()

    # ── Rule: Gift Letter Required ──
    # For each GiftOfCash / GiftOfEquity present, verify Gift Letter is in eFolder.
    for gift in gifts:
        amt    = gift.get("amount", 0)
        owner  = gift.get("owner", "Borrower")
        a_type = gift.get("asset_type", "Gift")
        gift_letter_present = _efolder_present(state, "Gift Letter")

        if not gift_letter_present:
            flags.append({
                "substep": "6.1",
                "title": "Gift Letter Missing",
                "severity": "warning",
                "details": (
                    f"{a_type} of ${amt:,.2f} ({owner}) is recorded but no Gift Letter "
                    f"was found in the eFolder."
                ),
                "suggestion": "Send gift letter to borrower for signature and return; upload signed copy to eFolder.",
                "resolved": False,
                "timestamp": now,
            })
        else:
            _gift_flag = {
                "substep": "6.1",
                "title": "Gift Letter Present",
                "severity": "info",
                "details": f"{a_type} of ${amt:,.2f} ({owner}) — Gift Letter found in eFolder.",
                "suggestion": "Confirm donor details and amount match the gift letter.",
                "resolved": True,
                "timestamp": now,
            }
            _gift_refs = _relevant_docs(state, doc_types=["Gift Letter"])
            if _gift_refs:
                _gift_flag["relevant_documents"] = _gift_refs
            flags.append(_gift_flag)

    # ── Rule: Grant — Confirm Deposited ──
    for grant in grants:
        amt       = grant.get("amount", 0)
        source    = grant.get("source", "")
        deposited = grant.get("deposited", False)
        owner     = grant.get("owner", "Borrower")

        source_label = source.replace("Agency", " Agency") if source else "Unknown Source"

        if not deposited:
            flags.append({
                "substep": "6.1",
                "title": "Grant Not Yet Deposited",
                "severity": "info",
                "details": (
                    f"Grant of ${amt:,.2f} from {source_label} ({owner}) is present "
                    f"but has not been deposited yet."
                ),
                "suggestion": "Confirm grant will be deposited before closing; verify with processor.",
                "resolved": False,
                "timestamp": now,
            })
        else:
            flags.append({
                "substep": "6.1",
                "title": "Grant Deposited",
                "severity": "info",
                "details": f"Grant of ${amt:,.2f} from {source_label} ({owner}) — deposited.",
                "suggestion": "No action needed.",
                "resolved": True,
                "timestamp": now,
            })

    # ── Rule: AMI Eligibility Check ──
    # If AMI percentage <= 50%, borrower qualifies for $2,500 Freddie Mac grant automatically.
    # Verify CX.AMI.ELIGIBILITY = "AM 100%" in Fannie Mae Additional Data.
    try:
        ami_pct_val = float(str(ami_percentage or "").replace("%", "").strip()) if ami_percentage else None
    except (ValueError, TypeError):
        ami_pct_val = None

    if ami_pct_val is not None and ami_pct_val <= 50:
        if not ami_eligibility or str(ami_eligibility).strip().upper() not in ("AM 100%", "AM100%"):
            flags.append({
                "substep": "6.1",
                "title": "AMI Eligibility Not Confirmed",
                "severity": "info",
                "details": (
                    f"Borrower AMI is {ami_pct_val}% (≤ 50%) — qualifies for automatic $2,500 "
                    f"Freddie Mac grant. Affordable Loan Eligibility field (CX.AMI.ELIGIBILITY) "
                    f"is currently '{ami_eligibility or 'blank'}'."
                ),
                "suggestion": "Confirm AMI = AM 100% in Fannie Mae Additional Data screen.",
                "resolved": False,
                "timestamp": now,
            })
        else:
            flags.append({
                "substep": "6.1",
                "title": "AMI Eligibility Confirmed",
                "severity": "info",
                "details": (
                    f"Borrower AMI is {ami_pct_val}% — Affordable Loan Eligibility = '{ami_eligibility}'. "
                    f"Qualifies for $2,500 Freddie Mac grant."
                ),
                "suggestion": "No action needed.",
                "resolved": True,
                "timestamp": now,
            })

    # ── Rule: Rental Income (4c) ──
    if rental_income and str(rental_income).strip() not in ("", "0", "0.0"):
        flags.append({
            "substep": "6.1",
            "title": "Rental Income Present (4c)",
            "severity": "info",
            "details": f"Rental income of ${rental_income} recorded in Section 4c.",
            "suggestion": "Verify rental income is supported by lease agreement or tax returns in eFolder.",
            "resolved": False,
            "timestamp": now,
        })

    # ── Build result ──
    grants_count = len(grants)
    gifts_count  = len(gifts)
    result = {
        "success": True,
        "substep": "6.1",
        "tool": "review_urla_downpayment",
        "flags_count": len(flags),
        "gifts_found": gifts_count,
        "grants_found": grants_count,
        "message": (
            f"Downpayment Sources (4b, 4c, 4d) completed — "
            f"{gifts_count} gift(s), {grants_count} grant(s) found"
            + (f", {len(flags)} flag(s)" if flags else "")
        ),
    }

    logger.info(f"[REVIEW_URLA_DOWNPAYMENT] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
