"""review_flags — Tool for substep 16.1: Review All Flags (HITL)

Step 16 (STEP_16): Flag Review (HITL)
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def review_flags(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Gather all accumulated flags from Steps 1-15 from state["flags"]. Also pull the Required Fields screen from Encompass — surface any fields that Encompass marks as required. Call interrupt() with the full flag list + required fields list. Wait for processor to review and respond. On resume: record which flags were resolved and carry forward any processor edits to state.


    Call this tool during STEP_16 (Flag Review (HITL)) as substep 16.1.    Reads LOS: required_fields_status    Flags: Critical Flag Not Resolved (critical)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_FLAGS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    required_fields_status = _los(state, "required_fields_status")  # Field CX.REQUIRED.FIELDS.STATUS: Encompass Required Fields Status    # ── Rule: All Critical Flags Must Be Resolved ──
    # Processor must acknowledge or resolve all critical flags before Step 17 can proceed. Warning flags may be acknowledged without resolution.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Critical Flag Not Resolved ──
    # Condition: Processor confirmed HITL without resolving a critical flag
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "16.1",
    #         "title": "Critical Flag Not Resolved",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Resolve all critical flags before proceeding to submission",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "16.1",
        "tool": "review_flags",
        "flags_count": len(flags),
        "message": "Review All Flags (HITL) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_FLAGS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
