"""review_borrower_summary — Tool for substep 2.1: Review Borrower Summary - Origination

Step 2 (STEP_02): Borrower Summary - Origination
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile, _write_fields

logger = logging.getLogger(__name__)


def _flag(flags, substep, title, severity, details, suggestion):
    flags.append({
        "substep": substep,
        "title": title,
        "severity": severity,
        "details": details,
        "suggestion": suggestion,
        "resolved": False,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })


def _is_checked(val) -> bool:
    """Return True if an Encompass checkbox field is checked (Y / true / True / 1)."""
    if val is None:
        return False
    return str(val).strip().lower() in ("y", "yes", "true", "1")


@tool
def review_borrower_summary(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Walk through the Borrower Summary – Origination screen. Check every field for completeness (cell phone = home phone if empty). Auto-check accept text/SMS if unchecked. Verify credit score, loan amount, email, marital status populated. Cross-check property address against Purchase Contract.

    Call this tool during STEP_02 (Borrower Summary - Origination) as substep 2.1.
    Reads LOS: borrower_first_name, borrower_last_name, borrower_cell_phone, borrower_home_phone,
    borrower_accept_sms, borrower_dob, borrower_email, borrower_marital_status,
    coborrower_first_name, coborrower_last_name, coborrower_cell_phone, coborrower_accept_sms,
    coborrower_email, coborrower_marital_status, property_address, property_city, property_state,
    property_zip, credit_score, loan_amount, appraised_value, loan_purpose, ami_eligibility
    Reads Docs: Driver's License, Purchase Agreement
    Flags: Required Field Empty, Borrower ID Expired, Property Address Mismatch, Loan Amount Missing,
    Credit Score Missing, Email Missing
    Writes: 1490 (borr cell ← home phone), 4920 (borr SMS), 4935 (coborr SMS)
    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_BORROWER_SUMMARY] Starting for loan {str(loan_id)[:8]}...")

    flags = []

    # ── Read LOS Fields (pre-fetched by fetch_los_fields via state) ──────
    borrower_first_name      = _los(state, "borrower_first_name")
    borrower_last_name       = _los(state, "borrower_last_name")
    borrower_ssn             = _los(state, "borrower_ssn")
    borrower_dob             = _los(state, "borrower_dob")
    borrower_home_phone      = _los(state, "borrower_home_phone")
    borrower_cell_phone      = _los(state, "borrower_cell_phone")   # field 1490
    borrower_email           = _los(state, "borrower_email")
    borrower_marital_status  = _los(state, "borrower_marital_status")
    borrower_accept_sms      = _los(state, "borrower_accept_sms")   # field 4920

    coborrower_first_name    = _los(state, "coborrower_first_name")
    coborrower_last_name     = _los(state, "coborrower_last_name")
    coborrower_cell_phone    = _los(state, "coborrower_cell_phone")  # field 1480
    coborrower_home_phone    = _los(state, "coborrower_home_phone")
    coborrower_email         = _los(state, "coborrower_email")
    coborrower_marital_status = _los(state, "coborrower_marital_status")
    coborrower_accept_sms    = _los(state, "coborrower_accept_sms")  # field 4935

    credit_score             = _los(state, "credit_score")
    experian_score           = _los(state, "experian_score")
    transunion_score         = _los(state, "transunion_score")
    equifax_score            = _los(state, "equifax_score")
    coborrower_experian_score  = _los(state, "coborrower_experian_score")
    coborrower_transunion_score = _los(state, "coborrower_transunion_score")
    coborrower_equifax_score   = _los(state, "coborrower_equifax_score")
    credit_score_decision    = _los(state, "credit_score_decision")
    credit_reference_number  = _los(state, "credit_reference_number")
    loan_amount              = _los(state, "loan_amount")
    appraised_value          = _los(state, "appraised_value")
    loan_purpose             = _los(state, "loan_purpose")
    property_address         = _los(state, "property_address")
    property_city            = _los(state, "property_city")
    property_state           = _los(state, "property_state")
    property_zip             = _los(state, "property_zip")
    ami_eligibility          = _los(state, "ami_eligibility")

    has_coborrower = bool(coborrower_first_name and coborrower_last_name)

    # ── Read Doc Fields ───────────────────────────────────────────────────
    dl_expiry_doc            = _doc(state, "dl_expiry")
    dl_name_doc              = _doc(state, "dl_name")
    purchase_price_doc       = _doc(state, "purchase_price")
    purchase_property_address_doc = _doc(state, "purchase_property_address")

    # ── Rule: Required Fields Populated ───────────────────────────────────
    required_fields = {
        "Borrower First Name":    borrower_first_name,
        "Borrower Last Name":     borrower_last_name,
        "Borrower SSN":           borrower_ssn,
        "Borrower Date of Birth": borrower_dob,
        "Borrower Marital Status": borrower_marital_status,
    }
    for label, val in required_fields.items():
        if not val:
            _flag(flags, "2.1", "Required Field Empty", "warning",
                  f"{label} is blank on the Borrower Summary screen.",
                  "Populate the missing field before proceeding.")

    if has_coborrower:
        coborr_required = {
            "Co-Borrower Marital Status": coborrower_marital_status,
        }
        for label, val in coborr_required.items():
            if not val:
                _flag(flags, "2.1", "Required Field Empty", "warning",
                      f"{label} is blank.",
                      "Populate the missing field before proceeding.")

    # ── Rule: Phone — cell phone fallback from home phone ────────────────
    # Borrower: write home phone → cell (1490) if cell is empty
    _write_fields(
        loan_id,
        {"1490": borrower_home_phone if not borrower_cell_phone else None},
        substep="2.1",
        flags=flags,
        state=state,
        labels={"1490": "Borrower Cell Phone (copied from Home Phone)"},
    )

    # Co-borrower: write home phone → cell (1480) if cell is empty and coborrower present
    if has_coborrower:
        _write_fields(
            loan_id,
            {"1480": coborrower_home_phone if not coborrower_cell_phone else None},
            substep="2.1",
            flags=flags,
            state=state,
            labels={"1480": "Co-Borrower Cell Phone (copied from Co-Borrower Home Phone)"},
        )

    if not borrower_home_phone and not borrower_cell_phone:
        _flag(flags, "2.1", "Required Field Empty", "warning",
              "Both Borrower Home Phone and Cell Phone are blank.",
              "Obtain at least one phone number for the borrower.")

    if has_coborrower and not coborrower_home_phone and not coborrower_cell_phone:
        _flag(flags, "2.1", "Required Field Empty", "warning",
              "Both Co-Borrower Home Phone and Cell Phone are blank.",
              "Obtain at least one phone number for the co-borrower.")

    # ── Rule: Accept Text/SMS ─────────────────────────────────────────────
    _write_fields(
        loan_id,
        {"4920": "Y" if not _is_checked(borrower_accept_sms) else None},
        substep="2.1",
        flags=flags,
        state=state,
        labels={"4920": "Borrower Accept Text/SMS"},
    )

    if has_coborrower:
        _write_fields(
            loan_id,
            {"4935": "Y" if not _is_checked(coborrower_accept_sms) else None},
            substep="2.1",
            flags=flags,
            state=state,
            labels={"4935": "Co-Borrower Accept Text/SMS"},
        )

    # ── Rule: Email present ───────────────────────────────────────────────
    if not borrower_email:
        _flag(flags, "2.1", "Email Missing", "warning",
              "Borrower email address is blank.",
              "Obtain and enter borrower email address.")

    if has_coborrower and not coborrower_email:
        _flag(flags, "2.1", "Co-Borrower Email Missing", "warning",
              "Co-borrower email address is blank.",
              "Obtain and enter co-borrower email address.")

    # ── Rule: Credit Scores ───────────────────────────────────────────────
    borr_credit_fields = {
        "Borrower Experian/FICO (67)":           experian_score,
        "Borrower TransUnion/Empirica (1450)":   transunion_score,
        "Borrower Equifax/Beacon (1414)":        equifax_score,
    }
    for label, val in borr_credit_fields.items():
        if not val:
            _flag(flags, "2.1", "Credit Score Missing", "warning",
                  f"{label} is blank.",
                  "Ensure credit has been pulled and all bureau scores are populated.")

    if not credit_score:
        _flag(flags, "2.1", "Credit Score Missing", "critical",
              "Middle credit score (field 1168) is blank.",
              "Ensure credit has been pulled and scores are populated in Encompass.")

    if not credit_score_decision:
        _flag(flags, "2.1", "Credit Score Missing", "warning",
              "Credit Score for Decision Making (VASUMM.X23) is blank.",
              "Populate the decision credit score field.")

    if not credit_reference_number:
        _flag(flags, "2.1", "Credit Reference Number Missing", "warning",
              "Credit Reference Number (field 300) is blank.",
              "Enter the credit reference number from the credit report.")

    if has_coborrower:
        coborr_credit_fields = {
            "Co-Borrower Experian/FICO (60)":          coborrower_experian_score,
            "Co-Borrower TransUnion/Empirica (1452)":  coborrower_transunion_score,
            "Co-Borrower Equifax/Beacon (1415)":       coborrower_equifax_score,
        }
        for label, val in coborr_credit_fields.items():
            if not val:
                _flag(flags, "2.1", "Credit Score Missing", "warning",
                      f"{label} is blank.",
                      "Ensure co-borrower credit scores are populated.")

    # ── Rule: Loan Amount > 0 ─────────────────────────────────────────────
    try:
        if not loan_amount or float(str(loan_amount).replace(",", "")) <= 0:
            _flag(flags, "2.1", "Loan Amount Missing", "critical",
                  f"Loan amount is '{loan_amount or 'blank'}' — must be greater than zero.",
                  "Enter the correct loan amount before proceeding.")
    except (ValueError, TypeError):
        _flag(flags, "2.1", "Loan Amount Missing", "critical",
              f"Loan amount '{loan_amount}' could not be parsed.",
              "Enter a valid numeric loan amount.")

    # ── Rule: Property Address (reads from state["address_validation"] set by step 0.5) ──
    addr_val = state.get("address_validation", {})
    if addr_val:
        if addr_val.get("valid") is False:
            _flag(flags, "2.1", "Property Address Invalid", "warning",
                  f"USPS could not confirm address: {addr_val.get('los_address', property_address)}. "
                  f"Error: {addr_val.get('error', 'unknown')}.",
                  "Verify the property address is correct in Encompass.")
        if addr_val.get("mismatch_with_purchase_contract"):
            _flag(flags, "2.1", "Property Address Mismatch", "warning",
                  f"Encompass: '{addr_val.get('los_address')}' vs Purchase Contract: "
                  f"'{addr_val.get('purchase_contract_address')}'.",
                  "Correct the property address in Encompass and flag for Lock Desk if needed.")
    elif purchase_property_address_doc and property_address:
        # Fallback if validate_property_address wasn't run yet
        los_num = str(property_address).strip().split()[0] if property_address else ""
        doc_num = str(purchase_property_address_doc).strip().split()[0] if purchase_property_address_doc else ""
        if los_num and doc_num and los_num != doc_num:
            _flag(flags, "2.1", "Property Address Mismatch", "warning",
                  f"Encompass: '{property_address}' vs Purchase Contract: '{purchase_property_address_doc}'.",
                  "Correct the property address in Encompass and flag for Lock Desk if needed.")

    # ── Rule: ID Not Expired ──────────────────────────────────────────────
    if dl_expiry_doc:
        try:
            for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m-%d-%Y"):
                try:
                    expiry_date = datetime.strptime(str(dl_expiry_doc).strip(), fmt).date()
                    break
                except ValueError:
                    continue
            else:
                expiry_date = None

            if expiry_date and expiry_date < datetime.now(timezone.utc).date():
                _flag(flags, "2.1", "Borrower ID Expired", "warning",
                      f"Driver's License expired on {dl_expiry_doc}.",
                      "Request a valid, non-expired government ID from the borrower.")
        except Exception:
            pass

    # ── Build result ──────────────────────────────────────────────────────
    result = {
        "success": True,
        "substep": "2.1",
        "tool": "review_borrower_summary",
        "has_coborrower": has_coborrower,
        "flags_count": len(flags),
        "credit_score": credit_score,
        "credit_score_decision": credit_score_decision,
        "credit_reference_number": credit_reference_number,
        "loan_amount": loan_amount,
        "ami_eligibility": ami_eligibility,
        "message": "Review Borrower Summary - Origination completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_BORROWER_SUMMARY] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
