"""review_borrower_summary — Tool for substep 2.1: Review Borrower Summary - Origination

Step 2 (STEP_02): Borrower Summary - Origination
Phase: DATA_REVIEW

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
import re
from datetime import date, datetime, timedelta, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _doc_all, _write_fields, _relevant_docs

logger = logging.getLogger(__name__)

CREDIT_REPORT_VALIDITY_DAYS = 120
INQUIRY_LOOKBACK_DAYS = 120


def _flag(flags, substep, title, severity, details, suggestion, docs=None):
    f = {
        "substep": substep,
        "title": title,
        "severity": severity,
        "details": details,
        "suggestion": suggestion,
        "resolved": False,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    if docs:
        f["relevant_documents"] = docs
    flags.append(f)


def _is_checked(val) -> bool:
    """Return True if an Encompass checkbox field is checked (Y / true / True / 1)."""
    if val is None:
        return False
    return str(val).strip().lower() in ("y", "yes", "true", "1")


def _id_copies(state: dict) -> dict:
    """Collect per-copy Government ID info from the Driver's License doc copies.

    Returns {copy_index: {"gov_id": ..., "gov_id_type": ..., "name": ...}}.
    """
    out: dict = {}

    def _ingest(key: str, field: str) -> None:
        for c in _doc_all(state, key):
            if not isinstance(c, dict):
                continue
            val = c.get("value")
            if val in (None, ""):
                continue
            out.setdefault(c.get("copy_index", 0), {}).setdefault(field, val)

    _ingest("dl_gov_id", "gov_id")
    _ingest("dl_gov_id_type", "gov_id_type")
    _ingest("dl_borrower_name", "name")
    _ingest("dl_name", "name")  # fallback name source
    return out


def _match_copy_to_person(records: dict, first, last):
    """Return the copy_index whose ID name best matches the given person, else None."""
    first_l = (first or "").strip().lower()
    last_l = (last or "").strip().lower()
    if not (first_l or last_l):
        return None
    best = None
    for ci, rec in records.items():
        name = (rec.get("name") or "").lower()
        if not name:
            continue
        score = (2 if last_l and last_l in name else 0) + (1 if first_l and first_l in name else 0)
        if score and (best is None or score > best[1]):
            best = (ci, score)
    return best[0] if best else None


def _blank(val) -> bool:
    """True when a LOS value is missing/empty (so it's safe to fill)."""
    return not (val and str(val).strip())


def _parse_date(val):
    """Best-effort parse of a date string to a date, or None."""
    if not val:
        return None
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m-%d-%Y", "%m/%d/%y"):
        try:
            return datetime.strptime(str(val).strip(), fmt).date()
        except ValueError:
            continue
    return None


def _surname_on(surname, text) -> bool:
    """True when the borrower surname appears in a name string as whole token(s).

    Conservative on purpose: only used to raise a *mismatch* flag when the
    borrower's last name is entirely absent from a document name. Compares
    tokenized name parts rather than a raw substring so a short surname does not
    match inside an unrelated name (e.g. 'Le' inside 'Leonard'); a multi-token
    surname must have every token present as a whole token.
    """
    s_tokens = [tok for tok in re.split(r"[^a-z0-9]+", (surname or "").lower()) if tok]
    t_tokens = {tok for tok in re.split(r"[^a-z0-9]+", (text or "").lower()) if tok}
    if not s_tokens or not t_tokens:
        return False
    return all(tok in t_tokens for tok in s_tokens)


def _digits(val) -> str:
    """Digits-only string (used to compare SSNs without formatting noise)."""
    return re.sub(r"\D", "", str(val or ""))


def _norm_addr(val) -> str:
    """Lowercase, punctuation-stripped, single-spaced address for loose compare."""
    return re.sub(r"[^a-z0-9]+", " ", str(val or "").lower()).strip()


def _norm_name(val) -> str:
    """Lowercase, punctuation-stripped, single-spaced name for loose compare."""
    return re.sub(r"[^a-z0-9]+", " ", str(val or "").lower()).strip()


def _occ_is_investment(occ) -> bool:
    """True for investment / non-owner-occupied LOS occupancy values."""
    o = str(occ or "").lower()
    return any(k in o for k in ("investment", "investor", "non-owner", "nonowner", "non owner"))


def _occ_is_primary(occ) -> bool:
    """True only for an unambiguous owner-occupied / primary occupancy.

    Mutually exclusive with :func:`_occ_is_investment` — a value like
    'Non-Owner Occupied' contains 'owner' but must NOT count as primary."""
    o = str(occ or "").lower()
    if not o or _occ_is_investment(o) or any(k in o for k in ("second", "vacation")):
        return False
    return "primary" in o or "owner" in o


def _split_akas(raw) -> list:
    """Split a credit-report AKA blob into individual alternate names.

    Handles common delimiters and the 'AKA' / 'A/K/A' / 'FKA' markers; drops
    empty fragments."""
    parts = re.split(r"\s*(?:;|,|/|\||\band\b|\ba/?k/?a\b|\bf/?k/?a\b|\baka\b|\bfka\b)\s*",
                     str(raw or ""), flags=re.IGNORECASE)
    return [p.strip() for p in parts if p and p.strip()]


def _addr_match(a, b) -> bool:
    """Loose address equality: same house number AND street-name token overlap.

    Returns True when we cannot meaningfully compare (missing data) so a
    mismatch is only raised on a genuine house-number/street disagreement."""
    na, nb = _norm_addr(a), _norm_addr(b)
    if not na or not nb:
        return True
    ta, tb = na.split(), nb.split()
    an = ta[0] if ta else ""
    bn = tb[0] if tb else ""
    if an.isdigit() and bn.isdigit() and an != bn:
        return False
    return len(set(ta) & set(tb)) >= 2


def _appraisal_address(state: dict) -> Optional[str]:
    """Appraisal-specific subject address.

    Prefers the collision-free ``appraisal_property_address`` (lowercase
    ``appraisal_report`` schema). Falls back to a ``property_address`` copy whose
    provenance is the appraisal — that key is shared with the Title Report, so we
    only accept it when ``source_document`` names the appraisal."""
    v = _doc(state, "appraisal_property_address")
    if v:
        return v
    for c in _doc_all(state, "property_address"):
        if "appraisal" in (c.get("source_document") or "").lower() and c.get("value"):
            return c.get("value")
    return None


def _sourced_property_address(state: dict, source_hint: str) -> Optional[str]:
    """A ``property_address`` copy whose provenance matches ``source_hint``.

    The ``property_address`` key is shared across the Title Report, Lock
    Confirmation, CPL, etc., so we only accept the copy whose ``source_document``
    names the document we want (e.g. 'title')."""
    for c in _doc_all(state, "property_address"):
        if source_hint in (c.get("source_document") or "").lower() and c.get("value"):
            return c.get("value")
    return None


def _norm_gov_id_type(raw) -> Optional[str]:
    """Normalize an OCR'd Government ID type to a canonical Encompass value.

    The source is always the Driver's License doc, so license-like variants map
    to "DL"; any other extracted type is preserved as-is."""
    s = str(raw or "").strip()
    if not s:
        return None
    low = s.lower()
    if "driver" in low or low in ("dl", "dln", "d/l", "dl#"):
        return "DL"
    return s


def _write_government_id(state, loan_id, flags, b_first, b_last, c_first, c_last, has_co) -> None:
    """Populate Government ID + Type for borrower (5053/5055) and co-borrower
    (5054/5056) from the Driver's License doc content, mapping each license copy
    to the correct person by name (falling back to copy order)."""
    records = _id_copies(state)
    if not records:
        return

    order = sorted(records)
    b_ci = _match_copy_to_person(records, b_first, b_last)
    if b_ci is None and order:
        b_ci = order[0]

    c_ci = None
    if has_co:
        c_ci = _match_copy_to_person(records, c_first, c_last)
        if c_ci is None or c_ci == b_ci:
            rest = [ci for ci in order if ci != b_ci]
            c_ci = rest[0] if rest else None

    # field id → LOS state key, so we can honor write-only-if-blank and not
    # clobber a manually-corrected Government ID / Type on every run.
    _gov_los = {"5053": "borrower_gov_id", "5054": "coborrower_gov_id",
                "5055": "borrower_gov_id_type", "5056": "coborrower_gov_id_type"}

    def _write_person(ci, id_field, type_field, label):
        if ci is None:
            return
        rec = records.get(ci, {})
        updates = {}
        # 5053/5054 — Government ID number, write only when Encompass is blank.
        if rec.get("gov_id") and _blank(_los(state, _gov_los[id_field])):
            updates[id_field] = rec["gov_id"]
        # 5055/5056 — normalize OCR type to the canonical "DL" (source is the
        # Driver's License doc); write only when blank.
        norm_type = _norm_gov_id_type(rec.get("gov_id_type"))
        if norm_type and _blank(_los(state, _gov_los[type_field])):
            updates[type_field] = norm_type
        if updates:
            _write_fields(loan_id=loan_id, updates=updates, substep="2.1",
                          flags=flags, state=state,
                          labels={id_field: f"{label} Government ID",
                                  type_field: f"{label} Government ID Type"})

    _write_person(b_ci, "5053", "5055", "Borrower")
    if has_co:
        _write_person(c_ci, "5054", "5056", "Co-Borrower")


@tool
def review_borrower_summary(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Walk through the Borrower Summary – Origination screen. Check every field for completeness (cell phone = home phone if empty). Auto-check accept text/SMS if unchecked. Verify credit score, loan amount, email, marital status populated. Cross-check property address against Purchase Contract.

    Call this tool during STEP_02 (Borrower Summary - Origination) as substep 2.1.
    Reads LOS: borrower_first_name, borrower_last_name, borrower_cell_phone, borrower_home_phone,
    borrower_accept_sms, borrower_dob, borrower_email, borrower_marital_status,
    coborrower_first_name, coborrower_last_name, coborrower_cell_phone, coborrower_accept_sms,
    coborrower_email, coborrower_marital_status, property_address, property_city, property_state,
    property_zip, credit_score_decision, loan_amount, appraised_value, estimated_value, los_purchase_price,
    loan_purpose, ami_eligibility
    Reads Docs: Driver's License, Purchase Agreement
    Flags: Required Field Empty, Borrower ID Expired, Property Address Mismatch, Loan Amount Missing,
    Credit Score Missing, Email Missing, Purchase Price Mismatch, Estimated Value Mismatch
    Writes: 1490 (borr cell ← home phone), 4920 (borr SMS), 4935 (coborr SMS),
            356 (appraised value ← estimated value if 356 is empty)
    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[REVIEW_BORROWER_SUMMARY] Starting for loan {str(loan_id)[:8]}...")

    flags = []

    # ── Read LOS Fields (pre-fetched by fetch_los_fields via state) ──────
    borrower_first_name      = _los(state, "borrower_first_name")
    borrower_last_name       = _los(state, "borrower_last_name")
    borrower_ssn             = _los(state, "borrower_ssn")
    coborrower_ssn           = _los(state, "coborrower_ssn")
    borrower_dob             = _los(state, "borrower_dob")
    borrower_home_phone      = _los(state, "borrower_home_phone")
    borrower_cell_phone      = _los(state, "borrower_cell_phone")   # field 1490
    borrower_email           = _los(state, "borrower_email")
    borrower_marital_status  = _los(state, "borrower_marital_status")
    borrower_accept_sms      = _los(state, "borrower_accept_sms")   # field 4920

    coborrower_first_name    = _los(state, "coborrower_first_name")
    coborrower_last_name     = _los(state, "coborrower_last_name")
    coborrower_cell_phone    = _los(state, "coborrower_cell_phone")  # field 1480
    coborrower_home_phone    = _los(state, "coborrower_home_phone")
    coborrower_email         = _los(state, "coborrower_email")
    coborrower_marital_status = _los(state, "coborrower_marital_status")
    coborrower_accept_sms    = _los(state, "coborrower_accept_sms")  # field 4935

    experian_score           = _los(state, "experian_score")
    transunion_score         = _los(state, "transunion_score")
    equifax_score            = _los(state, "equifax_score")
    coborrower_experian_score  = _los(state, "coborrower_experian_score")
    coborrower_transunion_score = _los(state, "coborrower_transunion_score")
    coborrower_equifax_score   = _los(state, "coborrower_equifax_score")
    credit_score_decision    = _los(state, "credit_score_decision")
    credit_reference_number  = _los(state, "credit_reference_number")
    loan_amount              = _los(state, "loan_amount")
    appraised_value          = _los(state, "appraised_value")       # field 356
    estimated_value          = _los(state, "estimated_value")       # field 1821
    los_purchase_price       = _los(state, "los_purchase_price")    # field 136
    loan_purpose             = _los(state, "loan_purpose")          # field 19
    property_address         = _los(state, "property_address")
    property_address_urla    = _los(state, "property_address_urla")  # URLA.X73 — editable
    property_city            = _los(state, "property_city")
    property_state           = _los(state, "property_state")
    property_zip             = _los(state, "property_zip")
    borr_present_addr        = _los(state, "borr_present_addr")      # FR0126
    borr_present_city        = _los(state, "borr_present_city")      # FR0106
    borr_present_state       = _los(state, "borr_present_state")     # FR0107
    borr_present_zip         = _los(state, "borr_present_zip")       # FR0108
    ami_eligibility          = _los(state, "ami_eligibility")

    # ── Transaction Details ───────────────────────────────────────────────
    lender                   = _los(state, "lender")               # field 1264
    loan_program             = _los(state, "loan_program")         # field 1401
    closing_cost_program     = _los(state, "closing_cost_program") # field 1785
    loan_number              = _los(state, "loan_number")          # field 364
    mers_min                 = _los(state, "mers_min")             # field 1051

    # ── Loan Info ─────────────────────────────────────────────────────────
    occupancy                = _los(state, "occupancy")            # field 1811
    loan_type                = _los(state, "loan_type")            # field 1172
    lien_position            = _los(state, "lien_position")        # field 420
    amort_type               = _los(state, "amort_type")           # field 608
    loan_term_months         = _los(state, "loan_term_months")     # field 4
    term_due_in_months       = _los(state, "term_due_in_months")   # field 325

    # ── Rates ─────────────────────────────────────────────────────────────
    note_rate                = _los(state, "note_rate")            # field 3
    qual_rate                = _los(state, "qualifying_rate")      # field 1014
    undiscounted_rate        = _los(state, "undiscounted_rate")    # field 3293

    # ── Payments / Income ────────────────────────────────────────────────
    monthly_payment          = _los(state, "monthly_payment")      # field 5
    total_monthly_payment    = _los(state, "total_monthly_payment") # field 912
    monthly_income           = _los(state, "monthly_income")       # field 736

    # ── Down Payment ─────────────────────────────────────────────────────
    down_payment_pct         = _los(state, "down_payment_pct")     # field 1771
    down_payment_amount      = _los(state, "down_payment_amount")  # field 1335

    # ── Lock / Rate Dates ────────────────────────────────────────────────
    rate_is_locked           = _los(state, "rate_is_locked")       # field 2400
    lock_date                = _los(state, "lock_date")            # field 761
    lock_days                = _los(state, "lock_days")            # field 432
    lock_expires             = _los(state, "lock_expires")         # field 762
    last_rate_set_date       = _los(state, "last_rate_set_date")   # field 3253
    rate_lock_disclosure_date_val = _los(state, "rate_lock_disclosure_date")  # field 3259
    est_closing_date_val     = _los(state, "closing_date")         # field 763
    borrower_est_closing_date_val = _los(state, "borrower_est_closing_date")  # field 4114
    secondary_registration   = _los(state, "secondary_registration") # field 3941

    has_coborrower = bool(coborrower_first_name and coborrower_last_name)

    # ── Read Doc Fields ───────────────────────────────────────────────────
    dl_expiry_doc            = _doc(state, "dl_expiry")
    dl_borrower_name_doc     = _doc(state, "dl_borrower_name") or _doc(state, "dl_name")
    purchase_price_doc       = _doc(state, "purchase_price")
    purchase_property_address_doc = _doc(state, "purchase_property_address")
    pa_buyer_name_doc        = _doc(state, "pa_buyer_name")
    purchase_closing_date_doc = _doc(state, "purchase_closing_date") or _doc(state, "pa_closing_date")

    # ── Rule: Required Fields Populated ───────────────────────────────────
    required_fields = {
        "Borrower First Name":    borrower_first_name,
        "Borrower Last Name":     borrower_last_name,
        "Borrower SSN":           borrower_ssn,
        "Borrower Date of Birth": borrower_dob,
        "Borrower Marital Status": borrower_marital_status,
    }
    for label, val in required_fields.items():
        if not val:
            _flag(flags, "2.1", "Required Field Empty", "warning",
                  f"{label} is blank on the Borrower Summary screen.",
                  "Populate the missing field before proceeding.")

    if has_coborrower:
        coborr_required = {
            "Co-Borrower Marital Status": coborrower_marital_status,
        }
        for label, val in coborr_required.items():
            if not val:
                _flag(flags, "2.1", "Required Field Empty", "warning",
                      f"{label} is blank.",
                      "Populate the missing field before proceeding.")

    # ── Rule: Phone — cell phone fallback from home phone ────────────────
    # Borrower: write home phone → cell (1490) if cell is empty
    _write_fields(
        loan_id,
        {"1490": borrower_home_phone if not borrower_cell_phone else None},
        substep="2.1",
        flags=flags,
        state=state,
        labels={"1490": "Borrower Cell Phone (copied from Home Phone)"},
    )

    # Co-borrower: write home phone → cell (1480) if cell is empty and coborrower present
    if has_coborrower:
        _write_fields(
            loan_id,
            {"1480": coborrower_home_phone if not coborrower_cell_phone else None},
            substep="2.1",
            flags=flags,
            state=state,
            labels={"1480": "Co-Borrower Cell Phone (copied from Co-Borrower Home Phone)"},
        )

    if not borrower_home_phone and not borrower_cell_phone:
        _flag(flags, "2.1", "Required Field Empty", "warning",
              "Both Borrower Home Phone and Cell Phone are blank.",
              "Obtain at least one phone number for the borrower.")

    if has_coborrower and not coborrower_home_phone and not coborrower_cell_phone:
        _flag(flags, "2.1", "Required Field Empty", "warning",
              "Both Co-Borrower Home Phone and Cell Phone are blank.",
              "Obtain at least one phone number for the co-borrower.")

    # ── Rule: Accept Text/SMS ─────────────────────────────────────────────
    _write_fields(
        loan_id,
        {"4920": "true" if not _is_checked(borrower_accept_sms) else None},
        substep="2.1",
        flags=flags,
        state=state,
        labels={"4920": "Borrower Accept Text/SMS"},
    )

    if has_coborrower:
        _write_fields(
            loan_id,
            {"4935": "true" if not _is_checked(coborrower_accept_sms) else None},
            substep="2.1",
            flags=flags,
            state=state,
            labels={"4935": "Co-Borrower Accept Text/SMS"},
        )

    # ── Rule: Email present ───────────────────────────────────────────────
    if not borrower_email:
        _flag(flags, "2.1", "Email Missing", "warning",
              "Borrower email address is blank.",
              "Obtain and enter borrower email address.")

    if has_coborrower and not coborrower_email:
        _flag(flags, "2.1", "Co-Borrower Email Missing", "warning",
              "Co-borrower email address is blank.",
              "Obtain and enter co-borrower email address.")

    # ── Rule: Credit Scores ───────────────────────────────────────────────
    borr_credit_fields = {
        "Borrower Experian/FICO (67)":           experian_score,
        "Borrower TransUnion/Empirica (1450)":   transunion_score,
        "Borrower Equifax/Beacon (1414)":        equifax_score,
    }
    for label, val in borr_credit_fields.items():
        if not val:
            _flag(flags, "2.1", "Credit Score Missing", "warning",
                  f"{label} is blank.",
                  "Ensure credit has been pulled and all bureau scores are populated.")

    # Representative / median credit score = VASUMM.X23 (Credit Score for Decision Making).
    # Field 1168 ("Credit Score Middle") is unreliable / often blank in Encompass and is no
    # longer used. The three bureau scores (67/1414/1450) are used only to decide severity.
    if not credit_score_decision:
        _bureau_scores = [
            int(s) for s in (experian_score, transunion_score, equifax_score)
            if str(s).strip().isdigit()
        ]
        if not _bureau_scores:
            _flag(flags, "2.1", "Credit Score Missing", "critical",
                  "No representative credit score available — Credit Score for Decision Making "
                  "(VASUMM.X23) and all three bureau scores (67/1414/1450) are blank.",
                  "Ensure credit has been pulled and scores are populated in Encompass.")
        else:
            _median = sorted(_bureau_scores)[len(_bureau_scores) // 2]
            _flag(flags, "2.1", "Credit Score Missing", "warning",
                  f"Credit Score for Decision Making (VASUMM.X23) is blank, but bureau scores are "
                  f"present (median {_median}). Verify the representative/decision score is populated.",
                  "Populate the decision credit score field (VASUMM.X23).")

    if not credit_reference_number and not _doc(state, "credit_reference_number"):
        _flag(flags, "2.1", "Credit Reference Number Missing", "warning",
              "Credit Reference Number (field 300) is blank and no report ID was extracted.",
              "Enter the credit reference number from the credit report.")

    if has_coborrower:
        coborr_credit_fields = {
            "Co-Borrower Experian/FICO (60)":          coborrower_experian_score,
            "Co-Borrower TransUnion/Empirica (1452)":  coborrower_transunion_score,
            "Co-Borrower Equifax/Beacon (1415)":       coborrower_equifax_score,
        }
        for label, val in coborr_credit_fields.items():
            if not val:
                _flag(flags, "2.1", "Credit Score Missing", "warning",
                      f"{label} is blank.",
                      "Ensure co-borrower credit scores are populated.")

    # ── Rule: Loan Amount > 0 ─────────────────────────────────────────────
    try:
        if not loan_amount or float(str(loan_amount).replace(",", "")) <= 0:
            _flag(flags, "2.1", "Loan Amount Missing", "critical",
                  f"Loan amount is '{loan_amount or 'blank'}' — must be greater than zero.",
                  "Enter the correct loan amount before proceeding.")
    except (ValueError, TypeError):
        _flag(flags, "2.1", "Loan Amount Missing", "critical",
              f"Loan amount '{loan_amount}' could not be parsed.",
              "Enter a valid numeric loan amount.")

    # ── Rule: Purchase Price — LOS vs Purchase Contract ──────────────────
    def _parse_amount(val) -> float | None:
        """Parse a dollar amount string like '$580,000' or '580000' to float."""
        if not val:
            return None
        try:
            return float(str(val).replace(",", "").replace("$", "").strip())
        except (ValueError, TypeError):
            return None

    PRICE_TOLERANCE = 500.0  # flag if values differ by more than this

    purchase_price_doc_amount = _parse_amount(purchase_price_doc)
    los_purchase_price_amount = _parse_amount(los_purchase_price)
    estimated_value_amount    = _parse_amount(estimated_value)
    appraised_value_amount    = _parse_amount(appraised_value)

    if purchase_price_doc_amount and los_purchase_price_amount:
        diff = abs(purchase_price_doc_amount - los_purchase_price_amount)
        if diff > PRICE_TOLERANCE:
            _flag(flags, "2.1", "Purchase Price Mismatch", "warning",
                  f"LOS purchase price (field 136): ${los_purchase_price_amount:,.0f} "
                  f"vs Purchase Contract: ${purchase_price_doc_amount:,.0f} "
                  f"(diff: ${diff:,.0f}).",
                  "Correct the purchase price in Encompass to match the Purchase Contract.",
                  docs=_relevant_docs(state, "purchase_price"))
    elif not los_purchase_price_amount and purchase_price_doc_amount:
        _flag(flags, "2.1", "Purchase Price Missing in LOS", "warning",
              f"Purchase Contract shows ${purchase_price_doc_amount:,.0f} but "
              f"LOS purchase price (field 136) is blank.",
              "Enter the purchase price in Encompass.",
              docs=_relevant_docs(state, "purchase_price"))

    # ── Rule: Estimated Value vs Purchase Price ───────────────────────────
    if purchase_price_doc_amount and estimated_value_amount:
        diff = abs(estimated_value_amount - purchase_price_doc_amount)
        if diff > PRICE_TOLERANCE:
            _flag(flags, "2.1", "Estimated Value vs Purchase Price Mismatch", "warning",
                  f"Estimated value (field 1821): ${estimated_value_amount:,.0f} "
                  f"vs Purchase Contract price: ${purchase_price_doc_amount:,.0f} "
                  f"(diff: ${diff:,.0f}).",
                  "Verify the estimated value is correct, or update to match the purchase price.",
                  docs=_relevant_docs(state, "purchase_price"))
    elif not estimated_value_amount:
        _flag(flags, "2.1", "Estimated Value Empty", "warning",
              "Estimated value (field 1821) is blank.",
              "Enter the estimated value in Encompass.")

    # ── Rule: Appraised Value — copy from Estimated Value if empty ────────
    if not appraised_value_amount and estimated_value_amount:
        clean_est = str(int(estimated_value_amount)) if estimated_value_amount == int(estimated_value_amount) \
            else str(estimated_value_amount)
        _write_fields(
            loan_id=loan_id,
            updates={"356": clean_est},
            substep="2.1",
            flags=flags,
            state=state,
            labels={"356": "Appraised Value"},
        )
    elif not appraised_value_amount:
        _flag(flags, "2.1", "Appraised Value Empty", "warning",
              "Appraised value (field 356) is blank and no estimated value to copy from.",
              "Enter the appraised value once the appraisal report is received.")

    # ── Rule: Property Address (reads from state["address_validation"] set by step 0.5) ──
    addr_val = state.get("address_validation", {})
    if addr_val and not addr_val.get("skipped"):
        if addr_val.get("valid") is False:
            _dpv = addr_val.get("dpv_confirmation")
            _err = addr_val.get("error")
            if _err:
                _reason = f"Error: {_err}"
            elif _dpv is None:
                _reason = "USPS returned no delivery confirmation (DPV null) — address may be undeliverable or outside USPS coverage"
            else:
                _reason = f"DPV confirmation: {_dpv}"
            _flag(flags, "2.1", "Property Address Invalid", "warning",
                  f"USPS could not confirm address: {addr_val.get('los_address', property_address)}. {_reason}.",
                  "Verify the property address is correct in Encompass.")
        if addr_val.get("mismatch_with_purchase_contract"):
            _flag(flags, "2.1", "Property Address Mismatch", "warning",
                  f"Encompass: '{addr_val.get('los_address')}' vs Purchase Contract: "
                  f"'{addr_val.get('purchase_contract_address')}'.",
                  "Correct the property address in Encompass and flag for Lock Desk if needed.",
                  docs=_relevant_docs(state, "purchase_property_address"))
    elif purchase_property_address_doc and property_address:
        # Fallback if validate_property_address wasn't run yet
        los_num = str(property_address).strip().split()[0] if property_address else ""
        doc_num = str(purchase_property_address_doc).strip().split()[0] if purchase_property_address_doc else ""
        if los_num and doc_num and los_num != doc_num:
            _flag(flags, "2.1", "Property Address Mismatch", "warning",
                  f"Encompass: '{property_address}' vs Purchase Contract: '{purchase_property_address_doc}'.",
                  "Correct the property address in Encompass and flag for Lock Desk if needed.",
                  docs=_relevant_docs(state, "purchase_property_address"))

    # ── Rule: Cash-Out Refi — Borrower Current Address vs Subject Property ──
    _is_cashout = "cashout" in (loan_purpose or "").lower().replace("-", "").replace(" ", "")
    if _is_cashout and borr_present_addr:
        # Use URLA.X73 as primary (editable); fall back to field 11
        _subj_street = (property_address_urla or property_address or "").strip().lower()
        _borr_street = (borr_present_addr or "").strip().lower()
        # Compare on street number only (robust to minor formatting differences)
        _subj_num = _subj_street.split()[0] if _subj_street else ""
        _borr_num  = _borr_street.split()[0] if _borr_street else ""
        _subj_full = f"{property_address_urla or property_address}, {property_city}, {property_state} {property_zip}".strip(", ")
        _borr_full = f"{borr_present_addr}, {borr_present_city}, {borr_present_state} {borr_present_zip}".strip(", ")
        if _subj_num and _borr_num and _subj_num != _borr_num:
            _flag(flags, "2.1", "Cash-Out Refi — Borrower Not at Subject Property", "warning",
                  f"Borrower current address ({_borr_full}) does not match subject property "
                  f"({_subj_full}). This is a cash-out refinance.",
                  "Confirm occupancy type is correct. If primary residence, verify borrower "
                  "has moved or update the current address in Encompass.")
        elif _subj_num and _borr_num and _subj_num == _borr_num:
            _flag(flags, "2.1", "Cash-Out Refi — Borrower at Subject Property", "info",
                  f"Borrower current address matches subject property ({_subj_full}). "
                  "Consistent with primary residence cash-out refinance.",
                  "No action needed — occupancy consistent with loan purpose.")

    # ── Checklist cross-checks (AWM Loan Processor Checklist §1 / §9 / §11) ──
    # These reuse data already gathered (Purchase Agreement, Driver's License,
    # occupancy, USPS address_validation) — no new extraction. Flags stay under
    # this tool's substep (2.1); the checklist item mapping lives in the CSV.
    _is_purchase = "purchase" in (loan_purpose or "").lower()
    _borr_name_full = " ".join(p for p in (borrower_first_name, borrower_last_name) if p).strip()

    # §1.4 — Borrower name vs Sales Contract (purchase only)
    if _is_purchase and pa_buyer_name_doc and borrower_last_name:
        if not _surname_on(borrower_last_name, pa_buyer_name_doc):
            _flag(flags, "2.1", "Borrower Name vs Sales Contract", "warning",
                  f"Borrower '{_borr_name_full}' was not found on the Purchase Contract buyer name "
                  f"('{pa_buyer_name_doc}').",
                  "Confirm the borrower name in Encompass matches the sales contract "
                  "(check spelling, middle name, and vesting).",
                  docs=_relevant_docs(state, "pa_buyer_name"))

    # §3.1 — Borrower legal name vs Government ID (name verification; SSN/DOB
    # cross-checks for §1.6 follow below).
    if dl_borrower_name_doc and borrower_last_name:
        if not _surname_on(borrower_last_name, dl_borrower_name_doc):
            _flag(flags, "2.1", "Borrower Name vs ID", "warning",
                  f"Borrower surname '{borrower_last_name}' was not found on the Driver's License "
                  f"name ('{dl_borrower_name_doc}').",
                  "Confirm the borrower's legal name matches the government ID.",
                  docs=_relevant_docs(state, "dl_borrower_name", doc_types=["Driver's License"]))

    # §1.6 — Borrower SSN & DOB vs ID / docs.
    #   SSN is not printed on a Driver's License, so compare the LOS SSN against
    #   the Credit Report SSN (masked to last-4 in the flag). DOB is compared to
    #   the value recovered from the Credit Report / Driver's License OCR.
    _ssn_doc = _doc(state, "borrower_ssn")             # Credit Report
    _los_ssn4, _doc_ssn4 = _digits(borrower_ssn)[-4:], _digits(_ssn_doc)[-4:]
    if _los_ssn4 and _doc_ssn4:
        if _digits(borrower_ssn) != _digits(_ssn_doc):
            _flag(flags, "2.1", "§04 #3 Borrower SSN Mismatch", "warning",
                  f"Encompass borrower SSN (ending {_los_ssn4}) does not match the Credit "
                  f"Report SSN (ending {_doc_ssn4}).",
                  "Verify the borrower SSN in Encompass against the credit report / ID.",
                  docs=_relevant_docs(state, "borrower_ssn", doc_types=["Credit Report"]))
        else:
            _flag(flags, "2.1", "§04 #3 Borrower SSN Confirmed", "info",
                  f"Borrower SSN (ending {_los_ssn4}) matches the Credit Report.",
                  "No action needed — SSN matches the credit report.")

    _dob_doc = _doc(state, "borrower_dob")             # Credit Report / DL OCR
    _los_dob_d, _doc_dob_d = _parse_date(borrower_dob), _parse_date(_dob_doc)
    if _los_dob_d and _doc_dob_d:
        if _los_dob_d != _doc_dob_d:
            _flag(flags, "2.1", "Borrower DOB vs ID / Credit Report", "warning",
                  f"Encompass borrower DOB ({borrower_dob}) does not match the DOB on the "
                  f"ID / credit report ({_dob_doc}).",
                  "Verify the borrower date of birth in Encompass against the ID / credit report.",
                  docs=_relevant_docs(state, "borrower_dob",
                                      doc_types=["Credit Report", "Driver's License"]))
        else:
            _flag(flags, "2.1", "Borrower DOB Confirmed", "info",
                  f"Borrower DOB matches the ID / credit report ({borrower_dob}).",
                  "No action needed — DOB matches.")

    # §3.1 — Applicant AKAs from the Credit Report vs the URLA alias field.
    #   The credit report lists also-known-as / former names. Compare them to the
    #   applicant's legal name and the current URLA alias field (borrower 1869 /
    #   co-borrower 1874): write-if-blank, otherwise flag the missing name(s) for
    #   manual reconciliation (never overwrite a populated alias field).
    def _aka_reconcile(aka_key, field_id, first, last, who):
        aka_raw = _doc(state, aka_key)
        if not aka_raw:
            return
        legal = _norm_name(f"{first or ''} {last or ''}")
        extras = []
        for cand in _split_akas(aka_raw):
            nc = _norm_name(cand)
            if not nc or nc == legal or nc in legal or legal in nc:
                continue
            extras.append(cand.strip())
        if not extras:
            return
        _legal_disp = f"{(first or '').strip()} {(last or '').strip()}".strip()
        cur_alias = _los(state, aka_key)
        if cur_alias and str(cur_alias).strip():
            missing = [e for e in extras if _norm_name(e) not in _norm_name(cur_alias)]
            if missing:
                _flag(flags, "2.1", f"Applicant AKA — Reconcile URLA Aliases ({who})", "warning",
                      f"The credit report lists alternate name(s) for the {who} "
                      f"({', '.join(missing)}) not present in the existing URLA alias field "
                      f"('{cur_alias}').",
                      "Confirm and add the missing also-known-as name(s) to the URLA aliases "
                      "in Encompass (same person — maiden / former name, spelling).",
                      docs=_relevant_docs(state, aka_key, doc_types=["Credit Report"]))
            return
        # Alias field blank → write-if-blank from the credit report. _write_fields
        # appends its own audit flag: an "info-overwrite" on success or a warning on
        # a skipped/rejected write. Only emit the success flag when the write landed.
        _n = len(flags)
        _write_fields(loan_id, {field_id: "; ".join(extras)}, "2.1", flags, state,
                      labels={field_id: f"{who} Alias / AKA (URLA)"})
        _wrote = any(
            f.get("severity") == "info-overwrite" and f"Field {field_id} set to" in f.get("details", "")
            for f in flags[_n:]
        )
        if _wrote:
            _flag(flags, "2.1", f"Applicant AKA — Added to URLA Aliases ({who})", "info",
                  f"Credit-report alternate name(s) for the {who} not reflected in the legal name "
                  f"('{_legal_disp}') were written to the blank URLA alias field: {', '.join(extras)}.",
                  "Verify the also-known-as name(s) belong to the same person.",
                  docs=_relevant_docs(state, aka_key, doc_types=["Credit Report"]))

    _aka_reconcile("borrower_aka", "1869", borrower_first_name, borrower_last_name, "Borrower")
    if has_coborrower:
        _aka_reconcile("coborrower_aka", "1874",
                       coborrower_first_name, coborrower_last_name, "Co-Borrower")

    # ── §04 Credit Report Review (warn/info only, no writes) ──
    _cr_docs = _relevant_docs(
        state, "credit_reference_number", "credit_report_order_date", "borrower_ssn",
        "coborrower_ssn", "borrower_current_address", "employer_name", "inquiries",
        doc_types=["Credit Report"],
    )

    # 04 #1 — Credit Report ID + expiration
    _cr_ref_doc = _doc(state, "credit_reference_number")
    _cr_ref_los = credit_reference_number
    if _cr_ref_doc or _cr_ref_los:
        _dr = _digits(_cr_ref_doc)
        _dl = _digits(_cr_ref_los)
        if _dr and _dl and _dr != _dl:
            _flag(flags, "2.1", "§04 #1 Credit Report ID Mismatch", "warning",
                  f"Credit report ID ('{_cr_ref_doc}') does not match Encompass "
                  f"Credit Reference Number (300) = '{_cr_ref_los}'.",
                  "Verify field 300 matches the report ID in the top-right of the credit report.",
                  docs=_cr_docs)
        elif _dr and not _dl:
            _flag(flags, "2.1", "§04 #1 Credit Report ID Not in Encompass", "warning",
                  f"Credit report shows ID '{_cr_ref_doc}' but Encompass field 300 is blank.",
                  "Enter the credit reference number from the credit report into field 300.",
                  docs=_cr_docs)
        elif _dr and _dl:
            _flag(flags, "2.1", "§04 #1 Credit Report ID Confirmed", "info",
                  f"Credit report ID ('{_cr_ref_doc}') matches Encompass field 300.",
                  "No action needed — credit report ID matches.")

    _cr_order_raw = _doc(state, "credit_report_order_date")
    _cr_order_dt = _parse_date(_cr_order_raw)
    if _cr_order_dt:
        _expiry = _cr_order_dt + timedelta(days=CREDIT_REPORT_VALIDITY_DAYS)
        _close_dt = _parse_date(est_closing_date_val or borrower_est_closing_date_val)
        _today = date.today()
        if _expiry < _today:
            _flag(flags, "2.1", "§04 #1 Credit Report Expired", "warning",
                  f"Credit report ordered {_cr_order_raw} expires {_expiry:%m/%d/%Y} "
                  f"({CREDIT_REPORT_VALIDITY_DAYS}-day validity) — already past today.",
                  "Order a fresh credit report before proceeding.",
                  docs=_cr_docs)
        elif _close_dt and _expiry < _close_dt:
            _flag(flags, "2.1", "§04 #1 Credit Report Expires Before Closing", "warning",
                  f"Credit report ordered {_cr_order_raw} expires {_expiry:%m/%d/%Y}, "
                  f"before the closing date ({_close_dt:%m/%d/%Y}).",
                  "Order a fresh credit report or confirm the closing date.",
                  docs=_cr_docs)
        else:
            _flag(flags, "2.1", "§04 #1 Credit Report Valid", "info",
                  f"Credit report ordered {_cr_order_raw} is valid through {_expiry:%m/%d/%Y}"
                  + (f" (closing {_close_dt:%m/%d/%Y})" if _close_dt else "") + ".",
                  "No action needed — credit report is within the validity window.",
                  docs=_cr_docs)

    # 04 #3 — Co-borrower SSN (borrower handled above in §1.6)
    if has_coborrower:
        _co_ssn_doc = _doc(state, "coborrower_ssn")
        _los_co4, _doc_co4 = _digits(coborrower_ssn)[-4:], _digits(_co_ssn_doc)[-4:]
        if _los_co4 and _doc_co4:
            if _digits(coborrower_ssn) != _digits(_co_ssn_doc):
                _flag(flags, "2.1", "§04 #3 Co-Borrower SSN Mismatch", "warning",
                      f"Encompass co-borrower SSN (ending {_los_co4}) does not match the "
                      f"Credit Report SSN (ending {_doc_co4}).",
                      "Verify the co-borrower SSN in Encompass against the credit report.",
                      docs=_cr_docs)
            else:
                _flag(flags, "2.1", "§04 #3 Co-Borrower SSN Confirmed", "info",
                      f"Co-borrower SSN (ending {_los_co4}) matches the Credit Report.",
                      "No action needed — co-borrower SSN matches the credit report.")

    # 04 #5 — Frozen bureau (score == 0)
    _csf_raw = _doc(state, "credit_score_factors")
    _csf = _csf_raw if isinstance(_csf_raw, list) else []
    _frozen = []
    for entry in _csf:
        if not isinstance(entry, dict):
            continue
        repo = (entry.get("repository") or "").strip()
        score = entry.get("score")
        try:
            if score is not None and float(score) == 0:
                _frozen.append(repo or "Unknown bureau")
        except (TypeError, ValueError):
            continue
    if _frozen:
        _flag(flags, "2.1", "§04 #5 Frozen Credit Bureau", "warning",
              f"Credit bureau(s) returned a score of 0 (frozen or unavailable): "
              f"{', '.join(_frozen)}. The tri-merge may be incomplete.",
              "Confirm whether the bureau is frozen and request an unfreeze or re-pull.",
              docs=_cr_docs)
    elif _csf:
        _flag(flags, "2.1", "§04 #5 Credit Bureaus Active", "info",
              "All reported bureau scores are non-zero — no frozen-bureau signal.",
              "No action needed — tri-merge bureau scores are present.")

    # 04 #4 — Residence address variance + employment discrepancy
    _cr_addr = _doc(state, "borrower_current_address")
    _los_addr = ", ".join(
        p for p in (borr_present_addr, borr_present_city, borr_present_state, borr_present_zip) if p)
    if _cr_addr and _los_addr:
        if not _addr_match(_cr_addr, _los_addr):
            _flag(flags, "2.1", "§04 #4 Credit Report Address Variance", "warning",
                  f"Credit report residence ('{_cr_addr}') does not match the Encompass "
                  f"borrower present address ('{_los_addr}').",
                  "Verify the borrower's current address on the 1003 matches the credit report.",
                  docs=_cr_docs)
        else:
            _flag(flags, "2.1", "§04 #4 Credit Report Address Confirmed", "info",
                  f"Credit report residence matches the Encompass borrower present address.",
                  "No action needed — residence address matches.")

    _cr_employer = (_doc(state, "employer_name") or "").strip()
    _los_employer = (
        (_los(state, "be01_employer_name") or _los(state, "employer_name") or "").strip()
    )
    if _cr_employer and _los_employer:
        _ce, _le = _cr_employer.lower(), _los_employer.lower()
        if _ce not in _le and _le not in _ce:
            _flag(flags, "2.1", "§04 #4 Employment Name Mismatch", "warning",
                  f"Credit report employer ('{_cr_employer}') does not match Encompass "
                  f"employer ('{_los_employer}').",
                  "Verify the borrower's current employer on the 1003 matches the credit report.",
                  docs=_cr_docs)
        else:
            _flag(flags, "2.1", "§04 #4 Employment Name Confirmed", "info",
                  f"Credit report employer ('{_cr_employer}') matches Encompass.",
                  "No action needed — employer matches the credit report.")

    # 04 #7 — Recent inquiries → LOX required
    _inq_raw = _doc(state, "inquiries")
    _inquiries = _inq_raw if isinstance(_inq_raw, list) else []
    _anchor = _cr_order_dt or date.today()
    _cutoff = _anchor - timedelta(days=INQUIRY_LOOKBACK_DAYS)
    _recent = []
    for inq in _inquiries:
        if not isinstance(inq, dict):
            continue
        _idt = _parse_date(inq.get("date"))
        if _idt and _idt >= _cutoff:
            _company = (inq.get("company") or inq.get("name") or "").strip()
            _itype = (inq.get("type") or "").strip()
            _recent.append(
                f"{inq.get('date')}: {_company}" + (f" ({_itype})" if _itype else "")
            )
    if _recent:
        _flag(flags, "2.1", "§04 #7 Recent Credit Inquiries — LOX Required", "warning",
              f"{len(_recent)} credit inquir{'y' if len(_recent) == 1 else 'ies'} within the "
              f"last {INQUIRY_LOOKBACK_DAYS} days — borrower LOX required:\n"
              + "\n".join(f"  • {r}" for r in _recent),
              "Request a Letter of Explanation from the borrower for each recent inquiry.",
              docs=_cr_docs)
    elif _inquiries:
        _flag(flags, "2.1", "§04 #7 No Recent Credit Inquiries", "info",
              f"No credit inquiries within the last {INQUIRY_LOOKBACK_DAYS} days of the report.",
              "No action needed — no recent inquiries requiring LOX.")

    # §1.5 (refi) — Owner-occupied rate/term refi: borrower should reside at subject.
    # (Cash-out refis are already handled by the dedicated rule above.)
    _purpose_norm = (loan_purpose or "").lower().replace("-", "").replace(" ", "")
    _is_refi = "refi" in _purpose_norm
    _is_cashout_p = "cashout" in _purpose_norm
    _occ_primary = _occ_is_primary(occupancy)
    if _is_refi and not _is_cashout_p and _occ_primary and borr_present_addr:
        _subj_street = (property_address_urla or property_address or "").strip().lower()
        _subj_num = _subj_street.split()[0] if _subj_street else ""
        _borr_num = str(borr_present_addr).strip().lower().split()[0] if borr_present_addr else ""
        if _subj_num and _borr_num and _subj_num != _borr_num:
            _subj_full = f"{property_address_urla or property_address}, {property_city}, {property_state} {property_zip}".strip(", ")
            _borr_full_addr = f"{borr_present_addr}, {borr_present_city}, {borr_present_state} {borr_present_zip}".strip(", ")
            _flag(flags, "2.1", "Refinance — Borrower Not at Subject Property", "warning",
                  f"Owner-occupied refinance: borrower current address ({_borr_full_addr}) does not "
                  f"match the subject property ({_subj_full}).",
                  "For a primary-residence refi the borrower should reside at the subject — confirm "
                  "occupancy or update the current address in Encompass.")

    # §9.2 — Property address confirmed vs Encompass (explicit positive result)
    if addr_val and addr_val.get("valid") and not addr_val.get("mismatch_with_purchase_contract"):
        _flag(flags, "2.1", "Property Address Confirmed", "info",
              f"Subject property address confirmed via USPS: "
              f"{addr_val.get('normalized') or property_address}.",
              "No action needed — address matches Encompass / USPS.")

    # §9.3 — Purchase closing date vs Encompass estimated closing date
    if _is_purchase and purchase_closing_date_doc:
        _los_close = est_closing_date_val or borrower_est_closing_date_val
        _pd = _parse_date(purchase_closing_date_doc)
        _ld = _parse_date(_los_close)
        if _pd and _ld and _pd != _ld:
            _flag(flags, "2.1", "Closing Date vs Purchase Contract", "warning",
                  f"Encompass estimated closing date ({_los_close}) differs from the Purchase "
                  f"Contract closing date ({purchase_closing_date_doc}).",
                  "Verify the estimated closing date matches the sales contract.",
                  docs=_relevant_docs(state, "purchase_closing_date", "pa_closing_date"))
        elif not _los_close:
            _flag(flags, "2.1", "Closing Date Missing in LOS", "warning",
                  f"Purchase Contract shows a closing date ({purchase_closing_date_doc}) but the "
                  f"Encompass estimated closing date (763/4114) is blank.",
                  "Enter the estimated closing date in Encompass.",
                  docs=_relevant_docs(state, "purchase_closing_date", "pa_closing_date"))

    # §9.3 — Purchase terms beyond price/closing date: seller credits, financing
    #   contingency, repairs, warranty, and fee allocation. There is no single LOS
    #   field to diff against, so these are surfaced for the processor to confirm
    #   against the fee worksheet / Loan Estimate. Purchase only.
    if _is_purchase:
        _terms = []
        _sc = (_doc(state, "pa_seller_concessions") or _doc(state, "seller_concessions")
               or _doc(state, "seller_credit_amount"))
        if _sc:
            _terms.append(f"Seller credits / concessions: {_sc}")
        _fin = _doc(state, "payment_terms")
        if _fin:
            _terms.append(f"Financing / contingency terms: {_fin}")
        _rep = _doc(state, "seller_repairs")
        if _rep:
            _terms.append(f"Seller repairs: {_rep}")
        _hw = _doc(state, "home_warranty_included") or _doc(state, "home_warranty_amount")
        if _hw:
            _hw_by = _doc(state, "home_warranty_paid_by")
            _terms.append(f"Home warranty: {_hw}" + (f" (paid by {_hw_by})" if _hw_by else ""))
        for _k, _lbl in (("escrow_fees_paid_by", "Escrow / settlement fees paid by"),
                         ("title_insurance_paid_by", "Title insurance paid by"),
                         ("hoa_transfer_fee_paid_by", "HOA transfer fee paid by")):
            _v = _doc(state, _k)
            if _v:
                _terms.append(f"{_lbl}: {_v}")
        _pp = _doc(state, "personal_property_included")
        if _pp:
            _terms.append(f"Personal property included in sale: {_pp}")
        if _terms:
            _flag(flags, "2.1", "Purchase Terms — Confirm", "info",
                  "Purchase Contract terms to confirm against the fee worksheet / Loan Estimate:\n"
                  + "\n".join(f"  • {t}" for t in _terms),
                  "Confirm seller credits, contingencies, repairs, warranty, and fee "
                  "allocation are reflected in Encompass / the fee worksheet.",
                  docs=_relevant_docs(state, "pa_seller_concessions", "payment_terms",
                                      doc_types=["Purchase Agreement"]))

    # §11.5 — Occupancy type is a recognized value (presence is checked in Loan Info below)
    if occupancy:
        _occ_norm = str(occupancy).strip().lower()
        _known = ("primary", "owner", "second", "vacation", "investment", "investor",
                  "non-owner", "nonowner")
        if not any(k in _occ_norm for k in _known):
            _flag(flags, "2.1", "Occupancy Type Unrecognized", "warning",
                  f"Occupancy (1811) = '{occupancy}' is not a recognized occupancy type.",
                  "Set occupancy to Primary Residence / Second Home / Investment as appropriate.")

    # §11.5 (appraisal cross-ref) — appraisal-stated occupancy (URAR 'Occupant'
    #   line: Owner / Tenant / Vacant) vs LOS occupancy (1811). Owner ↔ primary,
    #   Tenant ↔ investment/non-owner; Vacant is inconclusive.
    _appr_occ = _doc(state, "appraisal_occupancy")
    if _appr_occ and occupancy:
        _ao = str(_appr_occ).strip().lower()
        _los_primary = _occ_is_primary(occupancy)
        _los_investment = _occ_is_investment(occupancy)
        _appr_owner = True if "owner" in _ao else (False if "tenant" in _ao else None)
        _appr_docs = _relevant_docs(state, "appraisal_occupancy",
                                    doc_types=["Appraisal (URAR / 1004)"])
        if _appr_owner is True and _los_investment:
            _flag(flags, "2.1", "Occupancy vs Appraisal Mismatch", "warning",
                  f"LOS occupancy (1811) is investment / non-owner ('{occupancy}') but the "
                  f"appraisal reports the subject as Owner-occupied.",
                  "Reconcile occupancy — confirm whether the subject is owner-occupied or an "
                  "investment property.", docs=_appr_docs)
        elif _appr_owner is False and _los_primary:
            _flag(flags, "2.1", "Occupancy vs Appraisal Mismatch", "warning",
                  f"LOS occupancy (1811) is primary / owner-occupied ('{occupancy}') but the "
                  f"appraisal reports the subject as Tenant-occupied.",
                  "Reconcile occupancy — a primary residence should not be tenant-occupied per "
                  "the appraisal.", docs=_appr_docs)
        elif _appr_owner is None:
            _flag(flags, "2.1", "Appraisal Occupancy Inconclusive", "info",
                  f"Appraisal occupancy = '{_appr_occ}' (not Owner/Tenant); confirm against LOS "
                  f"occupancy ('{occupancy}').",
                  "Verify occupancy manually against the appraisal.", docs=_appr_docs)
        else:
            _flag(flags, "2.1", "Occupancy Confirmed vs Appraisal", "info",
                  f"Appraisal occupancy ('{_appr_occ}') is consistent with LOS occupancy "
                  f"('{occupancy}').",
                  "No action needed — occupancy matches the appraisal.", docs=_appr_docs)

    # §11.3 — Appraisal subject address vs the USPS-validated subject address.
    _appr_addr = _appraisal_address(state)
    if _appr_addr:
        _usps = (addr_val.get("normalized") if addr_val else None) or ", ".join(
            p for p in (property_address, property_city, property_state, property_zip) if p)
        if _usps and not _addr_match(_appr_addr, _usps):
            _flag(flags, "2.1", "Appraisal Address vs USPS", "warning",
                  f"Appraisal subject address ('{_appr_addr}') does not match the USPS-validated "
                  f"subject address ('{_usps}').",
                  "Verify the appraisal was completed on the correct subject property.",
                  docs=_relevant_docs(state, "appraisal_property_address", "property_address",
                                      doc_types=["Appraisal (URAR / 1004)"]))
        elif _usps:
            _flag(flags, "2.1", "Appraisal Address Confirmed", "info",
                  f"Appraisal subject address matches the subject property ('{_appr_addr}').",
                  "No action needed — appraisal is on the subject property.")

    # §3.12 — Multi-doc subject-address cross-reference (checklist 03 #12).
    # Beyond the Purchase Contract (above) and Appraisal (§11.3), confirm the
    # subject address on the Tax cert, Evidence of Insurance (HOI), and Title
    # Report each agree with the USPS-validated subject address. (The Flood
    # Certificate address/applicant/zone checks — 12 #2 / 12 #4 — now live in
    # STEP_08 review_flood_hazard_insurance.) Warn-only; never auto-corrected.
    _usps_subject = (addr_val.get("normalized") if addr_val else None) or ", ".join(
        p for p in (property_address, property_city, property_state, property_zip) if p)
    if _usps_subject:
        _addr_sources = [
            ("Tax Certificate", _doc(state, "tax_property_address"),
             ["Tax Summary"], ("tax_property_address",)),
            ("Evidence of Insurance",
             _doc(state, "insured_location") or _doc(state, "hazard_insurance_address"),
             ["Evidence of Insurance"], ("insured_location", "hazard_insurance_address")),
            ("Title Report", _sourced_property_address(state, "title"),
             ["Title Report"], ("property_address",)),
        ]
        for _label, _addr, _dtypes, _keys in _addr_sources:
            if not _addr:
                continue
            if not _addr_match(_addr, _usps_subject):
                _flag(flags, "2.1", f"{_label} Address vs USPS", "warning",
                      f"{_label} subject address ('{_addr}') does not match the USPS-validated "
                      f"subject address ('{_usps_subject}').",
                      f"Verify the {_label.lower()} was issued for the correct subject property.",
                      docs=_relevant_docs(state, *_keys, doc_types=_dtypes))
            else:
                _flag(flags, "2.1", f"{_label} Address Confirmed", "info",
                      f"{_label} subject address matches the subject property ('{_addr}').",
                      "No action needed — address matches the subject property.")

    # ── Rule: ID Not Expired ──────────────────────────────────────────────
    if dl_expiry_doc:
        try:
            for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m-%d-%Y"):
                try:
                    expiry_date = datetime.strptime(str(dl_expiry_doc).strip(), fmt).date()
                    break
                except ValueError:
                    continue
            else:
                expiry_date = None

            if expiry_date and expiry_date < datetime.now(timezone.utc).date():
                _flag(flags, "2.1", "Borrower ID Expired", "warning",
                      f"Driver's License expired on {dl_expiry_doc}.",
                      "Request a valid, non-expired government ID from the borrower.",
                      docs=_relevant_docs(state, "dl_expiry", doc_types=["Driver's License"]))
        except Exception:
            pass

    # ── Rule: Government ID + Type (from Driver's License doc content) ─────
    _write_government_id(state, loan_id, flags,
                         borrower_first_name, borrower_last_name,
                         coborrower_first_name, coborrower_last_name, has_coborrower)

    # ── Rule: Transaction Details ─────────────────────────────────────────
    EXPECTED_LENDER = "All Western Mortgage Inc."
    if not lender:
        _flag(flags, "2.1", "Lender Empty", "warning",
              f"Lender (1264) is blank — must be '{EXPECTED_LENDER}'.",
              f"Update Lender to '{EXPECTED_LENDER}'.")
    elif lender != EXPECTED_LENDER:
        _flag(flags, "2.1", "Lender Incorrect", "warning",
              f"Lender (1264) = '{lender}', expected '{EXPECTED_LENDER}'.",
              f"Update Lender to '{EXPECTED_LENDER}'.")

    if not loan_program:
        _flag(flags, "2.1", "Loan Program Empty", "warning",
              "Loan Program (1401) is blank.",
              "Select the correct Loan Program.")
    else:
        _flag(flags, "2.1", "Loan Program", "info",
              f"Loan Program (1401) = '{loan_program}'.",
              "Verify Loan Program is correct.")

    # Closing Cost Program — cross-check against Loan Purpose
    if closing_cost_program:
        _cc = closing_cost_program.lower()
        _purpose = str(loan_purpose or "").lower()
        if ("purchase" in _cc and "refin" in _purpose) or (("refin" in _cc or "refi" in _cc) and "purchase" in _purpose):
            _flag(flags, "2.1", "Closing Cost Program Mismatch", "warning",
                  f"Closing Cost Program (1785) = '{closing_cost_program}' but Loan Purpose (19) = '{loan_purpose}'. "
                  "Purchase program on a refinance (or vice versa) is a data error.",
                  "Escalate to processor — update Closing Cost Program to match loan purpose.")
        else:
            _flag(flags, "2.1", "Closing Cost Program", "info",
                  f"Closing Cost Program (1785) = '{closing_cost_program}'.",
                  "Verify Closing Cost Program is correct.")
    else:
        _flag(flags, "2.1", "Closing Cost Program Empty", "warning",
              "Closing Cost Program (1785) is blank.",
              "Select the appropriate Closing Cost Program for this loan.")

    if not loan_number:
        _flag(flags, "2.1", "Loan Number Empty", "warning",
              "Loan Number (364) is blank.",
              "Update Loan Number in Borrower Summary.")
    if mers_min:
        _flag(flags, "2.1", "MERS MIN", "info",
              f"MERS MIN (1051) = '{mers_min}'.", "Verify MERS MIN is registered and correct.")
    else:
        _flag(flags, "2.1", "MERS MIN Empty", "warning",
              "MERS MIN (1051) is blank.", "Enter MERS MIN when available.")

    # ── Rule: Loan Info fields (19 / 1811 / 1172 / 420 / 608) ───────────
    _loan_info_presence = {
        "Purpose of Loan (19)":          loan_purpose,
        "Property Will Be / Occupancy (1811)": occupancy,
        "Loan Type (1172)":              loan_type,
        "Lien Position (420)":           lien_position,
        "Amortization Type (608)":       amort_type,
        "Loan Term / Months (4)":        loan_term_months,
        "Term Due In Months (325)":      term_due_in_months,
    }
    for label, val in _loan_info_presence.items():
        if val:
            _flag(flags, "2.1", f"Loan Info — {label}", "info",
                  f"{label} = '{val}'.", "Verify matches loan entity; update if needed.")
        else:
            _flag(flags, "2.1", f"Loan Info — {label} Empty", "warning",
                  f"{label} is blank.", "Consult loan entity and update.")

    # ── Rule: Rates ───────────────────────────────────────────────────────
    if not note_rate:
        _flag(flags, "2.1", "Note Rate Empty", "warning",
              "Note Rate (field 3) is blank.", "Enter the note rate.")
    else:
        _flag(flags, "2.1", "Note Rate", "info",
              f"Note Rate (3) = '{note_rate}'.", "Verify rate is correct.")

    if not qual_rate:
        _flag(flags, "2.1", "Qualifying Rate Empty", "warning",
              "Qualifying Rate (1014) is blank.", "Enter the qualifying rate.")
    if undiscounted_rate:
        _flag(flags, "2.1", "Undiscounted Rate", "info",
              f"Undiscounted Rate (3293) = '{undiscounted_rate}'.", "Verify undiscounted rate.")
    else:
        _flag(flags, "2.1", "Undiscounted Rate Empty", "warning",
              "Undiscounted Rate (3293) is blank.", "Enter the undiscounted rate.")

    # ── Rule: Payments / Income ───────────────────────────────────────────
    if not monthly_payment:
        _flag(flags, "2.1", "Monthly Payment (P&I) Empty", "warning",
              "Monthly Payment / P&I (field 5) is blank.", "Verify loan terms are saved.")
    if not total_monthly_payment:
        _flag(flags, "2.1", "Total Monthly Payment Empty", "warning",
              "Total Monthly Payment (912) is blank.", "Verify total payment is calculated.")
    if not monthly_income:
        _flag(flags, "2.1", "Monthly Income Empty", "warning",
              "Monthly Income (736) is blank.", "Enter borrower monthly income.")

    # ── Rule: Down Payment cross-check ────────────────────────────────────
    down_pct_f  = _parse_amount(down_payment_pct)
    down_amt_f  = _parse_amount(down_payment_amount)
    pp_for_dp   = purchase_price_doc_amount or los_purchase_price_amount
    if down_pct_f and pp_for_dp:
        pct_value = down_pct_f / 100.0 if down_pct_f > 1 else down_pct_f
        expected_dp = round(pp_for_dp * pct_value)
        if down_amt_f:
            diff = abs(down_amt_f - expected_dp)
            if diff > PRICE_TOLERANCE:
                _flag(flags, "2.1", "Down Payment Amount Mismatch", "warning",
                      f"Down Payment % (1771) = {down_payment_pct}% × purchase price "
                      f"${pp_for_dp:,.0f} = ${expected_dp:,.0f}, "
                      f"but Down Payment Amount (1335) = ${down_amt_f:,.0f} (diff: ${diff:,.0f}).",
                      "Verify down payment percentage and amount are consistent.")
        else:
            _flag(flags, "2.1", "Down Payment Amount Empty", "warning",
                  f"Down Payment % (1771) = {down_payment_pct}% but Down Payment Amount (1335) is blank. "
                  f"Expected ≈ ${expected_dp:,.0f}.",
                  "Enter the down payment amount.")
    elif not down_pct_f:
        _flag(flags, "2.1", "Down Payment % Empty", "warning",
              "Down Payment % (1771) is blank.", "Enter the down payment percentage.")

    # ── Rule: Lock / Rate Dates ───────────────────────────────────────────
    _is_locked = str(rate_is_locked or "").strip().lower() in ("y", "yes", "true", "1", "locked")
    _today = datetime.now(timezone.utc).date()
    _today_str = _today.strftime("%m/%d/%Y")

    def _parse_date_str(s):
        if not s or str(s).strip() in ("", "//", "None"):
            return None
        for fmt in ("%m/%d/%Y", "%Y-%m-%d"):
            try:
                return datetime.strptime(str(s).strip(), fmt).date()
            except ValueError:
                continue
        return None

    _lock_dt       = _parse_date_str(lock_date)
    _last_rate_dt  = _parse_date_str(last_rate_set_date)
    _rl_disc_dt    = _parse_date_str(rate_lock_disclosure_date_val)

    if _is_locked:
        if _lock_dt:
            _flag(flags, "2.1", "Lock Date", "info",
                  f"Lock Date (761) = '{lock_date}'. Loan is locked.",
                  "Verify lock date is correct.")
            if _last_rate_dt and _last_rate_dt != _lock_dt:
                _flag(flags, "2.1", "Last Rate Set Date Mismatch", "warning",
                      f"Last Rate Set Date (3253) = '{last_rate_set_date}' but Lock Date (761) = '{lock_date}'. "
                      "For locked loans they should match.",
                      "Update Last Rate Set Date to match Lock Date.")
        else:
            _flag(flags, "2.1", "Lock Date Missing (Locked Loan)", "warning",
                  "Rate Is Locked (2400) = Y but Lock Date (761) is blank.",
                  "Enter the Lock Date.")

        if not lock_days:
            _flag(flags, "2.1", "Lock Period Empty", "warning",
                  "Lock Period / # of Days (432) is blank.",
                  "Enter the lock period in days.")
        if not lock_expires:
            _flag(flags, "2.1", "Lock Expiration Date Empty", "warning",
                  "Lock Expiration Date (762) is blank.",
                  "Enter the lock expiration date.")

        if _rl_disc_dt:
            if _rl_disc_dt != _today:
                _flag(flags, "2.1", "Rate Lock Disclosure Date Not Today", "warning",
                      f"Rate Lock Disclosure Date (3259) = '{rate_lock_disclosure_date_val}' "
                      f"but should be today's date '{_today_str}'.",
                      f"Update Rate Lock Disclosure Date to '{_today_str}'.")
        else:
            _flag(flags, "2.1", "Rate Lock Disclosure Date Empty", "warning",
                  f"Rate Lock Disclosure Date (3259) is blank — must be today '{_today_str}' when locked.",
                  f"Set Rate Lock Disclosure Date to '{_today_str}'.")
    else:
        if _last_rate_dt and _last_rate_dt != _today:
            _flag(flags, "2.1", "Last Rate Set Date Needs Update", "warning",
                  f"Last Rate Set Date (3253) = '{last_rate_set_date}', expected today '{_today_str}' "
                  "(loan is not locked).",
                  f"Update Last Rate Set Date to '{_today_str}'.")
        elif not last_rate_set_date:
            _flag(flags, "2.1", "Last Rate Set Date Empty", "warning",
                  "Last Rate Set Date (3253) is blank.",
                  f"Set to today's date '{_today_str}'.")

    if not est_closing_date_val:
        _flag(flags, "2.1", "Est Closing Date Empty", "warning",
              "Est Closing Date (763) is blank.", "Enter the estimated closing date.")
    if not borrower_est_closing_date_val:
        _flag(flags, "2.1", "Borrower Est Closing Date Empty", "warning",
              "Borrower Est Closing Date (4114) is blank.", "Enter the borrower est closing date.")
    if secondary_registration:
        _flag(flags, "2.1", "Secondary Registration", "info",
              f"Secondary Registration (3941) = '{secondary_registration}'.",
              "Verify secondary registration is correct.")
    else:
        _flag(flags, "2.1", "Secondary Registration Empty", "warning",
              "Secondary Registration (3941) is blank.", "Enter secondary registration if applicable.")

    # ── Build result ──────────────────────────────────────────────────────
    result = {
        "success": True,
        "substep": "2.1",
        "tool": "review_borrower_summary",
        "has_coborrower": has_coborrower,
        "flags_count": len(flags),
        "credit_score_decision": credit_score_decision,
        "credit_reference_number": credit_reference_number,
        "loan_amount": loan_amount,
        "ami_eligibility": ami_eligibility,
        "message": "Review Borrower Summary - Origination completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[REVIEW_BORROWER_SUMMARY] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
