"""run_pre_checks — Tool for substep 1.1: Document Presence Check

Step 1 (STEP_01): Pre-Checks
Phase: INTAKE

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
from datetime import date, datetime, timezone
from typing import Annotated

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _efolder_present, _efolder_bucket, _profile, _relevant_docs

logger = logging.getLogger(__name__)


def _flag(flags: list, substep: str, title: str, severity: str, details: str, suggestion: str) -> None:
    flags.append({
        "substep": substep,
        "title": title,
        "severity": severity,
        "details": details,
        "suggestion": suggestion,
        "resolved": False,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })


@tool
def run_pre_checks(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],
) -> Command:
    """Check eFolder for presence (and signing) of: 1003, Borrower's Cert/Auth,
    State disclosures (e.g. MD Right of Assumption), VOE, Assets, Bank Statement,
    Driver's License (or other ID), ESS, Credit Report, Flood Certificate,
    Hazard Insurance, Title Report, LDP, and existing AUS (Underwriting bucket).
    Flag any missing docs as warnings/critical before proceeding.

    Call this tool during STEP_01 (Pre-Checks) as substep 1.1.
    Reads LOS: property_state, loan_type, appraisal_waiver
    Reads Docs: 1003 URLA, Borrower's Certification and Authorization,
      Underwriting (DU / LP), VOE, Assets, Bank Statement (all copies),
      Driver's License, Estimated Settlement Statement, Credit Report,
      Flood Certificate, Evidence of Hazard Insurance, Title Report, LDP,
      State Disclosure, General Letter of Explanation
    Flags: Missing Required Document (critical/warning), AUS Missing (critical),
      Insufficient Bank Statements (warning), ID Expired (warning),
      State Disclosure Missing (warning), FACT ACT Missing (warning)
    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[RUN_PRE_CHECKS] Starting for loan {str(loan_id)[:8]}...")

    flags = []

    # ── LOS fields ──
    loan_type = _los(state, "loan_type") or _profile(state, "loan_type") or ""
    property_state = _los(state, "property_state") or _profile(state, "state") or ""

    # ── Doc fields ──
    # Presence: use _efolder_present (checks efolder_documents directly, not extracted value)
    # so a doc is only "missing" if it's truly absent from the eFolder — not if a field
    # inside it couldn't be extracted (e.g. urla_signed = None despite doc existing).
    urla_present         = _efolder_present(state, "1003 URLA")
    # urla_signed reserved for future signature check
    _doc(state, "urla_signed")
    bca_present          = _efolder_present(state, "Borrower's Certification & Authorization")
    aus_run_date         = _doc(state, "aus_run_date")
    aus_collateral_relief = _doc(state, "collateral_rw_relief")
    aus_income_raw_relief = _doc(state, "income_rw_relief")
    voe_present          = _efolder_present(state, "VOE - non service provider")
    paystubs_present     = _efolder_present(state, "Paystubs")
    assets_present       = _efolder_present(state, "Assets")
    bank_statement_present = _efolder_present(state, "Bank Statement")
    bank_statement_months = _doc(state, "bank_statement_months")
    dl_present           = _efolder_present(state, "Driver's License")
    dl_expiry            = _doc(state, "dl_expiry")
    ess_present          = _efolder_present(state, "Estimated Settlement Statement")
    credit_report_present = _efolder_present(state, "Credit Report")
    fact_act_present     = _doc(state, "fact_act_present")   # field inside credit report
    flood_cert_present   = _efolder_present(state, "Flood Certificate")
    hazard_insurance_present = _efolder_present(state, "Evidence of Hazard Insurance") or \
                               _efolder_present(state, "Evidence of Insurance")
    title_report_present = _efolder_present(state, "Title Report")
    ldp_present          = _efolder_present(state, "LDP")
    fraudguard_present   = _efolder_present(state, "Fraud")
    tax_summary_present  = _efolder_present(state, "Tax Summary")
    # MD eDisclosure signed flags (each is True/False/None)
    md_rescind_signed      = _doc(state, "md_rescind_signed")
    md_dual_cap_signed     = _doc(state, "md_dual_cap_signed")
    md_counseling_signed   = _doc(state, "md_counseling_signed")
    md_assumption_signed   = _doc(state, "md_assumption_signed")
    md_ins_provider_signed = _doc(state, "md_ins_provider_signed")
    md_settlement_signed   = _doc(state, "md_settlement_signed")
    _md_disc_flags = [md_rescind_signed, md_dual_cap_signed, md_counseling_signed,
                      md_assumption_signed, md_ins_provider_signed, md_settlement_signed]
    # At least one doc present in eFolder (any non-None value)
    _md_any_present = any(v is not None for v in _md_disc_flags)
    # At least one doc signed (True)
    _md_any_signed  = any(v is True for v in _md_disc_flags)

    def _bucket_label(doc_name: str) -> str:
        """Return '(eFolder bucket: X)' if the bucket name differs from the canonical doc name."""
        bucket = _efolder_bucket(state, doc_name)
        return f" (eFolder bucket: '{bucket}')" if bucket != doc_name else ""

    # ── Rule: AUS Required (critical — Step 10 orders depend on it) ──
    if not aus_run_date:
        _flag(flags, "1.1", "AUS Missing", "critical",
              f"No Underwriting (DU/LP) document found in eFolder{_bucket_label('Underwriting')}.",
              "Run AUS or retrieve existing results before ordering.")

    # ── Rule: Required Docs Present ──
    # Critical = downstream steps cannot run without these
    critical_docs = {
        "1003 URLA": urla_present,
        "Borrower's Certification & Authorization": bca_present,
        "Credit Report": credit_report_present,
    }
    # Warning = submission will be incomplete but earlier steps can proceed
    warning_docs = {
        "Assets": assets_present,
        "Estimated Settlement Statement": ess_present,
        "Flood Certificate": flood_cert_present,
        "Evidence of Hazard Insurance": hazard_insurance_present,
        "Title Report": title_report_present,
        "LDP": ldp_present,
        "Fraud": fraudguard_present,
        "Tax Summary": tax_summary_present,
    }

    for doc_name, present in critical_docs.items():
        if not present:
            _flag(flags, "1.1", "Missing Required Document", "critical",
                  f"{doc_name} not found in eFolder{_bucket_label(doc_name)}.",
                  "Locate or request the missing document before proceeding.")

    for doc_name, present in warning_docs.items():
        if not present:
            _flag(flags, "1.1", "Missing Required Document", "warning",
                  f"{doc_name} not found in eFolder{_bucket_label(doc_name)}.",
                  "Locate or request the missing document before proceeding.")

    # ── Rule: Govt ID (Driver's License) — info non-blocker ──
    if not dl_present:
        _dl_label = _bucket_label("Driver's License")
        _flag(flags, "1.1", "Govt ID Not Yet Uploaded", "info",
              f"Driver's License not found in eFolder{_dl_label}. "
              "Not required at this stage but needed before submission.",
              "Upload borrower's government-issued ID to the eFolder when available.")

    # ── Rule: Income Docs (VOE and/or Paystubs) ──
    # At least one income verification doc must be present
    _voe_label = _bucket_label("VOE - non service provider")
    if not voe_present and not paystubs_present:
        _flag(flags, "1.1", "Income Documents Missing", "warning",
              f"Neither VOE{_voe_label} nor paystubs found in eFolder.",
              "Request VOE or most recent paystubs from borrower for income verification.")
    elif not voe_present:
        _flag(flags, "1.1", "VOE Missing", "info",
              f"No VOE found{_voe_label} — paystubs are present but VOE is preferred for salaried borrowers.",
              "Request VOE from employer if borrower is W-2 employee.")
    elif not paystubs_present:
        _flag(flags, "1.1", "Paystubs Missing", "info",
              "No paystubs found — VOE is present. Paystubs required alongside VOE for most loan types.",
              "Request most recent 30-day paystubs from borrower.")

    # FACT ACT lives inside the Credit Report package
    if credit_report_present and not fact_act_present:
        _flag(flags, "1.1", "FACT ACT Disclosure Missing", "warning",
              "FACT ACT disclosure form not found within the credit report package.",
              "Confirm FACT ACT form is included in the credit report.")

    # ── Rule: Bank Statement Recency ──
    # Guardrail: distinguish "couldn't determine coverage" (months not extracted) from a
    # genuine "0 months". A None month count means extraction didn't yield a statement period
    # (e.g. doc-type/schema mismatch upstream) — do NOT coerce that to 0 and cry "Insufficient".
    required_months = 1 if str(loan_type).upper() == "FHA" else 2
    _bank_label = _bucket_label("Bank Statement")

    if bank_statement_months is None:
        if bank_statement_present:
            _flag(flags, "1.1", "Bank Statement Coverage Unverifiable", "warning",
                  f"Bank Statement document is present in eFolder{_bank_label} but the number of "
                  f"months / statement period could not be extracted ({required_months} month(s) "
                  f"required for {loan_type or 'this loan type'}).",
                  "Manually verify the statement covers the required period, or re-run extraction "
                  "(possible doc-type/schema name mismatch — see docs/EFOLDER_EXTRACTION.md).")
        else:
            _flag(flags, "1.1", "Bank Statements Missing", "warning",
                  f"No Bank Statement document found in eFolder{_bank_label} "
                  f"({required_months} month(s) required for {loan_type or 'this loan type'}).",
                  "Request bank statements from borrower.")
    else:
        try:
            bank_months = int(bank_statement_months)
        except (TypeError, ValueError):
            bank_months = 0

        if bank_months < required_months:
            _flag(flags, "1.1", "Insufficient Bank Statements", "warning",
                  f"Found {bank_months} month(s); {required_months} required for {loan_type or 'this loan type'}.",
                  "Request additional bank statements from borrower.")

    # ── Rule: DL Not Expired ──
    # Accept the common license formats (MM/DD/YYYY is what most state IDs use)
    # in addition to ISO, so a populated expiry is not misread as "unknown".
    dl_expiry_date = None
    if dl_expiry:
        for _fmt in ("%Y-%m-%d", "%m/%d/%Y", "%m-%d-%Y", "%m/%d/%y"):
            try:
                dl_expiry_date = datetime.strptime(str(dl_expiry).strip(), _fmt).date()
                break
            except ValueError:
                continue

    if dl_expiry_date is not None and dl_expiry_date < date.today():
        _flag(flags, "1.1", "ID Expired", "warning",
              f"Driver's License expired on {dl_expiry}.",
              "Request a valid, non-expired government ID from borrower.")
    elif dl_present and dl_expiry_date is None:
        _flag(flags, "1.1", "ID Expiry Unknown", "warning",
              "Driver's License present but expiry date could not be read.",
              "Manually verify ID expiration date.")

    # ── Rule: State Disclosures Signed ──
    if property_state.upper() == "MD":
        if _md_any_signed:
            pass  # At least one MD eDisclosure is signed — pass
        elif _md_any_present:
            _flag(flags, "1.1", "MD State Disclosure Not Signed", "warning",
                  "MD eDisclosure documents found in eFolder but none are signed by the borrower.",
                  "Confirm borrower has eSigned the required MD disclosures.")
        else:
            _flag(flags, "1.1", "MD State Disclosures Missing", "warning",
                  "No Maryland eDisclosure documents found in eFolder.",
                  "Add required MD disclosures (e.g. MD Notice Regarding Right for Assumption) "
                  "before submission.")

    # ── Info: Documents Present in eFolder ──
    # Positive complement of the "Missing Required Document" flags above. Built
    # from the exact presence booleans 1.1 already computes (not required_docs.json),
    # so it stays symmetric with the per-doc missing flags.
    checked_present = {
        "1003 URLA": urla_present,
        "Borrower's Certification & Authorization": bca_present,
        "Credit Report": credit_report_present,
        "Underwriting (AUS)": bool(aus_run_date),
        "VOE - non service provider": voe_present,
        "Paystubs": paystubs_present,
        "Assets": assets_present,
        "Driver's License": dl_present,
        "Estimated Settlement Statement": ess_present,
        "Flood Certificate": flood_cert_present,
        "Evidence of Hazard Insurance": hazard_insurance_present,
        "Title Report": title_report_present,
        "LDP": ldp_present,
        "Fraud": fraudguard_present,
        "Tax Summary": tax_summary_present,
    }
    if property_state.upper() == "MD":
        checked_present["MD State Disclosures"] = _md_any_present

    present_docs = [name for name, ok in checked_present.items() if ok]
    if present_docs:
        # Canonical eFolder bucket names for coordinate refs (a few checklist
        # labels differ from the bucket the file actually lives in).
        _ref_names = []
        for name in present_docs:
            if name == "Underwriting (AUS)":
                _ref_names.append("Underwriting")
            elif name == "Evidence of Hazard Insurance":
                _ref_names.extend(["Evidence of Hazard Insurance", "Evidence of Insurance"])
            elif name == "MD State Disclosures":
                continue  # spans multiple buckets — no single coordinate
            else:
                _ref_names.append(name)

        _present_flag = {
            "substep": "1.1",
            "title": "Documents Present in eFolder",
            "severity": "info",
            "details": (
                f"{len(present_docs)} of {len(checked_present)} checked document(s) "
                f"found in eFolder: {', '.join(present_docs)}."
            ),
            "suggestion": "No action needed.",
            "resolved": True,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        _refs = _relevant_docs(state, doc_types=_ref_names)
        if _refs:
            _present_flag["relevant_documents"] = _refs
        flags.append(_present_flag)

    # ── Build result ──
    critical_flags = [f for f in flags if f["severity"] == "critical"]
    result = {
        "success": True,
        "substep": "1.1",
        "tool": "run_pre_checks",
        "flags_count": len(flags),
        "critical_count": len(critical_flags),
        "aus_collateral_relief": aus_collateral_relief,
        "aus_income_raw_relief": aus_income_raw_relief,
        "message": (
            "Document Presence Check completed"
            + (f" with {len(flags)} flag(s) ({len(critical_flags)} critical)" if flags else " — all docs present")
        ),
    }

    logger.info(f"[RUN_PRE_CHECKS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = state.get("flags", []) + flags

    return Command(update=update)
