"""run_freddie_aus — Tool for substep 14.2: Run Freddie Mac LP

Step 14 (STEP_14): Run Fresh AUS
Phase: PREP

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def run_freddie_aus(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Submit loan to Freddie Mac Loan Product Advisor (LP). Record decision (Accept, Caution, Ineligible, etc.) and upload findings PDF to the Underwriting eFolder bucket.


    Call this tool during STEP_14 (Run Fresh AUS) as substep 14.2.    Reads LOS: loan_type    Flags: Freddie LP Not Accept (warning), Freddie LP Findings Not Uploaded (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[RUN_FREDDIE_AUS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_type = _los(state, "loan_type")  # Field 1172: Mortgage Type    # ── Rule: Freddie LP Submission ──
    # Submit to Freddie Mac LP via Encompass. Record decision and upload findings. If not Accept, flag the decision for processor review.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Freddie LP Not Accept ──
    # Condition: LP decision is not Accept
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "14.2",
    #         "title": "Freddie LP Not Accept",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Review LP findings with LO and underwriter before proceeding",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Freddie LP Findings Not Uploaded ──
    # Condition: Freddie LP findings PDF not found in UW bucket
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "14.2",
    #         "title": "Freddie LP Findings Not Uploaded",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Upload Freddie LP findings PDF to eFolder",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "14.2",
        "tool": "run_freddie_aus",
        "flags_count": len(flags),
        "message": "Run Freddie Mac LP completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[RUN_FREDDIE_AUS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
