"""run_pre_checks — Tool for substep 1.1: Document Presence Check

Step 1 (STEP_01): Pre-Checks
Phase: INTAKE

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: true
"""

import json
import logging
from datetime import date, datetime, timezone
from typing import Annotated

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


def _flag(flags: list, substep: str, title: str, severity: str, details: str, suggestion: str) -> None:
    flags.append({
        "substep": substep,
        "title": title,
        "severity": severity,
        "details": details,
        "suggestion": suggestion,
        "resolved": False,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })


@tool
def run_pre_checks(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],
) -> Command:
    """Check eFolder for presence (and signing) of: 1003, Borrower's Cert/Auth,
    State disclosures (e.g. MD Right of Assumption), VOE, Assets, Bank Statement,
    VOD, Driver's License (or other ID), ESS, Credit Report, Flood Certificate,
    Hazard Insurance, Title Report, LDP, and existing AUS (Underwriting bucket).
    Flag any missing docs as warnings/critical before proceeding.

    Call this tool during STEP_01 (Pre-Checks) as substep 1.1.
    Reads LOS: property_state, loan_type, appraisal_waiver
    Reads Docs: 1003 URLA, Borrower's Certification and Authorization,
      Underwriting (DU / LP), VOE, Assets, Bank Statement (all copies),
      VOD, Driver's License, Estimated Settlement Statement, Credit Report,
      Flood Certificate, Evidence of Hazard Insurance, Title Report, LDP,
      State Disclosure, General Letter of Explanation
    Flags: Missing Required Document (critical/warning), AUS Missing (critical),
      Insufficient Bank Statements (warning), ID Expired (warning),
      State Disclosure Missing (warning), FACT ACT Missing (warning)
    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[RUN_PRE_CHECKS] Starting for loan {str(loan_id)[:8]}...")

    flags = []

    # ── LOS fields ──
    loan_type = _los(state, "loan_type") or _profile(state, "loan_type") or ""
    property_state = _los(state, "property_state") or _profile(state, "state") or ""

    # ── Doc fields ──
    urla_signed          = _doc(state, "urla_signed")
    bca_present          = _doc(state, "bca_present")
    aus_run_date         = _doc(state, "aus_run_date")
    aus_collateral_relief = _doc(state, "aus_collateral_relief")
    aus_income_raw_relief = _doc(state, "aus_income_raw_relief")
    voe_present          = _doc(state, "voe_present")
    assets_present       = _doc(state, "assets_present")
    bank_statement_months = _doc(state, "bank_statement_months")
    vod_present          = _doc(state, "vod_present")
    dl_present           = _doc(state, "dl_present")
    dl_expiry            = _doc(state, "dl_expiry")
    ess_present          = _doc(state, "ess_present")
    credit_report_present = _doc(state, "credit_report_present")
    fact_act_present     = _doc(state, "fact_act_present")
    flood_cert_present   = _doc(state, "flood_cert_present")
    hazard_insurance_present = _doc(state, "hazard_insurance_present")
    title_report_present = _doc(state, "title_report_present")
    ldp_present          = _doc(state, "ldp_present")
    state_disclosure_present = _doc(state, "state_disclosure_present")

    # ── Rule: AUS Required (critical — Step 10 orders depend on it) ──
    if not aus_run_date:
        _flag(flags, "1.1", "AUS Missing", "critical",
              "No Underwriting (DU/LP) document found in eFolder.",
              "Run AUS or retrieve existing results before ordering.")

    # ── Rule: Required Docs Present ──
    # Critical = downstream steps cannot run without these
    critical_docs = {
        "1003 URLA": urla_signed,
        "Borrower's Certification and Authorization": bca_present,
        "Credit Report": credit_report_present,
    }
    # Warning = submission will be incomplete but earlier steps can proceed
    warning_docs = {
        "VOE": voe_present,
        "Assets": assets_present,
        "VOD": vod_present,
        "Driver's License": dl_present,
        "Estimated Settlement Statement": ess_present,
        "Flood Certificate": flood_cert_present,
        "Evidence of Hazard Insurance": hazard_insurance_present,
        "Title Report": title_report_present,
        "LDP": ldp_present,
    }

    for doc_name, present in critical_docs.items():
        if not present:
            _flag(flags, "1.1", "Missing Required Document", "critical",
                  f"{doc_name} not found in eFolder.",
                  "Locate or request the missing document before proceeding.")

    for doc_name, present in warning_docs.items():
        if not present:
            _flag(flags, "1.1", "Missing Required Document", "warning",
                  f"{doc_name} not found in eFolder.",
                  "Locate or request the missing document before proceeding.")

    # FACT ACT lives inside the Credit Report package
    if credit_report_present and not fact_act_present:
        _flag(flags, "1.1", "FACT ACT Disclosure Missing", "warning",
              "FACT ACT disclosure form not found within the credit report package.",
              "Confirm FACT ACT form is included in the credit report.")

    # ── Rule: Bank Statement Recency ──
    required_months = 1 if str(loan_type).upper() == "FHA" else 2
    try:
        bank_months = int(bank_statement_months) if bank_statement_months is not None else 0
    except (TypeError, ValueError):
        bank_months = 0

    if bank_months < required_months:
        _flag(flags, "1.1", "Insufficient Bank Statements", "warning",
              f"Found {bank_months} month(s); {required_months} required for {loan_type or 'this loan type'}.",
              "Request additional bank statements from borrower.")

    # ── Rule: DL Not Expired ──
    dl_expiry_date = None
    if dl_expiry:
        try:
            dl_expiry_date = datetime.strptime(str(dl_expiry), "%Y-%m-%d").date()
        except ValueError:
            pass

    if dl_expiry_date is not None and dl_expiry_date < date.today():
        _flag(flags, "1.1", "ID Expired", "warning",
              f"Driver's License expired on {dl_expiry}.",
              "Request a valid, non-expired government ID from borrower.")
    elif dl_present and dl_expiry_date is None:
        _flag(flags, "1.1", "ID Expiry Unknown", "warning",
              "Driver's License present but expiry date could not be read.",
              "Manually verify ID expiration date.")

    # ── Rule Modifier: MD Right of Assumption ──
    if property_state.upper() == "MD":
        if not state_disclosure_present:
            _flag(flags, "1.1", "MD Right of Assumption Disclosure Missing", "warning",
                  "Maryland requires the 'Notice Regarding Right for Assumption Under "
                  "Certain Circumstances' disclosure.",
                  "Add MD disclosure before submission.")
    elif not state_disclosure_present:
        _flag(flags, "1.1", "State Disclosure Missing", "warning",
              f"State-specific disclosure not found for {property_state or 'this state'}.",
              "Locate and add the required state disclosure.")

    # ── Build result ──
    critical_flags = [f for f in flags if f["severity"] == "critical"]
    result = {
        "success": True,
        "substep": "1.1",
        "tool": "run_pre_checks",
        "flags_count": len(flags),
        "critical_count": len(critical_flags),
        "aus_collateral_relief": aus_collateral_relief,
        "aus_income_raw_relief": aus_income_raw_relief,
        "message": (
            "Document Presence Check completed"
            + (f" with {len(flags)} flag(s) ({len(critical_flags)} critical)" if flags else " — all docs present")
        ),
    }

    logger.info(f"[RUN_PRE_CHECKS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = state.get("flags", []) + flags

    return Command(update=update)
