"""run_additional_services — Tool for substep 12.1: Run Ocrolus and Income Calc

Step 12 (STEP_12): Order Additional Services
Phase: PREP

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def run_additional_services(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Trigger Ocrolus run to process income documents (paystubs, W2s, tax returns). After Ocrolus completes, generate the Income Calc (1084 worksheets etc.). Save Income Calc PDF back to the Income Calc eFolder bucket.


    Call this tool during STEP_12 (Order Additional Services) as substep 12.1.    Reads LOS: loan_type, base_monthly_income    Reads Docs: Paystubs (all copies), W2 (all copies), Income Calc    Flags: Ocrolus Run Failed (warning), Income Calc Not Generated (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[RUN_ADDITIONAL_SERVICES] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_type = _los(state, "loan_type")  # Field 1172: Mortgage Type    base_monthly_income = _los(state, "base_monthly_income")  # Field 1072: Gross Monthly Income - Base    # ── Read Doc Fields ──    # From: Paystubs (ALL COPIES)    paystub_ytd_doc = _doc(state, "paystub_ytd")    paystub_pay_period_doc = _doc(state, "paystub_pay_period")    # From: W2 (ALL COPIES)    w2_wages_doc = _doc(state, "w2_wages")    # From: Income Calc    income_calc_monthly_doc = _doc(state, "income_calc_monthly")    income_calc_run_date_doc = _doc(state, "income_calc_run_date")    # ── Rule: Ocrolus Run Triggers Income Calc ──
    # Run Ocrolus via the income ordering service. After completion, trigger Income Calc generation. Save Income Calc to eFolder Income Calc bucket.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Ocrolus Run Failed ──
    # Condition: Ocrolus run returned an error or did not complete
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "12.1",
    #         "title": "Ocrolus Run Failed",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Retry Ocrolus or manually calculate income",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Income Calc Not Generated ──
    # Condition: Income Calc document not found in eFolder after run
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "12.1",
    #         "title": "Income Calc Not Generated",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Manually trigger Income Calc generation and save to eFolder",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "12.1",
        "tool": "run_additional_services",
        "flags_count": len(flags),
        "message": "Run Ocrolus and Income Calc completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[RUN_ADDITIONAL_SERVICES] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
