"""run_fannie_aus — Tool for substep 14.1: Run Fannie Mae DU

Step 14 (STEP_14): Run Fresh AUS
Phase: PREP

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def run_fannie_aus(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Submit loan to Fannie Mae Desktop Underwriter (DU). Record the decision (Approve/Eligible, Refer, Refer with Caution, etc.) and upload findings PDF to the Underwriting eFolder bucket.


    Call this tool during STEP_14 (Run Fresh AUS) as substep 14.1.    Reads LOS: loan_type    Flags: Fannie DU Not Approve/Eligible (warning), Fannie DU Findings Not Uploaded (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[RUN_FANNIE_AUS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_type = _los(state, "loan_type")  # Field 1172: Mortgage Type    # ── Rule: Fannie DU Submission ──
    # Submit to Fannie Mae DU via Encompass. Record decision and upload findings. If not Approve/Eligible, flag the decision for processor review.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Fannie DU Not Approve/Eligible ──
    # Condition: DU decision is not Approve/Eligible
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "14.1",
    #         "title": "Fannie DU Not Approve/Eligible",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Review findings with LO and underwriter before proceeding",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Fannie DU Findings Not Uploaded ──
    # Condition: Fannie DU findings PDF not found in UW bucket
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "14.1",
    #         "title": "Fannie DU Findings Not Uploaded",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Upload Fannie DU findings PDF to eFolder",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "14.1",
        "tool": "run_fannie_aus",
        "flags_count": len(flags),
        "message": "Run Fannie Mae DU completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[RUN_FANNIE_AUS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
