"""run_pre_checks — Tool for substep 1.1: Document Presence Check

Step 1 (STEP_01): Pre-Checks
Phase: INTAKE

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def run_pre_checks(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Check eFolder for presence (and signing) of: 1003, Borrower's Cert/Auth, State disclosures (e.g. MD Right of Assumption), VOE, Assets, Bank Statement, VOD, Driver's License (or other ID), ESS, and existing AUS (Underwriting bucket). Flag any missing docs as warnings/critical before proceeding.


    Call this tool during STEP_01 (Pre-Checks) as substep 1.1.    Reads LOS: property_state, loan_type, appraisal_waiver    Reads Docs: 1003 URLA, Borrower's Certification and Authorization, Underwriting (DU / LP), VOE, Assets, Bank Statement (all copies), VOD, Driver's License, Estimated Settlement Statement    Flags: Missing Required Document (critical), AUS Missing (critical), Insufficient Bank Statements (warning), ID Expired (warning), State Disclosure Missing (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[RUN_PRE_CHECKS] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    property_state = _los(state, "property_state")  # Field 14: Property State    loan_type = _los(state, "loan_type")  # Field 1172: Mortgage Type    appraisal_waiver = _los(state, "appraisal_waiver")  # Field CX.APPRAISAL.WAIVER: Appraisal Waiver    # ── Read Doc Fields ──    # From: 1003 URLA    urla_signed_doc = _doc(state, "urla_signed")    # From: Borrower's Certification and Authorization    bca_present_doc = _doc(state, "bca_present")    # From: Underwriting (DU / LP)    aus_collateral_relief_doc = _doc(state, "aus_collateral_relief")    aus_income_raw_relief_doc = _doc(state, "aus_income_raw_relief")    aus_run_date_doc = _doc(state, "aus_run_date")    # From: VOE    voe_present_doc = _doc(state, "voe_present")    # From: Assets    assets_present_doc = _doc(state, "assets_present")    # From: Bank Statement (ALL COPIES)    bank_statement_months_doc = _doc(state, "bank_statement_months")    bank_statement_dates_doc = _doc(state, "bank_statement_dates")    # From: VOD    vod_present_doc = _doc(state, "vod_present")    # From: Driver's License    dl_present_doc = _doc(state, "dl_present")    dl_expiry_doc = _doc(state, "dl_expiry")    # From: Estimated Settlement Statement    ess_present_doc = _doc(state, "ess_present")    # ── Rule: Required Docs Present ──
    # All listed docs must exist in eFolder. Flag each missing one as warning or critical based on downstream dependency severity.
    # 
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Rule: AUS Required ──
    # Existing AUS (Underwriting bucket) must be present. If missing, flag as critical — orders at Step 10 depend on AUS findings.
    # 
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Rule: Bank Statement Recency ──
    # If Conventional, require 2 months of bank statements. If FHA, require 1 month. Flag if fewer than required months are present.
    # 
    # Type: value_check    # Check: bank_statement_months >= required_months_by_loan_type    # TODO: Implement this rule
    pass

    # ── Rule: DL Not Expired ──
    # Driver's License expiry must be >= today.
    # Type: value_check    # Check: dl_expiry >= today    # TODO: Implement this rule
    pass

    # ── Flag: Missing Required Document ──
    # Condition: Any of the required documents is absent from the eFolder
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "1.1",
    #         "title": "Missing Required Document",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Locate or request the missing document before proceeding",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: AUS Missing ──
    # Condition: No Underwriting (DU/LP) document found in eFolder
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "1.1",
    #         "title": "AUS Missing",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Run AUS or retrieve existing results before ordering",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Insufficient Bank Statements ──
    # Condition: Fewer bank statement months than required for loan type
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "1.1",
    #         "title": "Insufficient Bank Statements",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request additional statements from borrower",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: ID Expired ──
    # Condition: Driver's License expiration date is before today
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "1.1",
    #         "title": "ID Expired",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Request a valid, non-expired government ID from borrower",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: State Disclosure Missing ──
    # Condition: State-specific disclosure document not found in eFolder
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "1.1",
    #         "title": "State Disclosure Missing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Locate and add the required state disclosure",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Rule Modifiers (loan profile conditions) ──
    _lp = state.get("loan_profile", {})
    if _lp.get("state") == "MD":  # Maryland requires the "Notice Regarding Right for...
        # ADD: Maryland requires the "Notice Regarding Right for Assumption Under Certain Circumstances" disclosure. Flag if missing. [notes.txt:14]
        # Flag: MD Right of Assumption Disclosure Missing (warning)
        # Condition: MD Right of Assumption notice not found in eFolder
        # TODO: Add modifier flag condition
        # if <condition>:
        #     flags.append({
        #         "substep": "1.1",
        #         "title": "MD Right of Assumption Disclosure Missing",
        #         "severity": "warning",
        #         "details": "",
        #         "suggestion": "Add MD disclosure before submission",
        #         "resolved": False,
        #         "timestamp": datetime.now(timezone.utc).isoformat(),
        #         "modifier_source": "notes.txt:14",
        #     })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "1.1",
        "tool": "run_pre_checks",
        "flags_count": len(flags),
        "message": "Document Presence Check completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[RUN_PRE_CHECKS] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
