"""send_lock_desk_email — Tool for substep 18.1: Lock Desk Email (if locked + address change)

Step 18 (STEP_18): Notifications
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def send_lock_desk_email(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Send email to Lock Desk if the loan is locked AND an address change was discovered at Step 2 (property address mismatch flag). Uses email template from recipients.json (Almas Younis, Ash Desai).


    Call this tool during STEP_18 (Notifications) as substep 18.1.    Reads LOS: loan_locked, lock_expiration    Flags: Lock Desk Email Not Sent (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[SEND_LOCK_DESK_EMAIL] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    loan_locked = _los(state, "loan_locked")  # Field CX.LOAN.LOCKED: Loan Locked Status    lock_expiration = _los(state, "lock_expiration")  # Field 762: Lock Expiration Date    # ── Rule: Send Only If Locked and Address Changed ──
    # If loan_locked == True AND address_change_flag raised at Step 2: send Lock Desk notification email. Otherwise, dynamically skip.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Lock Desk Email Not Sent ──
    # Condition: Locked loan with address change but Lock Desk email not sent
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "18.1",
    #         "title": "Lock Desk Email Not Sent",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Manually send Lock Desk email with updated property address",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "18.1",
        "tool": "send_lock_desk_email",
        "flags_count": len(flags),
        "message": "Lock Desk Email (if locked + address change) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[SEND_LOCK_DESK_EMAIL] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
