"""send_title_order_email — Tool for substep 10.3: File Contacts and Title Order Email

Step 10 (STEP_10): Orders
Phase: ORDERS

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def send_title_order_email(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Update File Contacts in Encompass (Title Company, Appraiser, etc.) and send the title order email to the title company. Use Ash's email template. Recipients: Joe Salem (cc Almas Younis, Ash Desai) per recipients.json.


    Call this tool during STEP_10 (Orders) as substep 10.3.    Reads LOS: title_company_name, title_company_email, property_address, borrower_last_name    Flags: Title Company Contact Missing (warning), Title Order Email Not Sent (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[SEND_TITLE_ORDER_EMAIL] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    title_company_name = _los(state, "title_company_name")  # Field CX.TITLE.COMPANY.NAME: Title Company Name    title_company_email = _los(state, "title_company_email")  # Field CX.TITLE.COMPANY.EMAIL: Title Company Email    property_address = _los(state, "property_address")  # Field 11: Property Address    borrower_last_name = _los(state, "borrower_last_name")  # Field 4002: Borrower Last Name    # ── Rule: File Contacts Updated ──
    # Title company name and email must be populated before sending order email.
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Flag: Title Company Contact Missing ──
    # Condition: Title company name or email not populated in File Contacts
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "10.3",
    #         "title": "Title Company Contact Missing",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Populate title company contact information before sending email",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Title Order Email Not Sent ──
    # Condition: Title order email was not sent
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "10.3",
    #         "title": "Title Order Email Not Sent",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Send title order email to the title company",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "10.3",
        "tool": "send_title_order_email",
        "flags_count": len(flags),
        "message": "File Contacts and Title Order Email completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[SEND_TITLE_ORDER_EMAIL] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
