"""send_emd_email — Tool for substep 18.3: EMD Email to Realtor (if EMD missing or mismatch)

Step 18 (STEP_18): Notifications
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def send_emd_email(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Send email to the Realtor requesting EMD check copy if EMD missing or amount mismatch was flagged at Step 5. Realtor is payable-to entity from Purchase Contract. Copy recipients per recipients.json.


    Call this tool during STEP_18 (Notifications) as substep 18.3.    Reads LOS: realtor_email, emd_amount    Reads Docs: Purchase Agreement    Flags: EMD Email Not Sent (info)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[SEND_EMD_EMAIL] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    realtor_email = _los(state, "realtor_email")  # Field CX.REALTOR.EMAIL: Realtor Email    emd_amount = _los(state, "emd_amount")  # Field 186: EMD Amount    # ── Read Doc Fields ──    # From: Purchase Agreement    emd_payable_to_doc = _doc(state, "emd_payable_to")    emd_amount_pa_doc = _doc(state, "emd_amount_pa")    # ── Rule: Send Only If EMD Flag Raised at Step 5 ──
    # If EMD-missing or EMD-mismatch flag is in state["flags"] from Step 5: send Realtor email requesting EMD check copy. Otherwise, dynamically skip.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: EMD Email Not Sent ──
    # Condition: EMD flag raised but Realtor email not sent
    # Severity: info
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "18.3",
    #         "title": "EMD Email Not Sent",
    #         "severity": "info",
    #         "details": "",
    #         "suggestion": "Manually email Realtor to request EMD check copy",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "18.3",
        "tool": "send_emd_email",
        "flags_count": len(flags),
        "message": "EMD Email to Realtor (if EMD missing or mismatch) completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[SEND_EMD_EMAIL] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
