"""update_transmittal_summary — Tool for substep 9.1: Update Transmittal Summary

Step 9 (STEP_09): Transmittal Summary
Phase: FORM_UPDATES

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def update_transmittal_summary(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Populate the 1008 Transmittal Summary: project type, project ID, project name, qualifying rate. If condo, run Freddie Mac Condo Project Advisor lookup and populate project type (Warrantable / Non-Warrantable / Established). Verify note rate == qualifying rate.


    Call this tool during STEP_09 (Transmittal Summary) as substep 9.1.    Reads LOS: property_type, condo_project_type, condo_project_name, condo_project_id, note_rate, qualifying_rate    Flags: Note Rate vs Qualifying Rate Mismatch (warning), Condo Project Fields Not Populated (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[UPDATE_TRANSMITTAL_SUMMARY] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    property_type = _los(state, "property_type")  # Field 1041: Property Type    condo_project_type = _los(state, "condo_project_type")  # Field 1065: Condo Project Type    condo_project_name = _los(state, "condo_project_name")  # Field CX.CONDO.PROJECT.NAME: Condo Project Name    condo_project_id = _los(state, "condo_project_id")  # Field CX.CONDO.PROJECT.ID: Condo Project ID    note_rate = _los(state, "note_rate")  # Field 3: Note Rate    qualifying_rate = _los(state, "qualifying_rate")  # Field 799: Qualifying Rate    # ── Rule: Note Rate Equals Qualifying Rate ──
    # Note rate must match the qualifying rate on the Transmittal Summary.
    # Type: field_comparison    # Check: note_rate == qualifying_rate    # TODO: Implement this rule
    pass

    # ── Flag: Note Rate vs Qualifying Rate Mismatch ──
    # Condition: Note rate doesn't match qualifying rate on Transmittal Summary
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "9.1",
    #         "title": "Note Rate vs Qualifying Rate Mismatch",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Reconcile rates — qualifying rate should equal note rate for fixed-rate loans",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Condo Project Fields Not Populated ──
    # Condition: Condo property but project type/name/ID not populated
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "9.1",
    #         "title": "Condo Project Fields Not Populated",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Run Freddie Mac Condo Project Advisor to populate project details",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Rule Modifiers (loan profile conditions) ──
    _lp = state.get("loan_profile", {})
    if _lp.get("loan_type") == "Conventional":  # For Conventional/Condo: run Freddie Mac Condo Project...
        # ADD: For Conventional/Condo: run Freddie Mac Condo Project Advisor lookup to determine Warrantable / Non-Warrantable / Established / etc. [notes.txt]
        # Rule: Condo Project Advisor Lookup — Run Freddie Mac Condo Project Advisor (FMCPA) for this property. Return project type, project name, and project ID.

        # TODO: Implement rule modifier logic
        pass
        # Flag: Condo Project Advisor Not Run (warning)
        # Condition: Condo property without FMCPA result
        # TODO: Add modifier flag condition
        # if <condition>:
        #     flags.append({
        #         "substep": "9.1",
        #         "title": "Condo Project Advisor Not Run",
        #         "severity": "warning",
        #         "details": "",
        #         "suggestion": "Run Freddie Mac Condo Project Advisor lookup",
        #         "resolved": False,
        #         "timestamp": datetime.now(timezone.utc).isoformat(),
        #         "modifier_source": "notes.txt",
        #     })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "9.1",
        "tool": "update_transmittal_summary",
        "flags_count": len(flags),
        "message": "Update Transmittal Summary completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[UPDATE_TRANSMITTAL_SUMMARY] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
