"""update_processor_closing — Tool for substep 15.2: Processor Closing Update

Step 15 (STEP_15): Processor Workflow and Closing
Phase: PROCESSOR_UPDATE

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def update_processor_closing(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Fill out the Processor Closing screen: set signing date and wire requested date.


    Call this tool during STEP_15 (Processor Workflow and Closing) as substep 15.2.    Reads LOS: signing_date, wire_requested_date    Flags: Signing Date Not Set (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[UPDATE_PROCESSOR_CLOSING] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    signing_date = _los(state, "signing_date")  # Field CX.SIGNING.DATE: Signing Date    wire_requested_date = _los(state, "wire_requested_date")  # Field CX.WIRE.REQUESTED.DATE: Wire Requested Date    # ── Rule: Signing Date Set ──
    # Signing date must be populated on the Processor Closing screen.
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Flag: Signing Date Not Set ──
    # Condition: Signing date is blank on Processor Closing screen
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "15.2",
    #         "title": "Signing Date Not Set",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Set the signing date before proceeding to submission",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "15.2",
        "tool": "update_processor_closing",
        "flags_count": len(flags),
        "message": "Processor Closing Update completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[UPDATE_PROCESSOR_CLOSING] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
