"""update_milestone — Tool for substep 17.3: Milestone Change and Processor Name

Step 17 (STEP_17): Submission
Phase: SUBMISSION

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def update_milestone(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Change loan milestone from "In Processing" to "Submitted to UW". Set the processor name field to state["processor_name"]. Check and close all outstanding tasks.


    Call this tool during STEP_17 (Submission) as substep 17.3.    Reads LOS: current_milestone, processor_name    Flags: Milestone Change Failed (critical), Processor Name Not Set (warning)    Writes: field corrections for CX.PROCESSOR.NAME    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[UPDATE_MILESTONE] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    current_milestone = _los(state, "current_milestone")  # Field CX.MILESTONE.CURRENT: Current Milestone    processor_name = _los(state, "processor_name")  # Field CX.PROCESSOR.NAME: Processor Name    # ── Rule: Milestone Changed to Submitted ──
    # Change milestone from In Processing → Submitted to UW. Set processor name. Verify all tasks are closed or note any outstanding.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Flag: Milestone Change Failed ──
    # Condition: Milestone could not be changed to Submitted
    # Severity: critical
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "17.3",
    #         "title": "Milestone Change Failed",
    #         "severity": "critical",
    #         "details": "",
    #         "suggestion": "Manually change milestone in Encompass",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Processor Name Not Set ──
    # Condition: Processor name field is empty after milestone change
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "17.3",
    #         "title": "Processor Name Not Set",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Set processor name in the loan record",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Field Updates ──
    field_updates = {}    # Field CX.PROCESSOR.NAME: {processor_name} (condition: always)
    # TODO: Set value
    # field_updates["CX.PROCESSOR.NAME"] = <computed_value>
    if field_updates:
        try:
            from shared.encompass_io import write_fields
            write_fields(loan_id, field_updates, state=state)
            logger.info(f"[UPDATE_MILESTONE] Wrote {len(field_updates)} field updates")
        except Exception as e:
            logger.error(f"[UPDATE_MILESTONE] Field write error: {e}")
            flags.append({
                "substep": "17.3",
                "title": "Field Write Error",
                "severity": "warning",
                "details": str(e),
                "suggestion": "Retry or escalate",
                "resolved": False,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "17.3",
        "tool": "update_milestone",
        "flags_count": len(flags),
        "message": "Milestone Change and Processor Name completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[UPDATE_MILESTONE] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
