"""update_processor_workflow — Tool for substep 15.1: Processor Workflow Update

Step 15 (STEP_15): Processor Workflow and Closing
Phase: PROCESSOR_UPDATE

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def update_processor_workflow(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Fill out the Processor Workflow screen: select Conforming or Non-Deliverable Investor Approval, set doc type (wet-signed / e-sign / hybrid), and confirm the loan has been submitted to UW milestone.


    Call this tool during STEP_15 (Processor Workflow and Closing) as substep 15.1.    Reads LOS: investor_type, doc_type    Flags: Investor Type Not Set (warning), Doc Type Not Set (warning)    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[UPDATE_PROCESSOR_WORKFLOW] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    investor_type = _los(state, "investor_type")  # Field CX.INVESTOR.TYPE: Investor Type (Conforming / Non-Del)    doc_type = _los(state, "doc_type")  # Field CX.DOC.TYPE: Doc Type (Wet / E-sign / Hybrid)    # ── Rule: Investor Type Set ──
    # Conforming or Non-Deliverable investor type must be selected.
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Rule: Doc Type Set ──
    # Signing doc type must be selected.
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Flag: Investor Type Not Set ──
    # Condition: Investor type not selected in Processor Workflow
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "15.1",
    #         "title": "Investor Type Not Set",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Select Conforming or Non-Deliverable Investor Approval",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Doc Type Not Set ──
    # Condition: Doc type not selected in Processor Workflow
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "15.1",
    #         "title": "Doc Type Not Set",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Select Wet-Signed / E-Sign / Hybrid for this loan",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })


    # ── Build result ──
    result = {
        "success": True,
        "substep": "15.1",
        "tool": "update_processor_workflow",
        "flags_count": len(flags),
        "message": "Processor Workflow Update completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[UPDATE_PROCESSOR_WORKFLOW] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
