"""update_borrower_vesting — Tool for substep 8.1: Update Borrower Vesting

Step 8 (STEP_08): Borrower Info - Vesting
Phase: FORM_UPDATES

Generated by Agent Factory. Edit the business logic (marked with TODO),
but do NOT modify the tool signature or state access patterns.

# FACTORY-LOCK: false
"""

import json
import logging
from datetime import datetime, timezone
from typing import Annotated, Optional

from langchain_core.messages import ToolMessage
from langchain_core.tools import InjectedToolCallId, tool
from langgraph.prebuilt import InjectedState
from langgraph.types import Command

from ._helpers import _los, _doc, _profile

logger = logging.getLogger(__name__)


@tool
def update_borrower_vesting(
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[dict, InjectedState],) -> Command:
    """Verify occupancy intent, populate vesting description from URLA Part 1 (married/unmarried/single). Build and confirm the Final Vesting string (e.g. "WILL OCCUPY / A SINGLE WOMAN OR UNMARRIED WOMAN"). Click Build Final Vesting when complete.


    Call this tool during STEP_08 (Borrower Info - Vesting) as substep 8.1.    Reads LOS: occupancy, marital_status, vesting_description, final_vesting, coborrower_first_name    Flags: Vesting Description Not Set (warning), Final Vesting Not Built (warning)    Writes: field corrections for CX.VESTING.DESCRIPTION    """
    loan_id = state.get("loan_id")
    if not loan_id:
        return Command(update={"messages": [ToolMessage(
            content=json.dumps({"error": "No loan_id in state. Run find_loan first."}),
            tool_call_id=tool_call_id,
        )]})

    logger.info(f"[UPDATE_BORROWER_VESTING] Starting for loan {str(loan_id)[:8]}...")

    flags = []
    # ── Read LOS Fields ──    occupancy = _los(state, "occupancy")  # Field 1811: Occupancy / Occupancy Intent    marital_status = _los(state, "marital_status")  # Field 1065: Borrower Marital Status    vesting_description = _los(state, "vesting_description")  # Field CX.VESTING.DESCRIPTION: Vesting Description    final_vesting = _los(state, "final_vesting")  # Field CX.FINAL.VESTING: Final Vesting    coborrower_first_name = _los(state, "coborrower_first_name")  # Field 4004: Co-Borrower First Name    # ── Rule: Vesting Consistent with Marital Status ──
    # If single/unmarried and no co-borrower: Sole Ownership, unmarried/single vesting language. If married: appropriate joint vesting or sole ownership with spousal signature.
    # 
    # Type: custom    # TODO: Implement this rule
    pass

    # ── Rule: Final Vesting Built ──
    # Final Vesting field must be populated after the Build Final Vesting action.
    # Type: existence_check    # TODO: Implement this rule
    pass

    # ── Flag: Vesting Description Not Set ──
    # Condition: Vesting description field is empty
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "8.1",
    #         "title": "Vesting Description Not Set",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Populate vesting description from marital status before building",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Flag: Final Vesting Not Built ──
    # Condition: Final Vesting field is empty after update
    # Severity: warning
    # TODO: Add condition check
    # if <condition>:
    #     flags.append({
    #         "substep": "8.1",
    #         "title": "Final Vesting Not Built",
    #         "severity": "warning",
    #         "details": "",
    #         "suggestion": "Click Build Final Vesting in Encompass",
    #         "resolved": False,
    #         "timestamp": datetime.now(timezone.utc).isoformat(),
    #     })

    # ── Field Updates ──
    field_updates = {}    # Field CX.VESTING.DESCRIPTION: {computed_vesting_description} (condition: always)
    # TODO: Set value
    # field_updates["CX.VESTING.DESCRIPTION"] = <computed_value>
    if field_updates:
        try:
            from shared.encompass_io import write_fields
            write_fields(loan_id, field_updates, state=state)
            logger.info(f"[UPDATE_BORROWER_VESTING] Wrote {len(field_updates)} field updates")
        except Exception as e:
            logger.error(f"[UPDATE_BORROWER_VESTING] Field write error: {e}")
            flags.append({
                "substep": "8.1",
                "title": "Field Write Error",
                "severity": "warning",
                "details": str(e),
                "suggestion": "Retry or escalate",
                "resolved": False,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            })

    # ── Build result ──
    result = {
        "success": True,
        "substep": "8.1",
        "tool": "update_borrower_vesting",
        "flags_count": len(flags),
        "message": "Update Borrower Vesting completed" + (f" with {len(flags)} flags" if flags else ""),
    }

    logger.info(f"[UPDATE_BORROWER_VESTING] {result['message']}")

    update = {
        "messages": [ToolMessage(content=json.dumps(result), tool_call_id=tool_call_id)],
    }
    if flags:
        update["flags"] = flags

    return Command(update=update)
