#!/usr/bin/env python3
"""Export the workflow step/substep map to workflow_steps.csv (repo root).

Source of truth: output/config/workflow_config.json (regenerated by
`python3.11 -m factory factory-reset`). Run this after any step/substep change
so the root CSV stays in sync:

    python3.11 scripts/export_workflow_csv.py
"""

from __future__ import annotations

import csv
import json
import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG = os.path.join(PROJECT_ROOT, "output", "config", "workflow_config.json")
OUT = os.path.join(PROJECT_ROOT, "workflow_steps.csv")

COLUMNS = [
    "Phase", "Phase_Name", "Step_ID", "Step_Num", "Step_Name",
    "Substep_ID", "Substep_Name", "Plan_File", "Tools",
]


def _phase_name(phase: str) -> str:
    return phase.replace("_", " ").title()


def main() -> None:
    with open(CONFIG) as f:
        cfg = json.load(f)

    steps = cfg["steps"]
    rows = []
    for step_id in cfg["step_order"]:
        step = steps.get(step_id)
        if not step:
            continue
        step_num = int(step_id.replace("STEP_", ""))
        phase = step.get("phase", "")
        substeps = step.get("substeps", {})
        for ss_key in sorted(substeps, key=lambda k: int(k)):
            ss = substeps[ss_key]
            rows.append({
                "Phase": phase,
                "Phase_Name": _phase_name(phase),
                "Step_ID": step_id,
                "Step_Num": step_num,
                "Step_Name": step.get("name", ""),
                "Substep_ID": f"{step_num}.{ss_key}",
                "Substep_Name": ss.get("name", ""),
                "Plan_File": step.get("plan_file", ""),
                "Tools": ";".join(ss.get("tools", [])),
            })

    with open(OUT, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Wrote {len(rows)} substep rows → {os.path.relpath(OUT, PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
